// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package catalogdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeTestStepGap = `-- name: CloseTestStepGap :exec
UPDATE test_steps SET position = position - 1
WHERE test_case_id = $1 AND position > $2
`

type CloseTestStepGapParams struct {
	TestCaseID    int64
	AfterPosition int32
}

func (q *Queries) CloseTestStepGap(ctx context.Context, arg CloseTestStepGapParams) error {
	_, err := q.db.Exec(ctx, closeTestStepGap, arg.TestCaseID, arg.AfterPosition)
	return err
}

const countTestCases = `-- name: CountTestCases :one
SELECT count(*) FROM test_cases
WHERE ($1::text IS NULL OR status = $1::text)
`

func (q *Queries) CountTestCases(ctx context.Context, status pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countTestCases, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTestSteps = `-- name: CountTestSteps :one
SELECT count(*) FROM test_steps WHERE test_case_id = $1
`

func (q *Queries) CountTestSteps(ctx context.Context, testCaseID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTestSteps, testCaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTestCase = `-- name: CreateTestCase :one
INSERT INTO test_cases (title, description, expected_result, automated)
VALUES ($1, $2, $3, $4)
RETURNING id, title, description, expected_result, status, automated, created_at, updated_at, deprecated_at
`

type CreateTestCaseParams struct {
	Title          string
	Description    string
	ExpectedResult string
	Automated      bool
}

func (q *Queries) CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, createTestCase,
		arg.Title,
		arg.Description,
		arg.ExpectedResult,
		arg.Automated,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ExpectedResult,
		&i.Status,
		&i.Automated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeprecatedAt,
	)
	return i, err
}

const createTestStep = `-- name: CreateTestStep :one
INSERT INTO test_steps (test_case_id, position, action, expected_result)
VALUES ($1, $2, $3, $4)
RETURNING id, test_case_id, position, action, expected_result, created_at, updated_at
`

type CreateTestStepParams struct {
	TestCaseID     int64
	Position       int32
	Action         string
	ExpectedResult string
}

func (q *Queries) CreateTestStep(ctx context.Context, arg CreateTestStepParams) (TestStep, error) {
	row := q.db.QueryRow(ctx, createTestStep,
		arg.TestCaseID,
		arg.Position,
		arg.Action,
		arg.ExpectedResult,
	)
	var i TestStep
	err := row.Scan(
		&i.ID,
		&i.TestCaseID,
		&i.Position,
		&i.Action,
		&i.ExpectedResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTestStep = `-- name: DeleteTestStep :one
DELETE FROM test_steps WHERE test_case_id = $1 AND id = $2
RETURNING position
`

type DeleteTestStepParams struct {
	TestCaseID int64
	ID         int64
}

func (q *Queries) DeleteTestStep(ctx context.Context, arg DeleteTestStepParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteTestStep, arg.TestCaseID, arg.ID)
	var position int32
	err := row.Scan(&position)
	return position, err
}

const deprecateTestCase = `-- name: DeprecateTestCase :one
UPDATE test_cases SET
    status        = 'deprecated',
    deprecated_at = coalesce(deprecated_at, now()),
    updated_at    = CASE WHEN status = 'deprecated' THEN updated_at ELSE now() END
WHERE id = $1
RETURNING id, title, description, expected_result, status, automated, created_at, updated_at, deprecated_at
`

func (q *Queries) DeprecateTestCase(ctx context.Context, id int64) (TestCase, error) {
	row := q.db.QueryRow(ctx, deprecateTestCase, id)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ExpectedResult,
		&i.Status,
		&i.Automated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeprecatedAt,
	)
	return i, err
}

const getTestCase = `-- name: GetTestCase :one
SELECT id, title, description, expected_result, status, automated, created_at, updated_at, deprecated_at FROM test_cases WHERE id = $1
`

func (q *Queries) GetTestCase(ctx context.Context, id int64) (TestCase, error) {
	row := q.db.QueryRow(ctx, getTestCase, id)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ExpectedResult,
		&i.Status,
		&i.Automated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeprecatedAt,
	)
	return i, err
}

const listAllTestSteps = `-- name: ListAllTestSteps :many
SELECT id, test_case_id, position, action, expected_result, created_at, updated_at FROM test_steps WHERE test_case_id = $1 ORDER BY position
`

func (q *Queries) ListAllTestSteps(ctx context.Context, testCaseID int64) ([]TestStep, error) {
	rows, err := q.db.Query(ctx, listAllTestSteps, testCaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestStep
	for rows.Next() {
		var i TestStep
		if err := rows.Scan(
			&i.ID,
			&i.TestCaseID,
			&i.Position,
			&i.Action,
			&i.ExpectedResult,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngestionView = `-- name: ListIngestionView :many
SELECT id, status, (status = 'active' AND automated)::boolean AS expected, coalesce(id = ANY($1::bigint[]), false)::boolean AS referenced
FROM test_cases
WHERE (status = 'active' AND automated) OR id = ANY($1::bigint[])
ORDER BY id
`

type ListIngestionViewRow struct {
	ID         int64
	Status     string
	Expected   bool
	Referenced bool
}

// One statement, so the expected universe (active AND automated) and the status
// of the referenced TC-IDs come from the same snapshot: a deprecation committed
// during an ingestion cannot put a TC in one and not the other.
func (q *Queries) ListIngestionView(ctx context.Context, ids []int64) ([]ListIngestionViewRow, error) {
	rows, err := q.db.Query(ctx, listIngestionView, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIngestionViewRow
	for rows.Next() {
		var i ListIngestionViewRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Expected,
			&i.Referenced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCases = `-- name: ListTestCases :many
SELECT id, title, description, expected_result, status, automated, created_at, updated_at, deprecated_at FROM test_cases
WHERE ($1::text IS NULL OR status = $1::text)
ORDER BY id DESC
LIMIT $3 OFFSET $2
`

type ListTestCasesParams struct {
	Status     pgtype.Text
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListTestCases(ctx context.Context, arg ListTestCasesParams) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listTestCases, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestCase
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ExpectedResult,
			&i.Status,
			&i.Automated,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeprecatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSteps = `-- name: ListTestSteps :many
SELECT id, test_case_id, position, action, expected_result, created_at, updated_at FROM test_steps
WHERE test_case_id = $1
ORDER BY position
LIMIT $3 OFFSET $2
`

type ListTestStepsParams struct {
	TestCaseID int64
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListTestSteps(ctx context.Context, arg ListTestStepsParams) ([]TestStep, error) {
	rows, err := q.db.Query(ctx, listTestSteps, arg.TestCaseID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestStep
	for rows.Next() {
		var i TestStep
		if err := rows.Scan(
			&i.ID,
			&i.TestCaseID,
			&i.Position,
			&i.Action,
			&i.ExpectedResult,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTestCase = `-- name: LockTestCase :one
SELECT id FROM test_cases WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockTestCase(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockTestCase, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const reactivateTestCase = `-- name: ReactivateTestCase :one
UPDATE test_cases SET
    status        = 'active',
    deprecated_at = NULL,
    updated_at    = CASE WHEN status = 'active' THEN updated_at ELSE now() END
WHERE id = $1
RETURNING id, title, description, expected_result, status, automated, created_at, updated_at, deprecated_at
`

func (q *Queries) ReactivateTestCase(ctx context.Context, id int64) (TestCase, error) {
	row := q.db.QueryRow(ctx, reactivateTestCase, id)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ExpectedResult,
		&i.Status,
		&i.Automated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeprecatedAt,
	)
	return i, err
}

const setTestStepPosition = `-- name: SetTestStepPosition :exec
UPDATE test_steps SET position = $1, updated_at = now()
WHERE test_case_id = $2 AND id = $3
`

type SetTestStepPositionParams struct {
	Position   int32
	TestCaseID int64
	ID         int64
}

func (q *Queries) SetTestStepPosition(ctx context.Context, arg SetTestStepPositionParams) error {
	_, err := q.db.Exec(ctx, setTestStepPosition, arg.Position, arg.TestCaseID, arg.ID)
	return err
}

const shiftTestStepsDown = `-- name: ShiftTestStepsDown :exec
UPDATE test_steps SET position = position + 1
WHERE test_case_id = $1 AND position >= $2
`

type ShiftTestStepsDownParams struct {
	TestCaseID   int64
	FromPosition int32
}

func (q *Queries) ShiftTestStepsDown(ctx context.Context, arg ShiftTestStepsDownParams) error {
	_, err := q.db.Exec(ctx, shiftTestStepsDown, arg.TestCaseID, arg.FromPosition)
	return err
}

const updateTestCase = `-- name: UpdateTestCase :one
UPDATE test_cases SET
    title           = coalesce($1, title),
    description     = coalesce($2, description),
    expected_result = coalesce($3, expected_result),
    automated       = coalesce($4, automated),
    updated_at      = now()
WHERE id = $5
RETURNING id, title, description, expected_result, status, automated, created_at, updated_at, deprecated_at
`

type UpdateTestCaseParams struct {
	Title          pgtype.Text
	Description    pgtype.Text
	ExpectedResult pgtype.Text
	Automated      pgtype.Bool
	ID             int64
}

func (q *Queries) UpdateTestCase(ctx context.Context, arg UpdateTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, updateTestCase,
		arg.Title,
		arg.Description,
		arg.ExpectedResult,
		arg.Automated,
		arg.ID,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ExpectedResult,
		&i.Status,
		&i.Automated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeprecatedAt,
	)
	return i, err
}

const updateTestStep = `-- name: UpdateTestStep :one
UPDATE test_steps SET
    action          = coalesce($1, action),
    expected_result = coalesce($2, expected_result),
    updated_at      = now()
WHERE test_case_id = $3 AND id = $4
RETURNING id, test_case_id, position, action, expected_result, created_at, updated_at
`

type UpdateTestStepParams struct {
	Action         pgtype.Text
	ExpectedResult pgtype.Text
	TestCaseID     int64
	ID             int64
}

func (q *Queries) UpdateTestStep(ctx context.Context, arg UpdateTestStepParams) (TestStep, error) {
	row := q.db.QueryRow(ctx, updateTestStep,
		arg.Action,
		arg.ExpectedResult,
		arg.TestCaseID,
		arg.ID,
	)
	var i TestStep
	err := row.Scan(
		&i.ID,
		&i.TestCaseID,
		&i.Position,
		&i.Action,
		&i.ExpectedResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
