// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package catalogdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addIssueLinks = `-- name: AddIssueLinks :exec
INSERT INTO issue_test_cases (issue_id, project_id, test_case_id)
SELECT $1, $2, unnest($3::bigint[])
ON CONFLICT DO NOTHING
`

type AddIssueLinksParams struct {
	IssueID     int64
	ProjectID   int64
	TestCaseIds []int64
}

func (q *Queries) AddIssueLinks(ctx context.Context, arg AddIssueLinksParams) error {
	_, err := q.db.Exec(ctx, addIssueLinks, arg.IssueID, arg.ProjectID, arg.TestCaseIds)
	return err
}

const addRequirementLinks = `-- name: AddRequirementLinks :exec
INSERT INTO requirement_test_cases (requirement_id, project_id, test_case_id)
SELECT $1, $2, unnest($3::bigint[])
ON CONFLICT DO NOTHING
`

type AddRequirementLinksParams struct {
	RequirementID int64
	ProjectID     int64
	TestCaseIds   []int64
}

func (q *Queries) AddRequirementLinks(ctx context.Context, arg AddRequirementLinksParams) error {
	_, err := q.db.Exec(ctx, addRequirementLinks, arg.RequirementID, arg.ProjectID, arg.TestCaseIds)
	return err
}

const addSuiteCases = `-- name: AddSuiteCases :exec
INSERT INTO test_suite_cases (suite_id, project_id, test_case_id)
SELECT $1, $2, unnest($3::bigint[])
ON CONFLICT DO NOTHING
`

type AddSuiteCasesParams struct {
	SuiteID     int64
	ProjectID   int64
	TestCaseIds []int64
}

func (q *Queries) AddSuiteCases(ctx context.Context, arg AddSuiteCasesParams) error {
	_, err := q.db.Exec(ctx, addSuiteCases, arg.SuiteID, arg.ProjectID, arg.TestCaseIds)
	return err
}

const addTestCaseTags = `-- name: AddTestCaseTags :exec
INSERT INTO test_case_tags (test_case_id, tag)
SELECT $1, unnest($2::text[])
ON CONFLICT DO NOTHING
`

type AddTestCaseTagsParams struct {
	TestCaseID int64
	Tags       []string
}

func (q *Queries) AddTestCaseTags(ctx context.Context, arg AddTestCaseTagsParams) error {
	_, err := q.db.Exec(ctx, addTestCaseTags, arg.TestCaseID, arg.Tags)
	return err
}

const clearTestCaseClassification = `-- name: ClearTestCaseClassification :exec
DELETE FROM test_case_classifications WHERE test_case_id = $1 AND dimension_id = $2
`

type ClearTestCaseClassificationParams struct {
	TestCaseID  int64
	DimensionID int64
}

func (q *Queries) ClearTestCaseClassification(ctx context.Context, arg ClearTestCaseClassificationParams) error {
	_, err := q.db.Exec(ctx, clearTestCaseClassification, arg.TestCaseID, arg.DimensionID)
	return err
}

const closeTestStepGap = `-- name: CloseTestStepGap :exec
UPDATE test_steps SET position = position - 1
WHERE test_case_id = $1 AND position > $2
`

type CloseTestStepGapParams struct {
	TestCaseID    int64
	AfterPosition int32
}

func (q *Queries) CloseTestStepGap(ctx context.Context, arg CloseTestStepGapParams) error {
	_, err := q.db.Exec(ctx, closeTestStepGap, arg.TestCaseID, arg.AfterPosition)
	return err
}

const countProjects = `-- name: CountProjects :one
SELECT count(*) FROM projects
WHERE $1::bigint[] IS NULL OR id = ANY($1::bigint[])
`

func (q *Queries) CountProjects(ctx context.Context, projectIds []int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects, projectIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTestCases = `-- name: CountTestCases :one
SELECT count(*) FROM test_cases
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::bigint[] IS NULL OR project_id = ANY($2::bigint[]))
  AND ($3::text IS NULL OR EXISTS (SELECT 1 FROM test_case_tags t WHERE t.test_case_id = test_cases.id AND t.tag = $3::text))
  AND (coalesce(cardinality($4::text[]), 0) = 0 OR (
      SELECT count(*) FROM test_case_classifications c
      JOIN classification_dimensions d ON d.id = c.dimension_id
      JOIN classification_values v ON v.id = c.value_id
      WHERE c.test_case_id = test_cases.id AND d.key || ':' || v.key = ANY($4::text[])
  ) = cardinality($4::text[]))
  AND ($5::bigint IS NULL OR EXISTS (SELECT 1 FROM test_suite_cases m WHERE m.suite_id = $5::bigint AND m.test_case_id = test_cases.id))
  AND ($6::boolean IS NULL OR automated = $6::boolean)
  AND ($7::bigint IS NULL OR number = $7::bigint)
`

type CountTestCasesParams struct {
	Status     pgtype.Text
	ProjectIds []int64
	Tag        pgtype.Text
	Classified []string
	SuiteID    pgtype.Int8
	Automated  pgtype.Bool
	Number     pgtype.Int8
}

func (q *Queries) CountTestCases(ctx context.Context, arg CountTestCasesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTestCases,
		arg.Status,
		arg.ProjectIds,
		arg.Tag,
		arg.Classified,
		arg.SuiteID,
		arg.Automated,
		arg.Number,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTestSteps = `-- name: CountTestSteps :one
SELECT count(*) FROM test_steps WHERE test_case_id = $1
`

func (q *Queries) CountTestSteps(ctx context.Context, testCaseID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTestSteps, testCaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDimension = `-- name: CreateDimension :one
INSERT INTO classification_dimensions (project_id, key, name)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, key) DO NOTHING
RETURNING id, project_id, key, name, built_in, archived_at, created_at
`

type CreateDimensionParams struct {
	ProjectID int64
	Key       string
	Name      string
}

func (q *Queries) CreateDimension(ctx context.Context, arg CreateDimensionParams) (ClassificationDimension, error) {
	row := q.db.QueryRow(ctx, createDimension, arg.ProjectID, arg.Key, arg.Name)
	var i ClassificationDimension
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.BuiltIn,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createDimensionValue = `-- name: CreateDimensionValue :one
INSERT INTO classification_values (dimension_id, key, name, position)
SELECT $1, $2, $3, coalesce(max(position), 0) + 1 FROM classification_values WHERE dimension_id = $1
ON CONFLICT (dimension_id, key) DO NOTHING
RETURNING id, dimension_id, key, name, position, archived_at, created_at
`

type CreateDimensionValueParams struct {
	DimensionID int64
	Key         string
	Name        string
}

// Appended after the dimension's last value; no row when the key already exists in the dimension.
func (q *Queries) CreateDimensionValue(ctx context.Context, arg CreateDimensionValueParams) (ClassificationValue, error) {
	row := q.db.QueryRow(ctx, createDimensionValue, arg.DimensionID, arg.Key, arg.Name)
	var i ClassificationValue
	err := row.Scan(
		&i.ID,
		&i.DimensionID,
		&i.Key,
		&i.Name,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (key, name, description)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO NOTHING
RETURNING id, key, name, description, next_number, created_at, updated_at, next_requirement_number, next_issue_number
`

type CreateProjectParams struct {
	Key         string
	Name        string
	Description string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Key, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.NextNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextRequirementNumber,
		&i.NextIssueNumber,
	)
	return i, err
}

const createSuite = `-- name: CreateSuite :one
INSERT INTO test_suites (project_id, key, name, description, kind, query_tag, query_classified)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (project_id, key) DO NOTHING
RETURNING id
`

type CreateSuiteParams struct {
	ProjectID       int64
	Key             string
	Name            string
	Description     string
	Kind            string
	QueryTag        pgtype.Text
	QueryClassified []string
}

func (q *Queries) CreateSuite(ctx context.Context, arg CreateSuiteParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSuite,
		arg.ProjectID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Kind,
		arg.QueryTag,
		arg.QueryClassified,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTestCase = `-- name: CreateTestCase :one
WITH n AS (
    UPDATE projects SET next_number = next_number + 1
    WHERE id = $1
    RETURNING next_number - 1 AS number
)
INSERT INTO test_cases (project_id, number, title, description, expected_result, automated)
SELECT $1, n.number, $2, $3, $4, $5 FROM n
RETURNING id, title, description, expected_result, status, automated, created_at, updated_at, deprecated_at, project_id, number, version
`

type CreateTestCaseParams struct {
	ProjectID      int64
	Title          string
	Description    string
	ExpectedResult string
	Automated      bool
}

// The number comes from the project's counter in the same statement: numbers
// are assigned per project, in order, and never reused. No row when the
// project does not exist.
func (q *Queries) CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, createTestCase,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.ExpectedResult,
		arg.Automated,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ExpectedResult,
		&i.Status,
		&i.Automated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeprecatedAt,
		&i.ProjectID,
		&i.Number,
		&i.Version,
	)
	return i, err
}

const createTestStep = `-- name: CreateTestStep :one
INSERT INTO test_steps (test_case_id, position, action, expected_result)
VALUES ($1, $2, $3, $4)
RETURNING id, test_case_id, position, action, expected_result, created_at, updated_at
`

type CreateTestStepParams struct {
	TestCaseID     int64
	Position       int32
	Action         string
	ExpectedResult string
}

func (q *Queries) CreateTestStep(ctx context.Context, arg CreateTestStepParams) (TestStep, error) {
	row := q.db.QueryRow(ctx, createTestStep,
		arg.TestCaseID,
		arg.Position,
		arg.Action,
		arg.ExpectedResult,
	)
	var i TestStep
	err := row.Scan(
		&i.ID,
		&i.TestCaseID,
		&i.Position,
		&i.Action,
		&i.ExpectedResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIssueLinks = `-- name: DeleteIssueLinks :exec
DELETE FROM issue_test_cases WHERE issue_id = $1 AND NOT (test_case_id = ANY(coalesce($2::bigint[], '{}')))
`

type DeleteIssueLinksParams struct {
	IssueID int64
	Keep    []int64
}

func (q *Queries) DeleteIssueLinks(ctx context.Context, arg DeleteIssueLinksParams) error {
	_, err := q.db.Exec(ctx, deleteIssueLinks, arg.IssueID, arg.Keep)
	return err
}

const deleteRequirementLinks = `-- name: DeleteRequirementLinks :exec
DELETE FROM requirement_test_cases WHERE requirement_id = $1 AND NOT (test_case_id = ANY(coalesce($2::bigint[], '{}')))
`

type DeleteRequirementLinksParams struct {
	RequirementID int64
	Keep          []int64
}

func (q *Queries) DeleteRequirementLinks(ctx context.Context, arg DeleteRequirementLinksParams) error {
	_, err := q.db.Exec(ctx, deleteRequirementLinks, arg.RequirementID, arg.Keep)
	return err
}

const deleteSuiteCases = `-- name: DeleteSuiteCases :exec
DELETE FROM test_suite_cases WHERE suite_id = $1 AND NOT (test_case_id = ANY(coalesce($2::bigint[], '{}')))
`

type DeleteSuiteCasesParams struct {
	SuiteID int64
	Keep    []int64
}

// Removes the members not in keep (all of them when keep is empty).
func (q *Queries) DeleteSuiteCases(ctx context.Context, arg DeleteSuiteCasesParams) error {
	_, err := q.db.Exec(ctx, deleteSuiteCases, arg.SuiteID, arg.Keep)
	return err
}

const deleteTestCaseTags = `-- name: DeleteTestCaseTags :exec
DELETE FROM test_case_tags WHERE test_case_id = $1 AND NOT (tag = ANY(coalesce($2::text[], '{}')))
`

type DeleteTestCaseTagsParams struct {
	TestCaseID int64
	Keep       []string
}

// Removes the tags not in keep (all of them when keep is empty).
func (q *Queries) DeleteTestCaseTags(ctx context.Context, arg DeleteTestCaseTagsParams) error {
	_, err := q.db.Exec(ctx, deleteTestCaseTags, arg.TestCaseID, arg.Keep)
	return err
}

const deleteTestStep = `-- name: DeleteTestStep :one
DELETE FROM test_steps WHERE test_case_id = $1 AND id = $2
RETURNING position
`

type DeleteTestStepParams struct {
	TestCaseID int64
	ID         int64
}

func (q *Queries) DeleteTestStep(ctx context.Context, arg DeleteTestStepParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteTestStep, arg.TestCaseID, arg.ID)
	var position int32
	err := row.Scan(&position)
	return position, err
}

const deprecateTestCase = `-- name: DeprecateTestCase :one
UPDATE test_cases SET
    status        = 'deprecated',
    deprecated_at = coalesce(deprecated_at, now()),
    updated_at    = CASE WHEN status = 'deprecated' THEN updated_at ELSE now() END
WHERE id = $1
RETURNING id, title, description, expected_result, status, automated, created_at, updated_at, deprecated_at, project_id, number, version
`

func (q *Queries) DeprecateTestCase(ctx context.Context, id int64) (TestCase, error) {
	row := q.db.QueryRow(ctx, deprecateTestCase, id)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ExpectedResult,
		&i.Status,
		&i.Automated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeprecatedAt,
		&i.ProjectID,
		&i.Number,
		&i.Version,
	)
	return i, err
}

const getIssue = `-- name: GetIssue :one
SELECT i.id, i.project_id, i.provider, i.external_id, i.title, i.description, i.url, i.state, i.provider_status, i.closed_at, i.last_synced_at, i.created_at, i.updated_at, coalesce((SELECT array_agg(l.test_case_id ORDER BY l.test_case_id) FROM issue_test_cases l WHERE l.issue_id = i.id), '{}')::bigint[] AS test_case_ids
FROM issues i WHERE i.project_id = $1 AND i.id = $2
`

type GetIssueParams struct {
	ProjectID int64
	ID        int64
}

type GetIssueRow struct {
	ID             int64
	ProjectID      int64
	Provider       string
	ExternalID     string
	Title          string
	Description    string
	Url            string
	State          string
	ProviderStatus string
	ClosedAt       pgtype.Timestamptz
	LastSyncedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	TestCaseIds    []int64
}

func (q *Queries) GetIssue(ctx context.Context, arg GetIssueParams) (GetIssueRow, error) {
	row := q.db.QueryRow(ctx, getIssue, arg.ProjectID, arg.ID)
	var i GetIssueRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.ExternalID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.State,
		&i.ProviderStatus,
		&i.ClosedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TestCaseIds,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, key, name, description, next_number, created_at, updated_at, next_requirement_number, next_issue_number FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.NextNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextRequirementNumber,
		&i.NextIssueNumber,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, key, name, description, next_number, created_at, updated_at, next_requirement_number, next_issue_number FROM projects WHERE key = $1
`

func (q *Queries) GetProjectByKey(ctx context.Context, key string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByKey, key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.NextNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextRequirementNumber,
		&i.NextIssueNumber,
	)
	return i, err
}

const getRequirement = `-- name: GetRequirement :one
SELECT r.id, r.project_id, r.provider, r.external_id, r.title, r.description, r.url, r.provider_status, r.archived_at, r.last_synced_at, r.created_at, r.updated_at, coalesce((SELECT array_agg(l.test_case_id ORDER BY l.test_case_id) FROM requirement_test_cases l WHERE l.requirement_id = r.id), '{}')::bigint[] AS test_case_ids
FROM requirements r WHERE r.project_id = $1 AND r.id = $2
`

type GetRequirementParams struct {
	ProjectID int64
	ID        int64
}

type GetRequirementRow struct {
	ID             int64
	ProjectID      int64
	Provider       string
	ExternalID     string
	Title          string
	Description    string
	Url            string
	ProviderStatus string
	ArchivedAt     pgtype.Timestamptz
	LastSyncedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	TestCaseIds    []int64
}

func (q *Queries) GetRequirement(ctx context.Context, arg GetRequirementParams) (GetRequirementRow, error) {
	row := q.db.QueryRow(ctx, getRequirement, arg.ProjectID, arg.ID)
	var i GetRequirementRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.ExternalID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.ProviderStatus,
		&i.ArchivedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TestCaseIds,
	)
	return i, err
}

const getSuite = `-- name: GetSuite :one
SELECT s.id, s.project_id, s.key, s.name, s.description, s.kind, s.query_tag, s.query_classified, s.archived_at, s.created_at, s.updated_at, (SELECT count(*) FROM test_suite_cases c WHERE c.suite_id = s.id)::int AS case_count
FROM test_suites s WHERE s.project_id = $1 AND s.key = $2
`

type GetSuiteParams struct {
	ProjectID int64
	Key       string
}

type GetSuiteRow struct {
	ID              int64
	ProjectID       int64
	Key             string
	Name            string
	Description     string
	Kind            string
	QueryTag        pgtype.Text
	QueryClassified []string
	ArchivedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	CaseCount       int32
}

func (q *Queries) GetSuite(ctx context.Context, arg GetSuiteParams) (GetSuiteRow, error) {
	row := q.db.QueryRow(ctx, getSuite, arg.ProjectID, arg.Key)
	var i GetSuiteRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.QueryTag,
		&i.QueryClassified,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CaseCount,
	)
	return i, err
}

const getTestCase = `-- name: GetTestCase :one
SELECT id, title, description, expected_result, status, automated, created_at, updated_at, deprecated_at, project_id, number, version FROM test_cases WHERE id = $1
`

func (q *Queries) GetTestCase(ctx context.Context, id int64) (TestCase, error) {
	row := q.db.QueryRow(ctx, getTestCase, id)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ExpectedResult,
		&i.Status,
		&i.Automated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeprecatedAt,
		&i.ProjectID,
		&i.Number,
		&i.Version,
	)
	return i, err
}

const listAllTestSteps = `-- name: ListAllTestSteps :many
SELECT id, test_case_id, position, action, expected_result, created_at, updated_at FROM test_steps WHERE test_case_id = $1 ORDER BY position
`

func (q *Queries) ListAllTestSteps(ctx context.Context, testCaseID int64) ([]TestStep, error) {
	rows, err := q.db.Query(ctx, listAllTestSteps, testCaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestStep
	for rows.Next() {
		var i TestStep
		if err := rows.Scan(
			&i.ID,
			&i.TestCaseID,
			&i.Position,
			&i.Action,
			&i.ExpectedResult,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDimensionValues = `-- name: ListDimensionValues :many
SELECT v.id, v.dimension_id, v.key, v.name, v.position, v.archived_at, v.created_at FROM classification_values v
JOIN classification_dimensions d ON d.id = v.dimension_id
WHERE d.project_id = $1
ORDER BY v.dimension_id, v.position, v.id
`

func (q *Queries) ListDimensionValues(ctx context.Context, projectID int64) ([]ClassificationValue, error) {
	rows, err := q.db.Query(ctx, listDimensionValues, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClassificationValue
	for rows.Next() {
		var i ClassificationValue
		if err := rows.Scan(
			&i.ID,
			&i.DimensionID,
			&i.Key,
			&i.Name,
			&i.Position,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDimensions = `-- name: ListDimensions :many
SELECT id, project_id, key, name, built_in, archived_at, created_at FROM classification_dimensions WHERE project_id = $1
ORDER BY built_in DESC, id
`

// A project's classification dimensions: built-ins first in their seeded order, then the project's own by key.
func (q *Queries) ListDimensions(ctx context.Context, projectID int64) ([]ClassificationDimension, error) {
	rows, err := q.db.Query(ctx, listDimensions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClassificationDimension
	for rows.Next() {
		var i ClassificationDimension
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.BuiltIn,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngestionView = `-- name: ListIngestionView :many
SELECT id, number, status, (status = 'active' AND automated)::boolean AS expected, coalesce(number = ANY($1::bigint[]), false)::boolean AS referenced
FROM test_cases
WHERE project_id = $2 AND ((status = 'active' AND automated) OR number = ANY($1::bigint[]))
ORDER BY id
`

type ListIngestionViewParams struct {
	Numbers   []int64
	ProjectID int64
}

type ListIngestionViewRow struct {
	ID         int64
	Number     int64
	Status     string
	Expected   bool
	Referenced bool
}

// One statement, so the expected universe of the project (active AND automated)
// and the status of the referenced numbers come from the same snapshot: a
// deprecation committed during an ingestion cannot put a TC in one and not the other.
func (q *Queries) ListIngestionView(ctx context.Context, arg ListIngestionViewParams) ([]ListIngestionViewRow, error) {
	rows, err := q.db.Query(ctx, listIngestionView, arg.Numbers, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIngestionViewRow
	for rows.Next() {
		var i ListIngestionViewRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.Expected,
			&i.Referenced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssues = `-- name: ListIssues :many
SELECT i.id, i.project_id, i.provider, i.external_id, i.title, i.description, i.url, i.state, i.provider_status, i.closed_at, i.last_synced_at, i.created_at, i.updated_at, coalesce((SELECT array_agg(l.test_case_id ORDER BY l.test_case_id) FROM issue_test_cases l WHERE l.issue_id = i.id), '{}')::bigint[] AS test_case_ids
FROM issues i
WHERE i.project_id = $1
  AND ($2::text IS NULL OR i.state = $2::text)
  AND ($3::bigint IS NULL OR EXISTS (SELECT 1 FROM issue_test_cases x WHERE x.issue_id = i.id AND x.test_case_id = $3::bigint))
ORDER BY i.id DESC
`

type ListIssuesParams struct {
	ProjectID  int64
	State      pgtype.Text
	TestCaseID pgtype.Int8
}

type ListIssuesRow struct {
	ID             int64
	ProjectID      int64
	Provider       string
	ExternalID     string
	Title          string
	Description    string
	Url            string
	State          string
	ProviderStatus string
	ClosedAt       pgtype.Timestamptz
	LastSyncedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	TestCaseIds    []int64
}

// A project's issues (optionally only those linked to a test case, or in one state), newest first, with their linked
// test cases.
func (q *Queries) ListIssues(ctx context.Context, arg ListIssuesParams) ([]ListIssuesRow, error) {
	rows, err := q.db.Query(ctx, listIssues, arg.ProjectID, arg.State, arg.TestCaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssuesRow
	for rows.Next() {
		var i ListIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Provider,
			&i.ExternalID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.State,
			&i.ProviderStatus,
			&i.ClosedAt,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TestCaseIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectCaseIDs = `-- name: ListProjectCaseIDs :many
SELECT id FROM test_cases WHERE project_id = $1 AND id = ANY($2::bigint[]) ORDER BY id
`

type ListProjectCaseIDsParams struct {
	ProjectID int64
	Ids       []int64
}

// Which of the given ids are test cases of the project.
func (q *Queries) ListProjectCaseIDs(ctx context.Context, arg ListProjectCaseIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listProjectCaseIDs, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, key, name, description, next_number, created_at, updated_at, next_requirement_number, next_issue_number FROM projects
WHERE $1::bigint[] IS NULL OR id = ANY($1::bigint[])
ORDER BY key LIMIT $3 OFFSET $2
`

type ListProjectsParams struct {
	ProjectIds []int64
	PageOffset int32
	PageLimit  int32
}

// project_ids NULL means every project (administrators); otherwise only those.
func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.ProjectIds, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.NextNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextRequirementNumber,
			&i.NextIssueNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequirements = `-- name: ListRequirements :many
SELECT r.id, r.project_id, r.provider, r.external_id, r.title, r.description, r.url, r.provider_status, r.archived_at, r.last_synced_at, r.created_at, r.updated_at, coalesce((SELECT array_agg(l.test_case_id ORDER BY l.test_case_id) FROM requirement_test_cases l WHERE l.requirement_id = r.id), '{}')::bigint[] AS test_case_ids
FROM requirements r
WHERE r.project_id = $1
  AND ($2::bigint IS NULL OR EXISTS (SELECT 1 FROM requirement_test_cases x WHERE x.requirement_id = r.id AND x.test_case_id = $2::bigint))
ORDER BY r.id DESC
`

type ListRequirementsParams struct {
	ProjectID  int64
	TestCaseID pgtype.Int8
}

type ListRequirementsRow struct {
	ID             int64
	ProjectID      int64
	Provider       string
	ExternalID     string
	Title          string
	Description    string
	Url            string
	ProviderStatus string
	ArchivedAt     pgtype.Timestamptz
	LastSyncedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	TestCaseIds    []int64
}

// A project's requirements (optionally only those a test case covers), newest first, with their linked test cases.
func (q *Queries) ListRequirements(ctx context.Context, arg ListRequirementsParams) ([]ListRequirementsRow, error) {
	rows, err := q.db.Query(ctx, listRequirements, arg.ProjectID, arg.TestCaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequirementsRow
	for rows.Next() {
		var i ListRequirementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Provider,
			&i.ExternalID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.ProviderStatus,
			&i.ArchivedAt,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TestCaseIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuiteCaseIDs = `-- name: ListSuiteCaseIDs :many
SELECT test_case_id FROM test_suite_cases WHERE suite_id = $1 ORDER BY test_case_id
`

func (q *Queries) ListSuiteCaseIDs(ctx context.Context, suiteID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listSuiteCaseIDs, suiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var test_case_id int64
		if err := rows.Scan(&test_case_id); err != nil {
			return nil, err
		}
		items = append(items, test_case_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuites = `-- name: ListSuites :many
SELECT s.id, s.project_id, s.key, s.name, s.description, s.kind, s.query_tag, s.query_classified, s.archived_at, s.created_at, s.updated_at, (SELECT count(*) FROM test_suite_cases c WHERE c.suite_id = s.id)::int AS case_count
FROM test_suites s WHERE s.project_id = $1 ORDER BY s.key
`

type ListSuitesRow struct {
	ID              int64
	ProjectID       int64
	Key             string
	Name            string
	Description     string
	Kind            string
	QueryTag        pgtype.Text
	QueryClassified []string
	ArchivedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	CaseCount       int32
}

// A project's suites by key, with the number of test cases a static suite lists.
func (q *Queries) ListSuites(ctx context.Context, projectID int64) ([]ListSuitesRow, error) {
	rows, err := q.db.Query(ctx, listSuites, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuitesRow
	for rows.Next() {
		var i ListSuitesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Kind,
			&i.QueryTag,
			&i.QueryClassified,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CaseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCaseClassifications = `-- name: ListTestCaseClassifications :many
SELECT c.test_case_id, d.key AS dimension, v.key AS value
FROM test_case_classifications c
JOIN classification_dimensions d ON d.id = c.dimension_id
JOIN classification_values v ON v.id = c.value_id
WHERE c.test_case_id = ANY($1::bigint[])
ORDER BY c.test_case_id, d.id
`

type ListTestCaseClassificationsRow struct {
	TestCaseID int64
	Dimension  string
	Value      string
}

// The classification of the given test cases as dimension and value keys.
func (q *Queries) ListTestCaseClassifications(ctx context.Context, ids []int64) ([]ListTestCaseClassificationsRow, error) {
	rows, err := q.db.Query(ctx, listTestCaseClassifications, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTestCaseClassificationsRow
	for rows.Next() {
		var i ListTestCaseClassificationsRow
		if err := rows.Scan(&i.TestCaseID, &i.Dimension, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCaseIDs = `-- name: ListTestCaseIDs :many
SELECT id FROM test_cases
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::bigint[] IS NULL OR project_id = ANY($2::bigint[]))
  AND ($3::text IS NULL OR EXISTS (SELECT 1 FROM test_case_tags t WHERE t.test_case_id = test_cases.id AND t.tag = $3::text))
  AND (coalesce(cardinality($4::text[]), 0) = 0 OR (
      SELECT count(*) FROM test_case_classifications c
      JOIN classification_dimensions d ON d.id = c.dimension_id
      JOIN classification_values v ON v.id = c.value_id
      WHERE c.test_case_id = test_cases.id AND d.key || ':' || v.key = ANY($4::text[])
  ) = cardinality($4::text[]))
  AND ($5::bigint IS NULL OR EXISTS (SELECT 1 FROM test_suite_cases m WHERE m.suite_id = $5::bigint AND m.test_case_id = test_cases.id))
  AND ($6::boolean IS NULL OR automated = $6::boolean)
ORDER BY id
`

type ListTestCaseIDsParams struct {
	Status     pgtype.Text
	ProjectIds []int64
	Tag        pgtype.Text
	Classified []string
	SuiteID    pgtype.Int8
	Automated  pgtype.Bool
}

// The ids of every test case the filters select (a suite's selection for a run), ascending.
func (q *Queries) ListTestCaseIDs(ctx context.Context, arg ListTestCaseIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listTestCaseIDs,
		arg.Status,
		arg.ProjectIds,
		arg.Tag,
		arg.Classified,
		arg.SuiteID,
		arg.Automated,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCaseKeys = `-- name: ListTestCaseKeys :many
SELECT id, project_id, number FROM test_cases WHERE id = ANY($1::bigint[])
`

type ListTestCaseKeysRow struct {
	ID        int64
	ProjectID int64
	Number    int64
}

// The identity (project and number) of the given test cases, for display.
func (q *Queries) ListTestCaseKeys(ctx context.Context, ids []int64) ([]ListTestCaseKeysRow, error) {
	rows, err := q.db.Query(ctx, listTestCaseKeys, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTestCaseKeysRow
	for rows.Next() {
		var i ListTestCaseKeysRow
		if err := rows.Scan(&i.ID, &i.ProjectID, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCaseTags = `-- name: ListTestCaseTags :many
SELECT test_case_id, tag FROM test_case_tags WHERE test_case_id = ANY($1::bigint[])
ORDER BY test_case_id, tag
`

func (q *Queries) ListTestCaseTags(ctx context.Context, ids []int64) ([]TestCaseTag, error) {
	rows, err := q.db.Query(ctx, listTestCaseTags, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestCaseTag
	for rows.Next() {
		var i TestCaseTag
		if err := rows.Scan(&i.TestCaseID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCases = `-- name: ListTestCases :many
SELECT id, title, description, expected_result, status, automated, created_at, updated_at, deprecated_at, project_id, number, version FROM test_cases
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::bigint[] IS NULL OR project_id = ANY($2::bigint[]))
  AND ($3::text IS NULL OR EXISTS (SELECT 1 FROM test_case_tags t WHERE t.test_case_id = test_cases.id AND t.tag = $3::text))
  AND (coalesce(cardinality($4::text[]), 0) = 0 OR (
      SELECT count(*) FROM test_case_classifications c
      JOIN classification_dimensions d ON d.id = c.dimension_id
      JOIN classification_values v ON v.id = c.value_id
      WHERE c.test_case_id = test_cases.id AND d.key || ':' || v.key = ANY($4::text[])
  ) = cardinality($4::text[]))
  AND ($5::bigint IS NULL OR EXISTS (SELECT 1 FROM test_suite_cases m WHERE m.suite_id = $5::bigint AND m.test_case_id = test_cases.id))
  AND ($6::boolean IS NULL OR automated = $6::boolean)
  AND ($7::bigint IS NULL OR number = $7::bigint)
ORDER BY id DESC
LIMIT $9 OFFSET $8
`

type ListTestCasesParams struct {
	Status     pgtype.Text
	ProjectIds []int64
	Tag        pgtype.Text
	Classified []string
	SuiteID    pgtype.Int8
	Automated  pgtype.Bool
	Number     pgtype.Int8
	PageOffset int32
	PageLimit  int32
}

// classified holds distinct dimension:value pairs that must all hold (AND); a test case has one value per
// dimension, so two values of one dimension match nothing.
func (q *Queries) ListTestCases(ctx context.Context, arg ListTestCasesParams) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listTestCases,
		arg.Status,
		arg.ProjectIds,
		arg.Tag,
		arg.Classified,
		arg.SuiteID,
		arg.Automated,
		arg.Number,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestCase
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ExpectedResult,
			&i.Status,
			&i.Automated,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeprecatedAt,
			&i.ProjectID,
			&i.Number,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSteps = `-- name: ListTestSteps :many
SELECT id, test_case_id, position, action, expected_result, created_at, updated_at FROM test_steps
WHERE test_case_id = $1
ORDER BY position
LIMIT $3 OFFSET $2
`

type ListTestStepsParams struct {
	TestCaseID int64
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListTestSteps(ctx context.Context, arg ListTestStepsParams) ([]TestStep, error) {
	rows, err := q.db.Query(ctx, listTestSteps, arg.TestCaseID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestStep
	for rows.Next() {
		var i TestStep
		if err := rows.Scan(
			&i.ID,
			&i.TestCaseID,
			&i.Position,
			&i.Action,
			&i.ExpectedResult,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLinkParent = `-- name: LockLinkParent :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, $2::bigint))
`

type LockLinkParentParams struct {
	Kind string
	ID   int64
}

// Serializes replacements of one requirement's, issue's or static suite's test case set: concurrent replacements run
// one after the other, so the set always ends as one caller's list (never a union of two).
func (q *Queries) LockLinkParent(ctx context.Context, arg LockLinkParentParams) error {
	_, err := q.db.Exec(ctx, lockLinkParent, arg.Kind, arg.ID)
	return err
}

const lockTestCase = `-- name: LockTestCase :one
SELECT version FROM test_cases WHERE id = $1 FOR UPDATE
`

// Locks the test case (and its steps' order) until the transaction ends; returns its current version.
func (q *Queries) LockTestCase(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockTestCase, id)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const nextNativeIssueNumber = `-- name: NextNativeIssueNumber :one
UPDATE projects SET next_issue_number = next_issue_number + 1
WHERE id = $1
RETURNING (next_issue_number - 1)::bigint AS number
`

// Takes the next I-<n> of a project's native issues from its counter (the row lock serializes concurrent creations).
func (q *Queries) NextNativeIssueNumber(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, nextNativeIssueNumber, projectID)
	var number int64
	err := row.Scan(&number)
	return number, err
}

const nextNativeRequirementNumber = `-- name: NextNativeRequirementNumber :one
UPDATE projects SET next_requirement_number = next_requirement_number + 1
WHERE id = $1
RETURNING (next_requirement_number - 1)::bigint AS number
`

// Takes the next R-<n> of a project's native requirements from its counter (the row lock serializes concurrent
// creations; numbers are never reused).
func (q *Queries) NextNativeRequirementNumber(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, nextNativeRequirementNumber, projectID)
	var number int64
	err := row.Scan(&number)
	return number, err
}

const reactivateTestCase = `-- name: ReactivateTestCase :one
UPDATE test_cases SET
    status        = 'active',
    deprecated_at = NULL,
    updated_at    = CASE WHEN status = 'active' THEN updated_at ELSE now() END
WHERE id = $1
RETURNING id, title, description, expected_result, status, automated, created_at, updated_at, deprecated_at, project_id, number, version
`

func (q *Queries) ReactivateTestCase(ctx context.Context, id int64) (TestCase, error) {
	row := q.db.QueryRow(ctx, reactivateTestCase, id)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ExpectedResult,
		&i.Status,
		&i.Automated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeprecatedAt,
		&i.ProjectID,
		&i.Number,
		&i.Version,
	)
	return i, err
}

const setTestCaseClassification = `-- name: SetTestCaseClassification :exec
INSERT INTO test_case_classifications (test_case_id, project_id, dimension_id, value_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (test_case_id, dimension_id) DO UPDATE SET value_id = EXCLUDED.value_id
WHERE test_case_classifications.value_id <> EXCLUDED.value_id
`

type SetTestCaseClassificationParams struct {
	TestCaseID  int64
	ProjectID   int64
	DimensionID int64
	ValueID     int64
}

// Sets the value of one dimension; unchanged when it already has that value (so the version does not advance).
func (q *Queries) SetTestCaseClassification(ctx context.Context, arg SetTestCaseClassificationParams) error {
	_, err := q.db.Exec(ctx, setTestCaseClassification,
		arg.TestCaseID,
		arg.ProjectID,
		arg.DimensionID,
		arg.ValueID,
	)
	return err
}

const setTestStepPosition = `-- name: SetTestStepPosition :exec
UPDATE test_steps SET position = $1, updated_at = now()
WHERE test_case_id = $2 AND id = $3
`

type SetTestStepPositionParams struct {
	Position   int32
	TestCaseID int64
	ID         int64
}

func (q *Queries) SetTestStepPosition(ctx context.Context, arg SetTestStepPositionParams) error {
	_, err := q.db.Exec(ctx, setTestStepPosition, arg.Position, arg.TestCaseID, arg.ID)
	return err
}

const shiftTestStepsDown = `-- name: ShiftTestStepsDown :exec
UPDATE test_steps SET position = position + 1
WHERE test_case_id = $1 AND position >= $2
`

type ShiftTestStepsDownParams struct {
	TestCaseID   int64
	FromPosition int32
}

func (q *Queries) ShiftTestStepsDown(ctx context.Context, arg ShiftTestStepsDownParams) error {
	_, err := q.db.Exec(ctx, shiftTestStepsDown, arg.TestCaseID, arg.FromPosition)
	return err
}

const updateDimension = `-- name: UpdateDimension :one
UPDATE classification_dimensions SET
    name        = coalesce($1, name),
    archived_at = CASE WHEN $2::boolean IS NULL THEN archived_at
                       WHEN $2::boolean THEN coalesce(archived_at, now())
                       ELSE NULL END
WHERE project_id = $3 AND key = $4
RETURNING id, project_id, key, name, built_in, archived_at, created_at
`

type UpdateDimensionParams struct {
	Name      pgtype.Text
	Archived  pgtype.Bool
	ProjectID int64
	Key       string
}

func (q *Queries) UpdateDimension(ctx context.Context, arg UpdateDimensionParams) (ClassificationDimension, error) {
	row := q.db.QueryRow(ctx, updateDimension,
		arg.Name,
		arg.Archived,
		arg.ProjectID,
		arg.Key,
	)
	var i ClassificationDimension
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.BuiltIn,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateDimensionValue = `-- name: UpdateDimensionValue :one
UPDATE classification_values SET
    name        = coalesce($1, name),
    archived_at = CASE WHEN $2::boolean IS NULL THEN archived_at
                       WHEN $2::boolean THEN coalesce(archived_at, now())
                       ELSE NULL END
WHERE dimension_id = $3 AND key = $4
RETURNING id, dimension_id, key, name, position, archived_at, created_at
`

type UpdateDimensionValueParams struct {
	Name        pgtype.Text
	Archived    pgtype.Bool
	DimensionID int64
	Key         string
}

func (q *Queries) UpdateDimensionValue(ctx context.Context, arg UpdateDimensionValueParams) (ClassificationValue, error) {
	row := q.db.QueryRow(ctx, updateDimensionValue,
		arg.Name,
		arg.Archived,
		arg.DimensionID,
		arg.Key,
	)
	var i ClassificationValue
	err := row.Scan(
		&i.ID,
		&i.DimensionID,
		&i.Key,
		&i.Name,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateIssue = `-- name: UpdateIssue :one
UPDATE issues SET
    title           = coalesce($1, title),
    description     = coalesce($2, description),
    url             = coalesce($3, url),
    provider_status = coalesce($4, provider_status),
    state           = coalesce($5, state),
    closed_at       = CASE WHEN coalesce($5, state) = 'closed' THEN coalesce(closed_at, now()) END,
    updated_at      = now()
WHERE project_id = $6 AND id = $7
RETURNING id
`

type UpdateIssueParams struct {
	Title          pgtype.Text
	Description    pgtype.Text
	Url            pgtype.Text
	ProviderStatus pgtype.Text
	State          pgtype.Text
	ProjectID      int64
	ID             int64
}

func (q *Queries) UpdateIssue(ctx context.Context, arg UpdateIssueParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateIssue,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.ProviderStatus,
		arg.State,
		arg.ProjectID,
		arg.ID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
    name        = coalesce($1, name),
    description = coalesce($2, description),
    updated_at  = now()
WHERE key = $3
RETURNING id, key, name, description, next_number, created_at, updated_at, next_requirement_number, next_issue_number
`

type UpdateProjectParams struct {
	Name        pgtype.Text
	Description pgtype.Text
	Key         string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.Name, arg.Description, arg.Key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.NextNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextRequirementNumber,
		&i.NextIssueNumber,
	)
	return i, err
}

const updateRequirement = `-- name: UpdateRequirement :one
UPDATE requirements SET
    title           = coalesce($1, title),
    description     = coalesce($2, description),
    url             = coalesce($3, url),
    provider_status = coalesce($4, provider_status),
    archived_at     = CASE WHEN $5::boolean IS NULL THEN archived_at
                           WHEN $5::boolean THEN coalesce(archived_at, now())
                           ELSE NULL END,
    updated_at      = now()
WHERE project_id = $6 AND id = $7
RETURNING id
`

type UpdateRequirementParams struct {
	Title          pgtype.Text
	Description    pgtype.Text
	Url            pgtype.Text
	ProviderStatus pgtype.Text
	Archived       pgtype.Bool
	ProjectID      int64
	ID             int64
}

func (q *Queries) UpdateRequirement(ctx context.Context, arg UpdateRequirementParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateRequirement,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.ProviderStatus,
		arg.Archived,
		arg.ProjectID,
		arg.ID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateSuite = `-- name: UpdateSuite :one
UPDATE test_suites SET
    name             = coalesce($1, name),
    description      = coalesce($2, description),
    query_tag        = CASE WHEN $3::boolean THEN $4 ELSE query_tag END,
    query_classified = CASE WHEN $3::boolean THEN $5::text[] ELSE query_classified END,
    archived_at      = CASE WHEN $6::boolean IS NULL THEN archived_at
                            WHEN $6::boolean THEN coalesce(archived_at, now())
                            ELSE NULL END,
    updated_at       = now()
WHERE project_id = $7 AND key = $8
RETURNING id
`

type UpdateSuiteParams struct {
	Name            pgtype.Text
	Description     pgtype.Text
	SetQuery        bool
	QueryTag        pgtype.Text
	QueryClassified []string
	Archived        pgtype.Bool
	ProjectID       int64
	Key             string
}

func (q *Queries) UpdateSuite(ctx context.Context, arg UpdateSuiteParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateSuite,
		arg.Name,
		arg.Description,
		arg.SetQuery,
		arg.QueryTag,
		arg.QueryClassified,
		arg.Archived,
		arg.ProjectID,
		arg.Key,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateTestCase = `-- name: UpdateTestCase :one
UPDATE test_cases SET
    title           = coalesce($1, title),
    description     = coalesce($2, description),
    expected_result = coalesce($3, expected_result),
    automated       = coalesce($4, automated),
    updated_at      = now()
WHERE id = $5
RETURNING id, title, description, expected_result, status, automated, created_at, updated_at, deprecated_at, project_id, number, version
`

type UpdateTestCaseParams struct {
	Title          pgtype.Text
	Description    pgtype.Text
	ExpectedResult pgtype.Text
	Automated      pgtype.Bool
	ID             int64
}

func (q *Queries) UpdateTestCase(ctx context.Context, arg UpdateTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, updateTestCase,
		arg.Title,
		arg.Description,
		arg.ExpectedResult,
		arg.Automated,
		arg.ID,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ExpectedResult,
		&i.Status,
		&i.Automated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeprecatedAt,
		&i.ProjectID,
		&i.Number,
		&i.Version,
	)
	return i, err
}

const updateTestStep = `-- name: UpdateTestStep :one
UPDATE test_steps SET
    action          = coalesce($1, action),
    expected_result = coalesce($2, expected_result),
    updated_at      = now()
WHERE test_case_id = $3 AND id = $4
RETURNING id, test_case_id, position, action, expected_result, created_at, updated_at
`

type UpdateTestStepParams struct {
	Action         pgtype.Text
	ExpectedResult pgtype.Text
	TestCaseID     int64
	ID             int64
}

func (q *Queries) UpdateTestStep(ctx context.Context, arg UpdateTestStepParams) (TestStep, error) {
	row := q.db.QueryRow(ctx, updateTestStep,
		arg.Action,
		arg.ExpectedResult,
		arg.TestCaseID,
		arg.ID,
	)
	var i TestStep
	err := row.Scan(
		&i.ID,
		&i.TestCaseID,
		&i.Position,
		&i.Action,
		&i.ExpectedResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIssue = `-- name: UpsertIssue :one
INSERT INTO issues (project_id, provider, external_id, title, description, url, state, provider_status, closed_at, last_synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
    CASE WHEN $7::text = 'closed' THEN now() END, $9)
ON CONFLICT (project_id, provider, external_id) DO UPDATE SET
    title = EXCLUDED.title, description = EXCLUDED.description, url = EXCLUDED.url, state = EXCLUDED.state,
    provider_status = EXCLUDED.provider_status, last_synced_at = EXCLUDED.last_synced_at,
    closed_at = CASE WHEN EXCLUDED.state = 'closed' THEN coalesce(issues.closed_at, now()) END, updated_at = now()
WHERE $10::boolean
RETURNING id, (xmax = 0)::boolean AS created
`

type UpsertIssueParams struct {
	ProjectID      int64
	Provider       string
	ExternalID     string
	Title          string
	Description    string
	Url            string
	State          string
	ProviderStatus string
	LastSyncedAt   pgtype.Timestamptz
	Sync           bool
}

type UpsertIssueRow struct {
	ID      int64
	Created bool
}

// Creates an issue, or (when sync is true) updates the mirrored one with the same provider and external id; closed_at
// follows the state (kept while it stays closed).
func (q *Queries) UpsertIssue(ctx context.Context, arg UpsertIssueParams) (UpsertIssueRow, error) {
	row := q.db.QueryRow(ctx, upsertIssue,
		arg.ProjectID,
		arg.Provider,
		arg.ExternalID,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.State,
		arg.ProviderStatus,
		arg.LastSyncedAt,
		arg.Sync,
	)
	var i UpsertIssueRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}

const upsertRequirement = `-- name: UpsertRequirement :one
INSERT INTO requirements (project_id, provider, external_id, title, description, url, provider_status, last_synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (project_id, provider, external_id) DO UPDATE SET
    title = EXCLUDED.title, description = EXCLUDED.description, url = EXCLUDED.url,
    provider_status = EXCLUDED.provider_status, last_synced_at = EXCLUDED.last_synced_at, updated_at = now()
WHERE $9::boolean
RETURNING id, (xmax = 0)::boolean AS created
`

type UpsertRequirementParams struct {
	ProjectID      int64
	Provider       string
	ExternalID     string
	Title          string
	Description    string
	Url            string
	ProviderStatus string
	LastSyncedAt   pgtype.Timestamptz
	Sync           bool
}

type UpsertRequirementRow struct {
	ID      int64
	Created bool
}

// Creates a requirement, or (when sync is true) updates the mirrored one with the same provider and external id.
// xmax = 0 tells a fresh insert from an update.
func (q *Queries) UpsertRequirement(ctx context.Context, arg UpsertRequirementParams) (UpsertRequirementRow, error) {
	row := q.db.QueryRow(ctx, upsertRequirement,
		arg.ProjectID,
		arg.Provider,
		arg.ExternalID,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.ProviderStatus,
		arg.LastSyncedAt,
		arg.Sync,
	)
	var i UpsertRequirementRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}
