// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalogdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ClassificationDimension struct {
	ID         int64
	ProjectID  int64
	Key        string
	Name       string
	BuiltIn    bool
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type ClassificationValue struct {
	ID          int64
	DimensionID int64
	Key         string
	Name        string
	Position    int32
	ArchivedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Project struct {
	ID                    int64
	Key                   string
	Name                  string
	Description           string
	NextNumber            int64
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	NextRequirementNumber int64
}

type Requirement struct {
	ID             int64
	ProjectID      int64
	Provider       string
	ExternalID     string
	Title          string
	Description    string
	Url            string
	ProviderStatus string
	ArchivedAt     pgtype.Timestamptz
	LastSyncedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RequirementTestCase struct {
	RequirementID int64
	ProjectID     int64
	TestCaseID    int64
}

type TestCase struct {
	ID             int64
	Title          string
	Description    string
	ExpectedResult string
	Status         string
	Automated      bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeprecatedAt   pgtype.Timestamptz
	ProjectID      int64
	Number         int64
	Version        int64
}

type TestCaseClassification struct {
	TestCaseID  int64
	ProjectID   int64
	DimensionID int64
	ValueID     int64
}

type TestCaseTag struct {
	TestCaseID int64
	Tag        string
}

type TestStep struct {
	ID             int64
	TestCaseID     int64
	Position       int32
	Action         string
	ExpectedResult string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type TestSuite struct {
	ID              int64
	ProjectID       int64
	Key             string
	Name            string
	Description     string
	Kind            string
	QueryTag        pgtype.Text
	QueryClassified []string
	ArchivedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type TestSuiteCase struct {
	SuiteID    int64
	ProjectID  int64
	TestCaseID int64
}
