// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalogdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID          int64
	Key         string
	Name        string
	Description string
	NextNumber  int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type TestCase struct {
	ID             int64
	Title          string
	Description    string
	ExpectedResult string
	Status         string
	Automated      bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeprecatedAt   pgtype.Timestamptz
	ProjectID      int64
	Number         int64
	Version        int64
}

type TestStep struct {
	ID             int64
	TestCaseID     int64
	Position       int32
	Action         string
	ExpectedResult string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
