// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package catalogdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TestCase struct {
	ID             int64
	Title          string
	Description    string
	ExpectedResult string
	Status         string
	Automated      bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeprecatedAt   pgtype.Timestamptz
}

type TestStep struct {
	ID             int64
	TestCaseID     int64
	Position       int32
	Action         string
	ExpectedResult string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
