// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package catalogdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CloseTestStepGap(ctx context.Context, arg CloseTestStepGapParams) error
	CountTestCases(ctx context.Context, status pgtype.Text) (int64, error)
	CountTestSteps(ctx context.Context, testCaseID int64) (int64, error)
	CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error)
	CreateTestStep(ctx context.Context, arg CreateTestStepParams) (TestStep, error)
	DeleteTestStep(ctx context.Context, arg DeleteTestStepParams) (int32, error)
	DeprecateTestCase(ctx context.Context, id int64) (TestCase, error)
	GetTestCase(ctx context.Context, id int64) (TestCase, error)
	ListAllTestSteps(ctx context.Context, testCaseID int64) ([]TestStep, error)
	ListExpectedUniverse(ctx context.Context) ([]int64, error)
	ListTestCaseStatuses(ctx context.Context, ids []int64) ([]ListTestCaseStatusesRow, error)
	ListTestCases(ctx context.Context, arg ListTestCasesParams) ([]TestCase, error)
	ListTestSteps(ctx context.Context, arg ListTestStepsParams) ([]TestStep, error)
	LockTestCase(ctx context.Context, id int64) (int64, error)
	SetTestStepPosition(ctx context.Context, arg SetTestStepPositionParams) error
	ShiftTestStepsDown(ctx context.Context, arg ShiftTestStepsDownParams) error
	UpdateTestCase(ctx context.Context, arg UpdateTestCaseParams) (TestCase, error)
	UpdateTestStep(ctx context.Context, arg UpdateTestStepParams) (TestStep, error)
}

var _ Querier = (*Queries)(nil)
