// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package executiondb

import (
	"context"
)

// iteratorForInsertParseErrors implements pgx.CopyFromSource.
type iteratorForInsertParseErrors struct {
	rows                 []InsertParseErrorsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertParseErrors) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertParseErrors) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TestRunID,
		r.rows[0].CaseIndex,
		r.rows[0].TestName,
		r.rows[0].Message,
		r.rows[0].Persisted,
		r.rows[0].Severity,
	}, nil
}

func (r iteratorForInsertParseErrors) Err() error {
	return nil
}

func (q *Queries) InsertParseErrors(ctx context.Context, arg []InsertParseErrorsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"test_run_parse_errors"}, []string{"test_run_id", "case_index", "test_name", "message", "persisted", "severity"}, &iteratorForInsertParseErrors{rows: arg})
}

// iteratorForInsertTestResults implements pgx.CopyFromSource.
type iteratorForInsertTestResults struct {
	rows                 []InsertTestResultsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTestResults) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTestResults) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TestRunID,
		r.rows[0].TestCaseID,
		r.rows[0].RequestedTestCaseID,
		r.rows[0].Correlation,
		r.rows[0].TestName,
		r.rows[0].ClassName,
		r.rows[0].SuiteName,
		r.rows[0].Status,
		r.rows[0].DurationMs,
		r.rows[0].ErrorMessage,
		r.rows[0].ErrorDetails,
	}, nil
}

func (r iteratorForInsertTestResults) Err() error {
	return nil
}

func (q *Queries) InsertTestResults(ctx context.Context, arg []InsertTestResultsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"test_results"}, []string{"test_run_id", "test_case_id", "requested_test_case_id", "correlation", "test_name", "class_name", "suite_name", "status", "duration_ms", "error_message", "error_details"}, &iteratorForInsertTestResults{rows: arg})
}
