// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: execution.sql

package executiondb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeLiveRun = `-- name: CompleteLiveRun :exec
UPDATE test_runs SET status = $1, completed_at = now(), report_sha256 = $2
WHERE id = $3 AND mode = 'live' AND status = 'running'
`

type CompleteLiveRunParams struct {
	Status       string
	ReportSha256 string
	ID           int64
}

// The final report completes a running live run: its execution status, completion time and report digest.
func (q *Queries) CompleteLiveRun(ctx context.Context, arg CompleteLiveRunParams) error {
	_, err := q.db.Exec(ctx, completeLiveRun, arg.Status, arg.ReportSha256, arg.ID)
	return err
}

const countAmendments = `-- name: CountAmendments :one
SELECT count(*) FROM test_run_amendments WHERE test_run_id = $1
`

func (q *Queries) CountAmendments(ctx context.Context, testRunID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAmendments, testRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countParseErrors = `-- name: CountParseErrors :one
SELECT count(*) FROM test_run_parse_errors WHERE test_run_id = $1
`

func (q *Queries) CountParseErrors(ctx context.Context, testRunID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countParseErrors, testRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResultsForTestCase = `-- name: CountResultsForTestCase :one
SELECT count(*) FROM test_results WHERE test_case_id = $1
`

func (q *Queries) CountResultsForTestCase(ctx context.Context, testCaseID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countResultsForTestCase, testCaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunEvents = `-- name: CountRunEvents :one
SELECT count(*)::int FROM test_run_events WHERE test_run_id = $1
`

func (q *Queries) CountRunEvents(ctx context.Context, testRunID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countRunEvents, testRunID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countRunResults = `-- name: CountRunResults :one
SELECT count(*) FROM test_results
WHERE test_run_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR correlation = $3::text)
  AND ($4::int IS NULL OR shard = $4::int)
`

type CountRunResultsParams struct {
	TestRunID   int64
	Status      pgtype.Text
	Correlation pgtype.Text
	Shard       pgtype.Int4
}

func (q *Queries) CountRunResults(ctx context.Context, arg CountRunResultsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRunResults,
		arg.TestRunID,
		arg.Status,
		arg.Correlation,
		arg.Shard,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTestRuns = `-- name: CountTestRuns :one
SELECT count(*) FROM test_runs
WHERE ($1::bigint[] IS NULL OR project_id = ANY($1::bigint[]))
  AND ($2::text IS NULL OR suite_key = $2::text)
`

type CountTestRunsParams struct {
	ProjectIds []int64
	SuiteKey   pgtype.Text
}

func (q *Queries) CountTestRuns(ctx context.Context, arg CountTestRunsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTestRuns, arg.ProjectIds, arg.SuiteKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishShardedRun = `-- name: FinishShardedRun :exec
UPDATE test_runs SET status = $1, completed_at = now() WHERE id = $2 AND mode = 'sharded' AND status = 'running'
`

type FinishShardedRunParams struct {
	Status string
	ID     int64
}

// Every shard arrived (or CI finalized the run): its execution status and completion time.
func (q *Queries) FinishShardedRun(ctx context.Context, arg FinishShardedRunParams) error {
	_, err := q.db.Exec(ctx, finishShardedRun, arg.Status, arg.ID)
	return err
}

const finishTestRun = `-- name: FinishTestRun :exec
UPDATE test_runs SET status = $1, completed_at = now() WHERE id = $2 AND status = 'running'
`

type FinishTestRunParams struct {
	Status string
	ID     int64
}

func (q *Queries) FinishTestRun(ctx context.Context, arg FinishTestRunParams) error {
	_, err := q.db.Exec(ctx, finishTestRun, arg.Status, arg.ID)
	return err
}

const getRunProject = `-- name: GetRunProject :one
SELECT project_id FROM test_runs WHERE id = $1
`

// The project of a run: what authorizing a request on it needs, without the run's counts and outcome.
func (q *Queries) GetRunProject(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getRunProject, id)
	var project_id int64
	err := row.Scan(&project_id)
	return project_id, err
}

const getTestRun = `-- name: GetTestRun :one
SELECT r.id, r.external_run_id, r.provider, r.provider_run_id, r.run_attempt, r.pipeline, r.branch, r.commit_sha, r.status, r.created_at, r.started_at, r.completed_at, r.report_sha256, r.project_id, r.suite_key, r.suite_name, r.mode, r.started_by, r.shard_total,
    (SELECT count(*) FROM test_run_expected_cases e WHERE e.test_run_id = r.id)::int AS expected_count,
    (SELECT count(*) FROM test_results t WHERE t.test_run_id = r.id)::int AS result_count,
    (SELECT count(*) FROM test_run_amendments a WHERE a.test_run_id = r.id)::int AS amendment_count,
    (SELECT coalesce(array_agg(s.shard ORDER BY s.shard), '{}') FROM test_run_shards s WHERE s.test_run_id = r.id)::int[] AS shards_received
FROM test_runs r WHERE r.id = $1
`

type GetTestRunRow struct {
	TestRun        TestRun
	ExpectedCount  int32
	ResultCount    int32
	AmendmentCount int32
	ShardsReceived []int32
}

func (q *Queries) GetTestRun(ctx context.Context, id int64) (GetTestRunRow, error) {
	row := q.db.QueryRow(ctx, getTestRun, id)
	var i GetTestRunRow
	err := row.Scan(
		&i.TestRun.ID,
		&i.TestRun.ExternalRunID,
		&i.TestRun.Provider,
		&i.TestRun.ProviderRunID,
		&i.TestRun.RunAttempt,
		&i.TestRun.Pipeline,
		&i.TestRun.Branch,
		&i.TestRun.CommitSha,
		&i.TestRun.Status,
		&i.TestRun.CreatedAt,
		&i.TestRun.StartedAt,
		&i.TestRun.CompletedAt,
		&i.TestRun.ReportSha256,
		&i.TestRun.ProjectID,
		&i.TestRun.SuiteKey,
		&i.TestRun.SuiteName,
		&i.TestRun.Mode,
		&i.TestRun.StartedBy,
		&i.TestRun.ShardTotal,
		&i.ExpectedCount,
		&i.ResultCount,
		&i.AmendmentCount,
		&i.ShardsReceived,
	)
	return i, err
}

const getTestRunIDByExternalID = `-- name: GetTestRunIDByExternalID :one
SELECT id FROM test_runs WHERE project_id = $1 AND external_run_id = $2
`

type GetTestRunIDByExternalIDParams struct {
	ProjectID     int64
	ExternalRunID string
}

func (q *Queries) GetTestRunIDByExternalID(ctx context.Context, arg GetTestRunIDByExternalIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTestRunIDByExternalID, arg.ProjectID, arg.ExternalRunID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAmendment = `-- name: InsertAmendment :one
INSERT INTO test_run_amendments (test_run_id, test_case_id, amended_by, amended_by_username, reason)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (test_run_id, test_case_id) DO NOTHING
RETURNING id, test_run_id, test_case_id, amended_by, amended_by_username, reason, created_at
`

type InsertAmendmentParams struct {
	TestRunID         int64
	TestCaseID        int64
	AmendedBy         int64
	AmendedByUsername string
	Reason            string
}

func (q *Queries) InsertAmendment(ctx context.Context, arg InsertAmendmentParams) (TestRunAmendment, error) {
	row := q.db.QueryRow(ctx, insertAmendment,
		arg.TestRunID,
		arg.TestCaseID,
		arg.AmendedBy,
		arg.AmendedByUsername,
		arg.Reason,
	)
	var i TestRunAmendment
	err := row.Scan(
		&i.ID,
		&i.TestRunID,
		&i.TestCaseID,
		&i.AmendedBy,
		&i.AmendedByUsername,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertExpectedCases = `-- name: InsertExpectedCases :exec
INSERT INTO test_run_expected_cases (test_run_id, test_case_id)
SELECT $1, unnest($2::bigint[])
`

type InsertExpectedCasesParams struct {
	TestRunID   int64
	TestCaseIds []int64
}

func (q *Queries) InsertExpectedCases(ctx context.Context, arg InsertExpectedCasesParams) error {
	_, err := q.db.Exec(ctx, insertExpectedCases, arg.TestRunID, arg.TestCaseIds)
	return err
}

const insertManualResult = `-- name: InsertManualResult :one
INSERT INTO test_results (test_run_id, test_case_id, requested_test_case_id, correlation, test_name, class_name, suite_name, status, duration_ms, error_message, error_details, attempt, recorded_by, failed_step)
SELECT $1, $2, $3, 'valid', $4, $5, '', $6, $7, $8, '',
    coalesce(max(x.attempt), 0) + 1, $9, $10
FROM test_results x WHERE x.test_run_id = $1 AND x.class_name = $5 AND x.test_name = $4
  AND x.suite_name = ''
HAVING coalesce(max(x.attempt), 0) < $11::int
RETURNING id, test_run_id, test_case_id, requested_test_case_id, correlation, test_name, class_name, suite_name, status, duration_ms, error_message, error_details, created_at, attempt, recorded_by, failed_step, shard
`

type InsertManualResultParams struct {
	TestRunID           int64
	TestCaseID          pgtype.Int8
	RequestedTestCaseID pgtype.Text
	TestName            string
	ClassName           string
	Status              string
	DurationMs          pgtype.Int8
	ErrorMessage        string
	RecordedBy          pgtype.Text
	FailedStep          pgtype.Int4
	MaxAttempts         int32
}

// One recorded result of a running run; a re-test of the same test is its next attempt.
// Nothing is inserted past the last allowed attempt (the column's CHECK would fail the transaction instead).
func (q *Queries) InsertManualResult(ctx context.Context, arg InsertManualResultParams) (TestResult, error) {
	row := q.db.QueryRow(ctx, insertManualResult,
		arg.TestRunID,
		arg.TestCaseID,
		arg.RequestedTestCaseID,
		arg.TestName,
		arg.ClassName,
		arg.Status,
		arg.DurationMs,
		arg.ErrorMessage,
		arg.RecordedBy,
		arg.FailedStep,
		arg.MaxAttempts,
	)
	var i TestResult
	err := row.Scan(
		&i.ID,
		&i.TestRunID,
		&i.TestCaseID,
		&i.RequestedTestCaseID,
		&i.Correlation,
		&i.TestName,
		&i.ClassName,
		&i.SuiteName,
		&i.Status,
		&i.DurationMs,
		&i.ErrorMessage,
		&i.ErrorDetails,
		&i.CreatedAt,
		&i.Attempt,
		&i.RecordedBy,
		&i.FailedStep,
		&i.Shard,
	)
	return i, err
}

type InsertParseErrorsParams struct {
	TestRunID int64
	CaseIndex int32
	TestName  string
	Message   string
	Persisted bool
	Severity  string
	Shard     pgtype.Int4
}

const insertRunEvent = `-- name: InsertRunEvent :execrows
INSERT INTO test_run_events (test_run_id, event_id, sequence, event_type, test_name, requested_test_case_id, test_case_id, status, occurred_at, attempt)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (test_run_id, event_id) DO NOTHING
`

type InsertRunEventParams struct {
	TestRunID           int64
	EventID             string
	Sequence            int64
	EventType           string
	TestName            string
	RequestedTestCaseID pgtype.Text
	TestCaseID          pgtype.Int8
	Status              pgtype.Text
	OccurredAt          pgtype.Timestamptz
	Attempt             int32
}

// Appends one live event; an event id already received for the run is a duplicate delivery and is skipped (0 rows).
func (q *Queries) InsertRunEvent(ctx context.Context, arg InsertRunEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRunEvent,
		arg.TestRunID,
		arg.EventID,
		arg.Sequence,
		arg.EventType,
		arg.TestName,
		arg.RequestedTestCaseID,
		arg.TestCaseID,
		arg.Status,
		arg.OccurredAt,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRunShard = `-- name: InsertRunShard :execrows
INSERT INTO test_run_shards (test_run_id, shard, report_sha256, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (test_run_id, shard) DO NOTHING
`

type InsertRunShardParams struct {
	TestRunID    int64
	Shard        int32
	ReportSha256 string
	Status       string
}

// Records a shard of a running sharded run; a shard already received is a replay (0 rows).
func (q *Queries) InsertRunShard(ctx context.Context, arg InsertRunShardParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRunShard,
		arg.TestRunID,
		arg.Shard,
		arg.ReportSha256,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

type InsertTestResultsParams struct {
	TestRunID           int64
	TestCaseID          pgtype.Int8
	RequestedTestCaseID pgtype.Text
	Correlation         string
	TestName            string
	ClassName           string
	SuiteName           string
	Status              string
	DurationMs          pgtype.Int8
	ErrorMessage        string
	ErrorDetails        string
	Attempt             int32
	Shard               pgtype.Int4
}

const insertTestRun = `-- name: InsertTestRun :one
INSERT INTO test_runs (project_id, external_run_id, provider, provider_run_id, run_attempt, pipeline, branch, commit_sha, status, started_at, completed_at, report_sha256, suite_key, suite_name, mode, started_by, shard_total)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT (project_id, external_run_id) DO NOTHING
RETURNING id
`

type InsertTestRunParams struct {
	ProjectID     int64
	ExternalRunID string
	Provider      string
	ProviderRunID string
	RunAttempt    int32
	Pipeline      string
	Branch        string
	CommitSha     string
	Status        string
	StartedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
	ReportSha256  string
	SuiteKey      pgtype.Text
	SuiteName     pgtype.Text
	Mode          string
	StartedBy     pgtype.Text
	ShardTotal    pgtype.Int4
}

func (q *Queries) InsertTestRun(ctx context.Context, arg InsertTestRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertTestRun,
		arg.ProjectID,
		arg.ExternalRunID,
		arg.Provider,
		arg.ProviderRunID,
		arg.RunAttempt,
		arg.Pipeline,
		arg.Branch,
		arg.CommitSha,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ReportSha256,
		arg.SuiteKey,
		arg.SuiteName,
		arg.Mode,
		arg.StartedBy,
		arg.ShardTotal,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const isInUniverse = `-- name: IsInUniverse :one
SELECT EXISTS (SELECT 1 FROM test_run_expected_cases e WHERE e.test_run_id = $1::bigint AND e.test_case_id = $2::bigint)
    OR EXISTS (SELECT 1 FROM test_run_amendments a WHERE a.test_run_id = $1::bigint AND a.test_case_id = $2::bigint)
`

type IsInUniverseParams struct {
	RunID  int64
	CaseID int64
}

// Whether a test case is in a run's universe: its snapshot or its amendments.
func (q *Queries) IsInUniverse(ctx context.Context, arg IsInUniverseParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isInUniverse, arg.RunID, arg.CaseID)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listAmendments = `-- name: ListAmendments :many
SELECT id, test_run_id, test_case_id, amended_by, amended_by_username, reason, created_at FROM test_run_amendments WHERE test_run_id = $1 ORDER BY id
LIMIT $3 OFFSET $2
`

type ListAmendmentsParams struct {
	TestRunID  int64
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListAmendments(ctx context.Context, arg ListAmendmentsParams) ([]TestRunAmendment, error) {
	rows, err := q.db.Query(ctx, listAmendments, arg.TestRunID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestRunAmendment
	for rows.Next() {
		var i TestRunAmendment
		if err := rows.Scan(
			&i.ID,
			&i.TestRunID,
			&i.TestCaseID,
			&i.AmendedBy,
			&i.AmendedByUsername,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiagnosticResults = `-- name: ListDiagnosticResults :many
SELECT test_name, correlation, requested_test_case_id, shard FROM test_results
WHERE test_run_id = $1 AND correlation <> 'valid'
ORDER BY id
`

type ListDiagnosticResultsRow struct {
	TestName            string
	Correlation         string
	RequestedTestCaseID pgtype.Text
	Shard               pgtype.Int4
}

func (q *Queries) ListDiagnosticResults(ctx context.Context, testRunID int64) ([]ListDiagnosticResultsRow, error) {
	rows, err := q.db.Query(ctx, listDiagnosticResults, testRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiagnosticResultsRow
	for rows.Next() {
		var i ListDiagnosticResultsRow
		if err := rows.Scan(
			&i.TestName,
			&i.Correlation,
			&i.RequestedTestCaseID,
			&i.Shard,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlakyCounts = `-- name: ListFlakyCounts :many
WITH runs AS (
    SELECT id FROM test_runs WHERE project_id = $2 ORDER BY id DESC LIMIT $3
), attempts AS (
    SELECT t.test_case_id, t.test_run_id, t.suite_name, t.class_name, t.test_name, t.status, t.attempt,
        max(t.attempt) OVER (PARTITION BY t.test_run_id, t.test_case_id, t.suite_name, t.class_name, t.test_name) AS last_attempt
    FROM test_results t
    WHERE t.test_run_id IN (SELECT id FROM runs) AND t.correlation = 'valid'
), tests AS (
    SELECT a.test_case_id, a.test_run_id, a.class_name,
        bool_and(a.status = 'passed') FILTER (WHERE a.attempt = a.last_attempt) AS last_passed,
        coalesce(bool_or(a.status IN ('failed', 'error')) FILTER (WHERE a.attempt < a.last_attempt), false) AS earlier_failure,
        coalesce(bool_or(a.status IN ('failed', 'error')) FILTER (WHERE a.attempt = a.last_attempt), false) AS last_failure
    FROM attempts a
    GROUP BY a.test_case_id, a.test_run_id, a.suite_name, a.class_name, a.test_name
), flaky AS (
    SELECT x.test_case_id, x.test_run_id FROM tests x
    GROUP BY x.test_case_id, x.test_run_id
    HAVING bool_or(x.last_passed AND x.earlier_failure AND x.class_name <> 'provenly-manual') AND NOT bool_or(x.last_failure)
)
SELECT f.test_case_id::bigint AS test_case_id, count(*)::int AS flaky_runs
FROM flaky f
GROUP BY f.test_case_id
ORDER BY flaky_runs DESC, f.test_case_id
LIMIT $1
`

type ListFlakyCountsParams struct {
	MaxItems   int32
	ProjectID  int64
	WindowRuns int32
}

type ListFlakyCountsRow struct {
	TestCaseID int64
	FlakyRuns  int32
}

// In a project's latest runs, how many runs each test case was flaky in: every result of one of its tests' last
// attempt passed after a failed or errored earlier attempt, and the test case did not fail or error in that run (a
// variant that failed for good is a failure, not flakiness). Manual re-tests are never flaky.
func (q *Queries) ListFlakyCounts(ctx context.Context, arg ListFlakyCountsParams) ([]ListFlakyCountsRow, error) {
	rows, err := q.db.Query(ctx, listFlakyCounts, arg.MaxItems, arg.ProjectID, arg.WindowRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlakyCountsRow
	for rows.Next() {
		var i ListFlakyCountsRow
		if err := rows.Scan(&i.TestCaseID, &i.FlakyRuns); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLastExecuted = `-- name: ListLastExecuted :many
SELECT t.test_case_id::bigint AS test_case_id, max(r.created_at)::timestamptz AS last_executed_at
FROM test_results t JOIN test_runs r ON r.id = t.test_run_id
WHERE t.correlation = 'valid' AND t.test_case_id = ANY($1::bigint[])
GROUP BY t.test_case_id
`

type ListLastExecutedRow struct {
	TestCaseID     int64
	LastExecutedAt pgtype.Timestamptz
}

// When each given test case last had a valid result (the creation time of its latest run with one).
func (q *Queries) ListLastExecuted(ctx context.Context, testCaseIds []int64) ([]ListLastExecutedRow, error) {
	rows, err := q.db.Query(ctx, listLastExecuted, testCaseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLastExecutedRow
	for rows.Next() {
		var i ListLastExecutedRow
		if err := rows.Scan(&i.TestCaseID, &i.LastExecutedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestConclusive = `-- name: ListLatestConclusive :many
SELECT c.id::bigint AS test_case_id, p.test_run_id, p.status::text AS status
FROM unnest($1::bigint[]) AS c(id)
CROSS JOIN LATERAL (
    SELECT r.test_run_id, s.status
    FROM (SELECT DISTINCT x.test_run_id FROM test_results x
          WHERE x.test_case_id = c.id AND x.correlation = 'valid' ORDER BY x.test_run_id DESC) r
    CROSS JOIN LATERAL (
        SELECT CASE WHEN bool_or(a.status = 'failed') THEN 'failed' WHEN bool_or(a.status = 'error') THEN 'error'
                    WHEN bool_or(a.status = 'skipped') THEN 'skipped' ELSE 'passed' END AS status
        FROM (SELECT t.status, t.attempt,
                     max(t.attempt) OVER (PARTITION BY t.suite_name, t.class_name, t.test_name) AS last_attempt
              FROM test_results t
              WHERE t.test_run_id = r.test_run_id AND t.test_case_id = c.id AND t.correlation = 'valid') a
        WHERE a.attempt = a.last_attempt
    ) s
    WHERE s.status <> 'skipped'
    ORDER BY r.test_run_id DESC
    LIMIT 1
) p
ORDER BY c.id
`

type ListLatestConclusiveRow struct {
	TestCaseID int64
	TestRunID  int64
	Status     string
}

// For each given test case, its latest run with a conclusive logical status (passed, failed or error; skipped runs are
// inconclusive) and that status. The logical status of a test case in a run is the highest attempt of each test
// (every result of it: repeated names without an attempt signal are variants), aggregated failed > error > skipped >
// passed, as in summaries.
// Runs are walked newest first per test case and the walk stops at the first conclusive one (index
// test_results_case_run_valid_idx), instead of aggregating every run of the test case's history.
func (q *Queries) ListLatestConclusive(ctx context.Context, testCaseIds []int64) ([]ListLatestConclusiveRow, error) {
	rows, err := q.db.Query(ctx, listLatestConclusive, testCaseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestConclusiveRow
	for rows.Next() {
		var i ListLatestConclusiveRow
		if err := rows.Scan(&i.TestCaseID, &i.TestRunID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestResults = `-- name: ListLatestResults :many
WITH latest AS (
    SELECT c.id, (SELECT x.test_run_id FROM test_results x WHERE x.test_case_id = c.id AND x.correlation = 'valid'
                  ORDER BY x.test_run_id DESC LIMIT 1) AS run_id
    FROM unnest($1::bigint[]) AS c(id)
)
SELECT t.test_case_id::bigint AS test_case_id, t.status, (t.suite_name || chr(31) || t.class_name || chr(31) || t.test_name)::text AS execution, t.attempt
FROM latest l
JOIN test_results t ON t.test_run_id = l.run_id AND t.test_case_id = l.id AND t.correlation = 'valid'
ORDER BY t.test_case_id, t.id
`

type ListLatestResultsRow struct {
	TestCaseID int64
	Status     string
	Execution  string
	Attempt    int32
}

// The valid results of each given test case in the latest run that has one for it (status, test and attempt), to
// read its latest status (requirement coverage).
// The latest run is found first, once per test case (index test_results_case_run_valid_idx), then only its results
// are read.
func (q *Queries) ListLatestResults(ctx context.Context, testCaseIds []int64) ([]ListLatestResultsRow, error) {
	rows, err := q.db.Query(ctx, listLatestResults, testCaseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestResultsRow
	for rows.Next() {
		var i ListLatestResultsRow
		if err := rows.Scan(
			&i.TestCaseID,
			&i.Status,
			&i.Execution,
			&i.Attempt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParseErrors = `-- name: ListParseErrors :many
SELECT case_index, test_name, message, persisted, severity, shard FROM test_run_parse_errors
WHERE test_run_id = $1
ORDER BY coalesce(shard, 0), case_index
LIMIT $3 OFFSET $2
`

type ListParseErrorsParams struct {
	TestRunID  int64
	PageOffset int32
	PageLimit  int32
}

type ListParseErrorsRow struct {
	CaseIndex int32
	TestName  string
	Message   string
	Persisted bool
	Severity  string
	Shard     pgtype.Int4
}

func (q *Queries) ListParseErrors(ctx context.Context, arg ListParseErrorsParams) ([]ListParseErrorsRow, error) {
	rows, err := q.db.Query(ctx, listParseErrors, arg.TestRunID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParseErrorsRow
	for rows.Next() {
		var i ListParseErrorsRow
		if err := rows.Scan(
			&i.CaseIndex,
			&i.TestName,
			&i.Message,
			&i.Persisted,
			&i.Severity,
			&i.Shard,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResultsForTestCase = `-- name: ListResultsForTestCase :many
WITH page AS (
    SELECT p.id FROM test_results p WHERE p.test_case_id = $1
    ORDER BY p.id DESC LIMIT $3 OFFSET $2
), counts AS (
    SELECT r.id,
        (SELECT count(*) FROM test_run_expected_cases e WHERE e.test_run_id = r.id)::int AS expected_count,
        (SELECT count(*) FROM test_results x WHERE x.test_run_id = r.id)::int AS result_count,
        (SELECT count(*) FROM test_run_amendments a WHERE a.test_run_id = r.id)::int AS amendment_count,
        (SELECT coalesce(array_agg(s.shard ORDER BY s.shard), '{}') FROM test_run_shards s WHERE s.test_run_id = r.id)::int[] AS shards_received
    FROM test_runs r
    WHERE r.id IN (SELECT q.test_run_id FROM test_results q WHERE q.id IN (SELECT id FROM page))
)
SELECT t.id, t.test_run_id, t.test_case_id, t.requested_test_case_id, t.correlation, t.test_name, t.class_name, t.suite_name, t.status, t.duration_ms, t.error_message, t.error_details, t.created_at, t.attempt, t.recorded_by, t.failed_step, t.shard, EXISTS (
        SELECT 1 FROM test_results x WHERE x.test_run_id = t.test_run_id AND x.suite_name = t.suite_name
          AND x.class_name = t.class_name AND x.test_name = t.test_name AND x.attempt > t.attempt
    ) AS retried,
    r.project_id AS run_project_id, r.external_run_id, r.provider, r.provider_run_id, r.run_attempt, r.pipeline, r.branch, r.commit_sha,
    r.status AS run_status, r.created_at AS run_created_at, r.started_at AS run_started_at, r.completed_at AS run_completed_at,
    r.report_sha256, r.suite_key, r.suite_name, r.mode AS run_mode, r.started_by AS run_started_by,
    r.shard_total AS run_shard_total, c.expected_count AS run_expected_count, c.result_count AS run_result_count,
    c.amendment_count AS run_amendment_count, c.shards_received AS run_shards_received
FROM test_results t
JOIN test_runs r ON r.id = t.test_run_id
JOIN counts c ON c.id = r.id
WHERE t.id IN (SELECT id FROM page)
ORDER BY t.id DESC
`

type ListResultsForTestCaseParams struct {
	TestCaseID pgtype.Int8
	PageOffset int32
	PageLimit  int32
}

type ListResultsForTestCaseRow struct {
	TestResult        TestResult
	Retried           bool
	RunProjectID      int64
	ExternalRunID     string
	Provider          string
	ProviderRunID     string
	RunAttempt        int32
	Pipeline          string
	Branch            string
	CommitSha         string
	RunStatus         string
	RunCreatedAt      pgtype.Timestamptz
	RunStartedAt      pgtype.Timestamptz
	RunCompletedAt    pgtype.Timestamptz
	ReportSha256      string
	SuiteKey          pgtype.Text
	SuiteName         pgtype.Text
	RunMode           string
	RunStartedBy      pgtype.Text
	RunShardTotal     pgtype.Int4
	RunExpectedCount  int32
	RunResultCount    int32
	RunAmendmentCount int32
	RunShardsReceived []int32
}

// The page is chosen first (index on test_case_id, id DESC) and each run's counts
// are computed once, not for every row skipped by OFFSET or repeated per result.
func (q *Queries) ListResultsForTestCase(ctx context.Context, arg ListResultsForTestCaseParams) ([]ListResultsForTestCaseRow, error) {
	rows, err := q.db.Query(ctx, listResultsForTestCase, arg.TestCaseID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResultsForTestCaseRow
	for rows.Next() {
		var i ListResultsForTestCaseRow
		if err := rows.Scan(
			&i.TestResult.ID,
			&i.TestResult.TestRunID,
			&i.TestResult.TestCaseID,
			&i.TestResult.RequestedTestCaseID,
			&i.TestResult.Correlation,
			&i.TestResult.TestName,
			&i.TestResult.ClassName,
			&i.TestResult.SuiteName,
			&i.TestResult.Status,
			&i.TestResult.DurationMs,
			&i.TestResult.ErrorMessage,
			&i.TestResult.ErrorDetails,
			&i.TestResult.CreatedAt,
			&i.TestResult.Attempt,
			&i.TestResult.RecordedBy,
			&i.TestResult.FailedStep,
			&i.TestResult.Shard,
			&i.Retried,
			&i.RunProjectID,
			&i.ExternalRunID,
			&i.Provider,
			&i.ProviderRunID,
			&i.RunAttempt,
			&i.Pipeline,
			&i.Branch,
			&i.CommitSha,
			&i.RunStatus,
			&i.RunCreatedAt,
			&i.RunStartedAt,
			&i.RunCompletedAt,
			&i.ReportSha256,
			&i.SuiteKey,
			&i.SuiteName,
			&i.RunMode,
			&i.RunStartedBy,
			&i.RunShardTotal,
			&i.RunExpectedCount,
			&i.RunResultCount,
			&i.RunAmendmentCount,
			&i.RunShardsReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunEvents = `-- name: ListRunEvents :many
SELECT id, test_run_id, event_id, sequence, event_type, test_name, requested_test_case_id, test_case_id, status, occurred_at, received_at, attempt FROM test_run_events WHERE test_run_id = $1 ORDER BY sequence, id
`

func (q *Queries) ListRunEvents(ctx context.Context, testRunID int64) ([]TestRunEvent, error) {
	rows, err := q.db.Query(ctx, listRunEvents, testRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestRunEvent
	for rows.Next() {
		var i TestRunEvent
		if err := rows.Scan(
			&i.ID,
			&i.TestRunID,
			&i.EventID,
			&i.Sequence,
			&i.EventType,
			&i.TestName,
			&i.RequestedTestCaseID,
			&i.TestCaseID,
			&i.Status,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.Attempt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunResults = `-- name: ListRunResults :many
SELECT t.id, t.test_run_id, t.test_case_id, t.requested_test_case_id, t.correlation, t.test_name, t.class_name, t.suite_name, t.status, t.duration_ms, t.error_message, t.error_details, t.created_at, t.attempt, t.recorded_by, t.failed_step, t.shard, EXISTS (
    SELECT 1 FROM test_results x WHERE x.test_run_id = t.test_run_id AND x.suite_name = t.suite_name
      AND x.class_name = t.class_name AND x.test_name = t.test_name AND x.attempt > t.attempt
) AS retried
FROM test_results t
WHERE t.test_run_id = $1
  AND ($2::text IS NULL OR t.status = $2::text)
  AND ($3::text IS NULL OR t.correlation = $3::text)
  AND ($4::int IS NULL OR t.shard = $4::int)
ORDER BY t.id
LIMIT $6 OFFSET $5
`

type ListRunResultsParams struct {
	TestRunID   int64
	Status      pgtype.Text
	Correlation pgtype.Text
	Shard       pgtype.Int4
	PageOffset  int32
	PageLimit   int32
}

type ListRunResultsRow struct {
	TestResult TestResult
	Retried    bool
}

// retried: a later attempt of the same test exists in the run, so this one is not its logical result.
func (q *Queries) ListRunResults(ctx context.Context, arg ListRunResultsParams) ([]ListRunResultsRow, error) {
	rows, err := q.db.Query(ctx, listRunResults,
		arg.TestRunID,
		arg.Status,
		arg.Correlation,
		arg.Shard,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunResultsRow
	for rows.Next() {
		var i ListRunResultsRow
		if err := rows.Scan(
			&i.TestResult.ID,
			&i.TestResult.TestRunID,
			&i.TestResult.TestCaseID,
			&i.TestResult.RequestedTestCaseID,
			&i.TestResult.Correlation,
			&i.TestResult.TestName,
			&i.TestResult.ClassName,
			&i.TestResult.SuiteName,
			&i.TestResult.Status,
			&i.TestResult.DurationMs,
			&i.TestResult.ErrorMessage,
			&i.TestResult.ErrorDetails,
			&i.TestResult.CreatedAt,
			&i.TestResult.Attempt,
			&i.TestResult.RecordedBy,
			&i.TestResult.FailedStep,
			&i.TestResult.Shard,
			&i.Retried,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunShards = `-- name: ListRunShards :many
SELECT s.shard, s.report_sha256, s.status,
    (SELECT count(*) FROM test_results t WHERE t.test_run_id = s.test_run_id AND t.shard = s.shard)::int AS result_count
FROM test_run_shards s WHERE s.test_run_id = $1 ORDER BY s.shard
`

type ListRunShardsRow struct {
	Shard        int32
	ReportSha256 string
	Status       string
	ResultCount  int32
}

func (q *Queries) ListRunShards(ctx context.Context, testRunID int64) ([]ListRunShardsRow, error) {
	rows, err := q.db.Query(ctx, listRunShards, testRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunShardsRow
	for rows.Next() {
		var i ListRunShardsRow
		if err := rows.Scan(
			&i.Shard,
			&i.ReportSha256,
			&i.Status,
			&i.ResultCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSummaryInputs = `-- name: ListSummaryInputs :many
SELECT test_run_id, test_case_id, 'expected' AS kind, NULL::text AS status, ''::text AS execution, 0 AS attempt
FROM test_run_expected_cases
WHERE test_run_id = ANY($1::bigint[])
UNION ALL
SELECT test_run_id, test_case_id, 'amended', NULL, '', 0 FROM test_run_amendments
WHERE test_run_id = ANY($1::bigint[])
UNION ALL
SELECT test_run_id, test_case_id::bigint, 'result', status, suite_name || chr(31) || class_name || chr(31) || test_name, attempt
FROM test_results
WHERE test_run_id = ANY($1::bigint[]) AND correlation = 'valid'
ORDER BY 1, 2
`

type ListSummaryInputsRow struct {
	TestRunID  int64
	TestCaseID int64
	Kind       string
	Status     pgtype.Text
	Execution  string
	Attempt    int32
}

// Snapshot TC-IDs (kind 'expected'), amendments ('amended') and valid results ('result', with their status, the
// test they belong to and their attempt) of the given runs, in one read.
func (q *Queries) ListSummaryInputs(ctx context.Context, testRunIds []int64) ([]ListSummaryInputsRow, error) {
	rows, err := q.db.Query(ctx, listSummaryInputs, testRunIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSummaryInputsRow
	for rows.Next() {
		var i ListSummaryInputsRow
		if err := rows.Scan(
			&i.TestRunID,
			&i.TestCaseID,
			&i.Kind,
			&i.Status,
			&i.Execution,
			&i.Attempt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestRuns = `-- name: ListTestRuns :many
SELECT r.id, r.external_run_id, r.provider, r.provider_run_id, r.run_attempt, r.pipeline, r.branch, r.commit_sha, r.status, r.created_at, r.started_at, r.completed_at, r.report_sha256, r.project_id, r.suite_key, r.suite_name, r.mode, r.started_by, r.shard_total,
    (SELECT count(*) FROM test_run_expected_cases e WHERE e.test_run_id = r.id)::int AS expected_count,
    (SELECT count(*) FROM test_results t WHERE t.test_run_id = r.id)::int AS result_count,
    (SELECT count(*) FROM test_run_amendments a WHERE a.test_run_id = r.id)::int AS amendment_count,
    (SELECT coalesce(array_agg(s.shard ORDER BY s.shard), '{}') FROM test_run_shards s WHERE s.test_run_id = r.id)::int[] AS shards_received
FROM test_runs r
WHERE r.id IN (
    SELECT p.id FROM test_runs p
    WHERE ($1::bigint[] IS NULL OR p.project_id = ANY($1::bigint[]))
      AND ($2::text IS NULL OR p.suite_key = $2::text)
    ORDER BY p.id DESC LIMIT $4 OFFSET $3
)
ORDER BY r.id DESC
`

type ListTestRunsParams struct {
	ProjectIds []int64
	SuiteKey   pgtype.Text
	PageOffset int32
	PageLimit  int32
}

type ListTestRunsRow struct {
	TestRun        TestRun
	ExpectedCount  int32
	ResultCount    int32
	AmendmentCount int32
	ShardsReceived []int32
}

// The page is chosen first: the per-run counts are only computed for its rows,
// not for every row skipped by OFFSET.
func (q *Queries) ListTestRuns(ctx context.Context, arg ListTestRunsParams) ([]ListTestRunsRow, error) {
	rows, err := q.db.Query(ctx, listTestRuns,
		arg.ProjectIds,
		arg.SuiteKey,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTestRunsRow
	for rows.Next() {
		var i ListTestRunsRow
		if err := rows.Scan(
			&i.TestRun.ID,
			&i.TestRun.ExternalRunID,
			&i.TestRun.Provider,
			&i.TestRun.ProviderRunID,
			&i.TestRun.RunAttempt,
			&i.TestRun.Pipeline,
			&i.TestRun.Branch,
			&i.TestRun.CommitSha,
			&i.TestRun.Status,
			&i.TestRun.CreatedAt,
			&i.TestRun.StartedAt,
			&i.TestRun.CompletedAt,
			&i.TestRun.ReportSha256,
			&i.TestRun.ProjectID,
			&i.TestRun.SuiteKey,
			&i.TestRun.SuiteName,
			&i.TestRun.Mode,
			&i.TestRun.StartedBy,
			&i.TestRun.ShardTotal,
			&i.ExpectedCount,
			&i.ResultCount,
			&i.AmendmentCount,
			&i.ShardsReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTestRun = `-- name: LockTestRun :one
SELECT status, mode FROM test_runs WHERE id = $1 FOR UPDATE
`

type LockTestRunRow struct {
	Status string
	Mode   string
}

// Locks a run until the transaction ends (manual recording and completion).
func (q *Queries) LockTestRun(ctx context.Context, id int64) (LockTestRunRow, error) {
	row := q.db.QueryRow(ctx, lockTestRun, id)
	var i LockTestRunRow
	err := row.Scan(&i.Status, &i.Mode)
	return i, err
}
