// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: execution.sql

package executiondb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeLiveRun = `-- name: CompleteLiveRun :exec
UPDATE test_runs SET status = $1, completed_at = now(), report_sha256 = $2
WHERE id = $3 AND mode = 'live' AND status = 'running'
`

type CompleteLiveRunParams struct {
	Status       string
	ReportSha256 string
	ID           int64
}

// The final report completes a running live run: its execution status, completion time and report digest.
func (q *Queries) CompleteLiveRun(ctx context.Context, arg CompleteLiveRunParams) error {
	_, err := q.db.Exec(ctx, completeLiveRun, arg.Status, arg.ReportSha256, arg.ID)
	return err
}

const countAmendments = `-- name: CountAmendments :one
SELECT count(*) FROM test_run_amendments WHERE test_run_id = $1
`

func (q *Queries) CountAmendments(ctx context.Context, testRunID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAmendments, testRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countParseErrors = `-- name: CountParseErrors :one
SELECT count(*) FROM test_run_parse_errors WHERE test_run_id = $1
`

func (q *Queries) CountParseErrors(ctx context.Context, testRunID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countParseErrors, testRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResultsForTestCase = `-- name: CountResultsForTestCase :one
SELECT count(*) FROM test_results WHERE test_case_id = $1
`

func (q *Queries) CountResultsForTestCase(ctx context.Context, testCaseID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countResultsForTestCase, testCaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunEvents = `-- name: CountRunEvents :one
SELECT count(*)::int FROM test_run_events WHERE test_run_id = $1
`

func (q *Queries) CountRunEvents(ctx context.Context, testRunID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countRunEvents, testRunID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countRunResults = `-- name: CountRunResults :one
SELECT count(*) FROM test_results
WHERE test_run_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR correlation = $3::text)
`

type CountRunResultsParams struct {
	TestRunID   int64
	Status      pgtype.Text
	Correlation pgtype.Text
}

func (q *Queries) CountRunResults(ctx context.Context, arg CountRunResultsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRunResults, arg.TestRunID, arg.Status, arg.Correlation)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTestRuns = `-- name: CountTestRuns :one
SELECT count(*) FROM test_runs
WHERE ($1::bigint[] IS NULL OR project_id = ANY($1::bigint[]))
  AND ($2::text IS NULL OR suite_key = $2::text)
`

type CountTestRunsParams struct {
	ProjectIds []int64
	SuiteKey   pgtype.Text
}

func (q *Queries) CountTestRuns(ctx context.Context, arg CountTestRunsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTestRuns, arg.ProjectIds, arg.SuiteKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishTestRun = `-- name: FinishTestRun :exec
UPDATE test_runs SET status = $1, completed_at = now() WHERE id = $2 AND status = 'running'
`

type FinishTestRunParams struct {
	Status string
	ID     int64
}

func (q *Queries) FinishTestRun(ctx context.Context, arg FinishTestRunParams) error {
	_, err := q.db.Exec(ctx, finishTestRun, arg.Status, arg.ID)
	return err
}

const getTestRun = `-- name: GetTestRun :one
SELECT r.id, r.external_run_id, r.provider, r.provider_run_id, r.run_attempt, r.pipeline, r.branch, r.commit_sha, r.status, r.created_at, r.started_at, r.completed_at, r.report_sha256, r.project_id, r.suite_key, r.suite_name, r.mode, r.started_by,
    (SELECT count(*) FROM test_run_expected_cases e WHERE e.test_run_id = r.id)::int AS expected_count,
    (SELECT count(*) FROM test_results t WHERE t.test_run_id = r.id)::int AS result_count,
    (SELECT count(*) FROM test_run_amendments a WHERE a.test_run_id = r.id)::int AS amendment_count
FROM test_runs r WHERE r.id = $1
`

type GetTestRunRow struct {
	ID             int64
	ExternalRunID  string
	Provider       string
	ProviderRunID  string
	RunAttempt     int32
	Pipeline       string
	Branch         string
	CommitSha      string
	Status         string
	CreatedAt      pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	ReportSha256   string
	ProjectID      int64
	SuiteKey       pgtype.Text
	SuiteName      pgtype.Text
	Mode           string
	StartedBy      pgtype.Text
	ExpectedCount  int32
	ResultCount    int32
	AmendmentCount int32
}

func (q *Queries) GetTestRun(ctx context.Context, id int64) (GetTestRunRow, error) {
	row := q.db.QueryRow(ctx, getTestRun, id)
	var i GetTestRunRow
	err := row.Scan(
		&i.ID,
		&i.ExternalRunID,
		&i.Provider,
		&i.ProviderRunID,
		&i.RunAttempt,
		&i.Pipeline,
		&i.Branch,
		&i.CommitSha,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ReportSha256,
		&i.ProjectID,
		&i.SuiteKey,
		&i.SuiteName,
		&i.Mode,
		&i.StartedBy,
		&i.ExpectedCount,
		&i.ResultCount,
		&i.AmendmentCount,
	)
	return i, err
}

const getTestRunIDByExternalID = `-- name: GetTestRunIDByExternalID :one
SELECT id FROM test_runs WHERE project_id = $1 AND external_run_id = $2
`

type GetTestRunIDByExternalIDParams struct {
	ProjectID     int64
	ExternalRunID string
}

func (q *Queries) GetTestRunIDByExternalID(ctx context.Context, arg GetTestRunIDByExternalIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTestRunIDByExternalID, arg.ProjectID, arg.ExternalRunID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAmendment = `-- name: InsertAmendment :one
INSERT INTO test_run_amendments (test_run_id, test_case_id, amended_by, amended_by_username, reason)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (test_run_id, test_case_id) DO NOTHING
RETURNING id, test_run_id, test_case_id, amended_by, amended_by_username, reason, created_at
`

type InsertAmendmentParams struct {
	TestRunID         int64
	TestCaseID        int64
	AmendedBy         int64
	AmendedByUsername string
	Reason            string
}

func (q *Queries) InsertAmendment(ctx context.Context, arg InsertAmendmentParams) (TestRunAmendment, error) {
	row := q.db.QueryRow(ctx, insertAmendment,
		arg.TestRunID,
		arg.TestCaseID,
		arg.AmendedBy,
		arg.AmendedByUsername,
		arg.Reason,
	)
	var i TestRunAmendment
	err := row.Scan(
		&i.ID,
		&i.TestRunID,
		&i.TestCaseID,
		&i.AmendedBy,
		&i.AmendedByUsername,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertExpectedCases = `-- name: InsertExpectedCases :exec
INSERT INTO test_run_expected_cases (test_run_id, test_case_id)
SELECT $1, unnest($2::bigint[])
`

type InsertExpectedCasesParams struct {
	TestRunID   int64
	TestCaseIds []int64
}

func (q *Queries) InsertExpectedCases(ctx context.Context, arg InsertExpectedCasesParams) error {
	_, err := q.db.Exec(ctx, insertExpectedCases, arg.TestRunID, arg.TestCaseIds)
	return err
}

const insertManualResult = `-- name: InsertManualResult :one
INSERT INTO test_results (test_run_id, test_case_id, requested_test_case_id, correlation, test_name, class_name, suite_name, status, duration_ms, error_message, error_details, attempt, recorded_by, failed_step)
SELECT $1, $2, $3, 'valid', $4, $5, '', $6, $7, $8, '',
    coalesce(max(x.attempt), 0) + 1, $9, $10
FROM test_results x WHERE x.test_run_id = $1 AND x.class_name = $5 AND x.test_name = $4
RETURNING id, test_run_id, test_case_id, requested_test_case_id, correlation, test_name, class_name, suite_name, status, duration_ms, error_message, error_details, created_at, attempt, recorded_by, failed_step
`

type InsertManualResultParams struct {
	TestRunID           int64
	TestCaseID          pgtype.Int8
	RequestedTestCaseID pgtype.Text
	TestName            string
	ClassName           string
	Status              string
	DurationMs          pgtype.Int8
	ErrorMessage        string
	RecordedBy          pgtype.Text
	FailedStep          pgtype.Int4
}

// One recorded result of a running run; a re-test of the same test is its next attempt.
func (q *Queries) InsertManualResult(ctx context.Context, arg InsertManualResultParams) (TestResult, error) {
	row := q.db.QueryRow(ctx, insertManualResult,
		arg.TestRunID,
		arg.TestCaseID,
		arg.RequestedTestCaseID,
		arg.TestName,
		arg.ClassName,
		arg.Status,
		arg.DurationMs,
		arg.ErrorMessage,
		arg.RecordedBy,
		arg.FailedStep,
	)
	var i TestResult
	err := row.Scan(
		&i.ID,
		&i.TestRunID,
		&i.TestCaseID,
		&i.RequestedTestCaseID,
		&i.Correlation,
		&i.TestName,
		&i.ClassName,
		&i.SuiteName,
		&i.Status,
		&i.DurationMs,
		&i.ErrorMessage,
		&i.ErrorDetails,
		&i.CreatedAt,
		&i.Attempt,
		&i.RecordedBy,
		&i.FailedStep,
	)
	return i, err
}

type InsertParseErrorsParams struct {
	TestRunID int64
	CaseIndex int32
	TestName  string
	Message   string
	Persisted bool
	Severity  string
}

const insertRunEvent = `-- name: InsertRunEvent :execrows
INSERT INTO test_run_events (test_run_id, event_id, sequence, event_type, test_name, requested_test_case_id, test_case_id, status, occurred_at, attempt)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (test_run_id, event_id) DO NOTHING
`

type InsertRunEventParams struct {
	TestRunID           int64
	EventID             string
	Sequence            int64
	EventType           string
	TestName            string
	RequestedTestCaseID pgtype.Text
	TestCaseID          pgtype.Int8
	Status              pgtype.Text
	OccurredAt          pgtype.Timestamptz
	Attempt             int32
}

// Appends one live event; an event id already received for the run is a duplicate delivery and is skipped (0 rows).
func (q *Queries) InsertRunEvent(ctx context.Context, arg InsertRunEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRunEvent,
		arg.TestRunID,
		arg.EventID,
		arg.Sequence,
		arg.EventType,
		arg.TestName,
		arg.RequestedTestCaseID,
		arg.TestCaseID,
		arg.Status,
		arg.OccurredAt,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

type InsertTestResultsParams struct {
	TestRunID           int64
	TestCaseID          pgtype.Int8
	RequestedTestCaseID pgtype.Text
	Correlation         string
	TestName            string
	ClassName           string
	SuiteName           string
	Status              string
	DurationMs          pgtype.Int8
	ErrorMessage        string
	ErrorDetails        string
	Attempt             int32
}

const insertTestRun = `-- name: InsertTestRun :one
INSERT INTO test_runs (project_id, external_run_id, provider, provider_run_id, run_attempt, pipeline, branch, commit_sha, status, started_at, completed_at, report_sha256, suite_key, suite_name, mode, started_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (project_id, external_run_id) DO NOTHING
RETURNING id
`

type InsertTestRunParams struct {
	ProjectID     int64
	ExternalRunID string
	Provider      string
	ProviderRunID string
	RunAttempt    int32
	Pipeline      string
	Branch        string
	CommitSha     string
	Status        string
	StartedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
	ReportSha256  string
	SuiteKey      pgtype.Text
	SuiteName     pgtype.Text
	Mode          string
	StartedBy     pgtype.Text
}

func (q *Queries) InsertTestRun(ctx context.Context, arg InsertTestRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertTestRun,
		arg.ProjectID,
		arg.ExternalRunID,
		arg.Provider,
		arg.ProviderRunID,
		arg.RunAttempt,
		arg.Pipeline,
		arg.Branch,
		arg.CommitSha,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ReportSha256,
		arg.SuiteKey,
		arg.SuiteName,
		arg.Mode,
		arg.StartedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const isInUniverse = `-- name: IsInUniverse :one
SELECT EXISTS (SELECT 1 FROM test_run_expected_cases e WHERE e.test_run_id = $1::bigint AND e.test_case_id = $2::bigint)
    OR EXISTS (SELECT 1 FROM test_run_amendments a WHERE a.test_run_id = $1::bigint AND a.test_case_id = $2::bigint)
`

type IsInUniverseParams struct {
	RunID  int64
	CaseID int64
}

// Whether a test case is in a run's universe: its snapshot or its amendments.
func (q *Queries) IsInUniverse(ctx context.Context, arg IsInUniverseParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isInUniverse, arg.RunID, arg.CaseID)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listAmendments = `-- name: ListAmendments :many
SELECT id, test_run_id, test_case_id, amended_by, amended_by_username, reason, created_at FROM test_run_amendments WHERE test_run_id = $1 ORDER BY id
LIMIT $3 OFFSET $2
`

type ListAmendmentsParams struct {
	TestRunID  int64
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListAmendments(ctx context.Context, arg ListAmendmentsParams) ([]TestRunAmendment, error) {
	rows, err := q.db.Query(ctx, listAmendments, arg.TestRunID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestRunAmendment
	for rows.Next() {
		var i TestRunAmendment
		if err := rows.Scan(
			&i.ID,
			&i.TestRunID,
			&i.TestCaseID,
			&i.AmendedBy,
			&i.AmendedByUsername,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiagnosticResults = `-- name: ListDiagnosticResults :many
SELECT test_name, correlation, requested_test_case_id FROM test_results
WHERE test_run_id = $1 AND correlation <> 'valid'
ORDER BY id
`

type ListDiagnosticResultsRow struct {
	TestName            string
	Correlation         string
	RequestedTestCaseID pgtype.Text
}

func (q *Queries) ListDiagnosticResults(ctx context.Context, testRunID int64) ([]ListDiagnosticResultsRow, error) {
	rows, err := q.db.Query(ctx, listDiagnosticResults, testRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiagnosticResultsRow
	for rows.Next() {
		var i ListDiagnosticResultsRow
		if err := rows.Scan(&i.TestName, &i.Correlation, &i.RequestedTestCaseID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlakyCounts = `-- name: ListFlakyCounts :many
WITH runs AS (
    SELECT id FROM test_runs WHERE project_id = $2 ORDER BY id DESC LIMIT $3
), tests AS (
    SELECT t.test_case_id, t.test_run_id,
        (array_agg(t.status ORDER BY t.attempt DESC, t.id DESC))[1] AS last_status,
        bool_or(t.status IN ('failed', 'error')) AS any_failure
    FROM test_results t
    WHERE t.test_run_id IN (SELECT id FROM runs) AND t.correlation = 'valid' AND t.class_name <> 'provenly-manual'
    GROUP BY t.test_case_id, t.test_run_id, t.suite_name, t.class_name, t.test_name
)
SELECT x.test_case_id::bigint AS test_case_id, count(DISTINCT x.test_run_id)::int AS flaky_runs
FROM tests x WHERE x.last_status = 'passed' AND x.any_failure
GROUP BY x.test_case_id
ORDER BY flaky_runs DESC, x.test_case_id
LIMIT $1
`

type ListFlakyCountsParams struct {
	MaxItems   int32
	ProjectID  int64
	WindowRuns int32
}

type ListFlakyCountsRow struct {
	TestCaseID int64
	FlakyRuns  int32
}

// In a project's latest runs, how many runs each test case was flaky in: one of its tests passed on its last attempt
// after a failed or errored one. Manual re-tests are never flaky.
func (q *Queries) ListFlakyCounts(ctx context.Context, arg ListFlakyCountsParams) ([]ListFlakyCountsRow, error) {
	rows, err := q.db.Query(ctx, listFlakyCounts, arg.MaxItems, arg.ProjectID, arg.WindowRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlakyCountsRow
	for rows.Next() {
		var i ListFlakyCountsRow
		if err := rows.Scan(&i.TestCaseID, &i.FlakyRuns); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLastExecuted = `-- name: ListLastExecuted :many
SELECT t.test_case_id::bigint AS test_case_id, max(r.created_at)::timestamptz AS last_executed_at
FROM test_results t JOIN test_runs r ON r.id = t.test_run_id
WHERE t.correlation = 'valid' AND t.test_case_id = ANY($1::bigint[])
GROUP BY t.test_case_id
`

type ListLastExecutedRow struct {
	TestCaseID     int64
	LastExecutedAt pgtype.Timestamptz
}

// When each given test case last had a valid result (the creation time of its latest run with one).
func (q *Queries) ListLastExecuted(ctx context.Context, testCaseIds []int64) ([]ListLastExecutedRow, error) {
	rows, err := q.db.Query(ctx, listLastExecuted, testCaseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLastExecutedRow
	for rows.Next() {
		var i ListLastExecutedRow
		if err := rows.Scan(&i.TestCaseID, &i.LastExecutedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestConclusive = `-- name: ListLatestConclusive :many
WITH last_attempts AS (
    SELECT DISTINCT ON (t.test_case_id, t.test_run_id, t.suite_name, t.class_name, t.test_name)
        t.test_case_id, t.test_run_id, t.status
    FROM test_results t
    WHERE t.correlation = 'valid' AND t.test_case_id = ANY($1::bigint[])
    ORDER BY t.test_case_id, t.test_run_id, t.suite_name, t.class_name, t.test_name, t.attempt DESC, t.id DESC
), per_run AS (
    SELECT a.test_case_id, a.test_run_id,
        CASE WHEN bool_or(a.status = 'failed') THEN 'failed' WHEN bool_or(a.status = 'error') THEN 'error'
             WHEN bool_or(a.status = 'skipped') THEN 'skipped' ELSE 'passed' END AS status
    FROM last_attempts a GROUP BY a.test_case_id, a.test_run_id
)
SELECT DISTINCT ON (p.test_case_id) p.test_case_id::bigint AS test_case_id, p.test_run_id, p.status::text AS status
FROM per_run p WHERE p.status <> 'skipped'
ORDER BY p.test_case_id, p.test_run_id DESC
`

type ListLatestConclusiveRow struct {
	TestCaseID int64
	TestRunID  int64
	Status     string
}

// For each given test case, its latest run with a conclusive logical status (passed, failed or error; skipped runs are
// inconclusive) and that status. The logical status of a test case in a run is the highest attempt of each test,
// aggregated failed > error > skipped > passed, as in summaries.
func (q *Queries) ListLatestConclusive(ctx context.Context, testCaseIds []int64) ([]ListLatestConclusiveRow, error) {
	rows, err := q.db.Query(ctx, listLatestConclusive, testCaseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestConclusiveRow
	for rows.Next() {
		var i ListLatestConclusiveRow
		if err := rows.Scan(&i.TestCaseID, &i.TestRunID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestResults = `-- name: ListLatestResults :many
SELECT t.test_case_id::bigint AS test_case_id, t.status, (t.suite_name || chr(31) || t.class_name || chr(31) || t.test_name)::text AS execution, t.attempt
FROM test_results t
WHERE t.correlation = 'valid' AND t.test_case_id = ANY($1::bigint[])
  AND t.test_run_id = (SELECT max(x.test_run_id) FROM test_results x WHERE x.test_case_id = t.test_case_id AND x.correlation = 'valid')
ORDER BY t.test_case_id, t.id
`

type ListLatestResultsRow struct {
	TestCaseID int64
	Status     string
	Execution  string
	Attempt    int32
}

// The valid results of each given test case in the latest run that has one for it (status, test and attempt), to
// read its latest status (requirement coverage).
func (q *Queries) ListLatestResults(ctx context.Context, testCaseIds []int64) ([]ListLatestResultsRow, error) {
	rows, err := q.db.Query(ctx, listLatestResults, testCaseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestResultsRow
	for rows.Next() {
		var i ListLatestResultsRow
		if err := rows.Scan(
			&i.TestCaseID,
			&i.Status,
			&i.Execution,
			&i.Attempt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParseErrors = `-- name: ListParseErrors :many
SELECT case_index, test_name, message, persisted, severity FROM test_run_parse_errors
WHERE test_run_id = $1
ORDER BY case_index
LIMIT $3 OFFSET $2
`

type ListParseErrorsParams struct {
	TestRunID  int64
	PageOffset int32
	PageLimit  int32
}

type ListParseErrorsRow struct {
	CaseIndex int32
	TestName  string
	Message   string
	Persisted bool
	Severity  string
}

func (q *Queries) ListParseErrors(ctx context.Context, arg ListParseErrorsParams) ([]ListParseErrorsRow, error) {
	rows, err := q.db.Query(ctx, listParseErrors, arg.TestRunID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParseErrorsRow
	for rows.Next() {
		var i ListParseErrorsRow
		if err := rows.Scan(
			&i.CaseIndex,
			&i.TestName,
			&i.Message,
			&i.Persisted,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResultsForTestCase = `-- name: ListResultsForTestCase :many
WITH page AS (
    SELECT p.id FROM test_results p WHERE p.test_case_id = $1
    ORDER BY p.id DESC LIMIT $3 OFFSET $2
), counts AS (
    SELECT r.id,
        (SELECT count(*) FROM test_run_expected_cases e WHERE e.test_run_id = r.id)::int AS expected_count,
        (SELECT count(*) FROM test_results x WHERE x.test_run_id = r.id)::int AS result_count,
        (SELECT count(*) FROM test_run_amendments a WHERE a.test_run_id = r.id)::int AS amendment_count
    FROM test_runs r
    WHERE r.id IN (SELECT q.test_run_id FROM test_results q WHERE q.id IN (SELECT id FROM page))
)
SELECT t.id, t.test_run_id, t.test_case_id, t.requested_test_case_id, t.correlation, t.test_name, t.class_name, t.suite_name, t.status, t.duration_ms, t.error_message, t.error_details, t.created_at, t.attempt, t.recorded_by, t.failed_step, EXISTS (
        SELECT 1 FROM test_results x WHERE x.test_run_id = t.test_run_id AND x.suite_name = t.suite_name
          AND x.class_name = t.class_name AND x.test_name = t.test_name AND x.attempt > t.attempt
    ) AS retried,
    r.project_id AS run_project_id, r.external_run_id, r.provider, r.provider_run_id, r.run_attempt, r.pipeline, r.branch, r.commit_sha,
    r.status AS run_status, r.created_at AS run_created_at, r.started_at AS run_started_at, r.completed_at AS run_completed_at,
    c.expected_count AS run_expected_count, c.result_count AS run_result_count, c.amendment_count AS run_amendment_count
FROM test_results t
JOIN test_runs r ON r.id = t.test_run_id
JOIN counts c ON c.id = r.id
WHERE t.id IN (SELECT id FROM page)
ORDER BY t.id DESC
`

type ListResultsForTestCaseParams struct {
	TestCaseID pgtype.Int8
	PageOffset int32
	PageLimit  int32
}

type ListResultsForTestCaseRow struct {
	TestResult        TestResult
	Retried           bool
	RunProjectID      int64
	ExternalRunID     string
	Provider          string
	ProviderRunID     string
	RunAttempt        int32
	Pipeline          string
	Branch            string
	CommitSha         string
	RunStatus         string
	RunCreatedAt      pgtype.Timestamptz
	RunStartedAt      pgtype.Timestamptz
	RunCompletedAt    pgtype.Timestamptz
	RunExpectedCount  int32
	RunResultCount    int32
	RunAmendmentCount int32
}

// The page is chosen first (index on test_case_id, id DESC) and each run's counts
// are computed once, not for every row skipped by OFFSET or repeated per result.
func (q *Queries) ListResultsForTestCase(ctx context.Context, arg ListResultsForTestCaseParams) ([]ListResultsForTestCaseRow, error) {
	rows, err := q.db.Query(ctx, listResultsForTestCase, arg.TestCaseID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResultsForTestCaseRow
	for rows.Next() {
		var i ListResultsForTestCaseRow
		if err := rows.Scan(
			&i.TestResult.ID,
			&i.TestResult.TestRunID,
			&i.TestResult.TestCaseID,
			&i.TestResult.RequestedTestCaseID,
			&i.TestResult.Correlation,
			&i.TestResult.TestName,
			&i.TestResult.ClassName,
			&i.TestResult.SuiteName,
			&i.TestResult.Status,
			&i.TestResult.DurationMs,
			&i.TestResult.ErrorMessage,
			&i.TestResult.ErrorDetails,
			&i.TestResult.CreatedAt,
			&i.TestResult.Attempt,
			&i.TestResult.RecordedBy,
			&i.TestResult.FailedStep,
			&i.Retried,
			&i.RunProjectID,
			&i.ExternalRunID,
			&i.Provider,
			&i.ProviderRunID,
			&i.RunAttempt,
			&i.Pipeline,
			&i.Branch,
			&i.CommitSha,
			&i.RunStatus,
			&i.RunCreatedAt,
			&i.RunStartedAt,
			&i.RunCompletedAt,
			&i.RunExpectedCount,
			&i.RunResultCount,
			&i.RunAmendmentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunEvents = `-- name: ListRunEvents :many
SELECT id, test_run_id, event_id, sequence, event_type, test_name, requested_test_case_id, test_case_id, status, occurred_at, received_at, attempt FROM test_run_events WHERE test_run_id = $1 ORDER BY sequence, id
`

func (q *Queries) ListRunEvents(ctx context.Context, testRunID int64) ([]TestRunEvent, error) {
	rows, err := q.db.Query(ctx, listRunEvents, testRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestRunEvent
	for rows.Next() {
		var i TestRunEvent
		if err := rows.Scan(
			&i.ID,
			&i.TestRunID,
			&i.EventID,
			&i.Sequence,
			&i.EventType,
			&i.TestName,
			&i.RequestedTestCaseID,
			&i.TestCaseID,
			&i.Status,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.Attempt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunResults = `-- name: ListRunResults :many
SELECT t.id, t.test_run_id, t.test_case_id, t.requested_test_case_id, t.correlation, t.test_name, t.class_name, t.suite_name, t.status, t.duration_ms, t.error_message, t.error_details, t.created_at, t.attempt, t.recorded_by, t.failed_step, EXISTS (
    SELECT 1 FROM test_results x WHERE x.test_run_id = t.test_run_id AND x.suite_name = t.suite_name
      AND x.class_name = t.class_name AND x.test_name = t.test_name AND x.attempt > t.attempt
) AS retried
FROM test_results t
WHERE t.test_run_id = $1
  AND ($2::text IS NULL OR t.status = $2::text)
  AND ($3::text IS NULL OR t.correlation = $3::text)
ORDER BY t.id
LIMIT $5 OFFSET $4
`

type ListRunResultsParams struct {
	TestRunID   int64
	Status      pgtype.Text
	Correlation pgtype.Text
	PageOffset  int32
	PageLimit   int32
}

type ListRunResultsRow struct {
	TestResult TestResult
	Retried    bool
}

// retried: a later attempt of the same test exists in the run, so this one is not its logical result.
func (q *Queries) ListRunResults(ctx context.Context, arg ListRunResultsParams) ([]ListRunResultsRow, error) {
	rows, err := q.db.Query(ctx, listRunResults,
		arg.TestRunID,
		arg.Status,
		arg.Correlation,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunResultsRow
	for rows.Next() {
		var i ListRunResultsRow
		if err := rows.Scan(
			&i.TestResult.ID,
			&i.TestResult.TestRunID,
			&i.TestResult.TestCaseID,
			&i.TestResult.RequestedTestCaseID,
			&i.TestResult.Correlation,
			&i.TestResult.TestName,
			&i.TestResult.ClassName,
			&i.TestResult.SuiteName,
			&i.TestResult.Status,
			&i.TestResult.DurationMs,
			&i.TestResult.ErrorMessage,
			&i.TestResult.ErrorDetails,
			&i.TestResult.CreatedAt,
			&i.TestResult.Attempt,
			&i.TestResult.RecordedBy,
			&i.TestResult.FailedStep,
			&i.Retried,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSummaryInputs = `-- name: ListSummaryInputs :many
SELECT test_run_id, test_case_id, 'expected' AS kind, NULL::text AS status, ''::text AS execution, 0 AS attempt
FROM test_run_expected_cases
WHERE test_run_id = ANY($1::bigint[])
UNION ALL
SELECT test_run_id, test_case_id, 'amended', NULL, '', 0 FROM test_run_amendments
WHERE test_run_id = ANY($1::bigint[])
UNION ALL
SELECT test_run_id, test_case_id::bigint, 'result', status, suite_name || chr(31) || class_name || chr(31) || test_name, attempt
FROM test_results
WHERE test_run_id = ANY($1::bigint[]) AND correlation = 'valid'
ORDER BY 1, 2
`

type ListSummaryInputsRow struct {
	TestRunID  int64
	TestCaseID int64
	Kind       string
	Status     pgtype.Text
	Execution  string
	Attempt    int32
}

// Snapshot TC-IDs (kind 'expected'), amendments ('amended') and valid results ('result', with their status, the
// test they belong to and their attempt) of the given runs, in one read.
func (q *Queries) ListSummaryInputs(ctx context.Context, testRunIds []int64) ([]ListSummaryInputsRow, error) {
	rows, err := q.db.Query(ctx, listSummaryInputs, testRunIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSummaryInputsRow
	for rows.Next() {
		var i ListSummaryInputsRow
		if err := rows.Scan(
			&i.TestRunID,
			&i.TestCaseID,
			&i.Kind,
			&i.Status,
			&i.Execution,
			&i.Attempt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestRuns = `-- name: ListTestRuns :many
SELECT r.id, r.external_run_id, r.provider, r.provider_run_id, r.run_attempt, r.pipeline, r.branch, r.commit_sha, r.status, r.created_at, r.started_at, r.completed_at, r.report_sha256, r.project_id, r.suite_key, r.suite_name, r.mode, r.started_by,
    (SELECT count(*) FROM test_run_expected_cases e WHERE e.test_run_id = r.id)::int AS expected_count,
    (SELECT count(*) FROM test_results t WHERE t.test_run_id = r.id)::int AS result_count,
    (SELECT count(*) FROM test_run_amendments a WHERE a.test_run_id = r.id)::int AS amendment_count
FROM test_runs r
WHERE r.id IN (
    SELECT p.id FROM test_runs p
    WHERE ($1::bigint[] IS NULL OR p.project_id = ANY($1::bigint[]))
      AND ($2::text IS NULL OR p.suite_key = $2::text)
    ORDER BY p.id DESC LIMIT $4 OFFSET $3
)
ORDER BY r.id DESC
`

type ListTestRunsParams struct {
	ProjectIds []int64
	SuiteKey   pgtype.Text
	PageOffset int32
	PageLimit  int32
}

type ListTestRunsRow struct {
	ID             int64
	ExternalRunID  string
	Provider       string
	ProviderRunID  string
	RunAttempt     int32
	Pipeline       string
	Branch         string
	CommitSha      string
	Status         string
	CreatedAt      pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	ReportSha256   string
	ProjectID      int64
	SuiteKey       pgtype.Text
	SuiteName      pgtype.Text
	Mode           string
	StartedBy      pgtype.Text
	ExpectedCount  int32
	ResultCount    int32
	AmendmentCount int32
}

// The page is chosen first: the per-run counts are only computed for its rows,
// not for every row skipped by OFFSET.
func (q *Queries) ListTestRuns(ctx context.Context, arg ListTestRunsParams) ([]ListTestRunsRow, error) {
	rows, err := q.db.Query(ctx, listTestRuns,
		arg.ProjectIds,
		arg.SuiteKey,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTestRunsRow
	for rows.Next() {
		var i ListTestRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalRunID,
			&i.Provider,
			&i.ProviderRunID,
			&i.RunAttempt,
			&i.Pipeline,
			&i.Branch,
			&i.CommitSha,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ReportSha256,
			&i.ProjectID,
			&i.SuiteKey,
			&i.SuiteName,
			&i.Mode,
			&i.StartedBy,
			&i.ExpectedCount,
			&i.ResultCount,
			&i.AmendmentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTestRun = `-- name: LockTestRun :one
SELECT status, mode FROM test_runs WHERE id = $1 FOR UPDATE
`

type LockTestRunRow struct {
	Status string
	Mode   string
}

// Locks a run until the transaction ends (manual recording and completion).
func (q *Queries) LockTestRun(ctx context.Context, id int64) (LockTestRunRow, error) {
	row := q.db.QueryRow(ctx, lockTestRun, id)
	var i LockTestRunRow
	err := row.Scan(&i.Status, &i.Mode)
	return i, err
}
