// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package executiondb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TestResult struct {
	ID                  int64
	TestRunID           int64
	TestCaseID          pgtype.Int8
	RequestedTestCaseID pgtype.Text
	Correlation         string
	TestName            string
	ClassName           string
	SuiteName           string
	Status              string
	DurationMs          pgtype.Int8
	ErrorMessage        string
	ErrorDetails        string
	CreatedAt           pgtype.Timestamptz
	Attempt             int32
	RecordedBy          pgtype.Text
	FailedStep          pgtype.Int4
}

type TestRun struct {
	ID            int64
	ExternalRunID string
	Provider      string
	ProviderRunID string
	RunAttempt    int32
	Pipeline      string
	Branch        string
	CommitSha     string
	Status        string
	CreatedAt     pgtype.Timestamptz
	StartedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
	ReportSha256  string
	ProjectID     int64
	SuiteKey      pgtype.Text
	SuiteName     pgtype.Text
	Mode          string
	StartedBy     pgtype.Text
}

type TestRunAmendment struct {
	ID                int64
	TestRunID         int64
	TestCaseID        int64
	AmendedBy         int64
	AmendedByUsername string
	Reason            string
	CreatedAt         pgtype.Timestamptz
}

type TestRunExpectedCase struct {
	TestRunID  int64
	TestCaseID int64
}

type TestRunParseError struct {
	TestRunID int64
	CaseIndex int32
	TestName  string
	Message   string
	Persisted bool
	Severity  string
}
