// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package executiondb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// The final report completes a running live run: its execution status, completion time and report digest.
	CompleteLiveRun(ctx context.Context, arg CompleteLiveRunParams) error
	CountAmendments(ctx context.Context, testRunID int64) (int64, error)
	CountParseErrors(ctx context.Context, testRunID int64) (int64, error)
	CountResultsForTestCase(ctx context.Context, testCaseID pgtype.Int8) (int64, error)
	CountRunEvents(ctx context.Context, testRunID int64) (int32, error)
	CountRunResults(ctx context.Context, arg CountRunResultsParams) (int64, error)
	CountTestRuns(ctx context.Context, arg CountTestRunsParams) (int64, error)
	// Every shard arrived (or CI finalized the run): its execution status and completion time.
	FinishShardedRun(ctx context.Context, arg FinishShardedRunParams) error
	FinishTestRun(ctx context.Context, arg FinishTestRunParams) error
	// The project of a run: what authorizing a request on it needs, without the run's counts and outcome.
	GetRunProject(ctx context.Context, id int64) (int64, error)
	GetTestRun(ctx context.Context, id int64) (GetTestRunRow, error)
	GetTestRunIDByExternalID(ctx context.Context, arg GetTestRunIDByExternalIDParams) (int64, error)
	InsertAmendment(ctx context.Context, arg InsertAmendmentParams) (TestRunAmendment, error)
	InsertExpectedCases(ctx context.Context, arg InsertExpectedCasesParams) error
	// One recorded result of a running run; a re-test of the same test is its next attempt.
	// Nothing is inserted past the last allowed attempt (the column's CHECK would fail the transaction instead).
	InsertManualResult(ctx context.Context, arg InsertManualResultParams) (TestResult, error)
	InsertParseErrors(ctx context.Context, arg []InsertParseErrorsParams) (int64, error)
	// Appends one live event; an event id already received for the run is a duplicate delivery and is skipped (0 rows).
	InsertRunEvent(ctx context.Context, arg InsertRunEventParams) (int64, error)
	// Records a shard of a running sharded run; a shard already received is a replay (0 rows).
	InsertRunShard(ctx context.Context, arg InsertRunShardParams) (int64, error)
	InsertTestResults(ctx context.Context, arg []InsertTestResultsParams) (int64, error)
	InsertTestRun(ctx context.Context, arg InsertTestRunParams) (int64, error)
	// Whether a test case is in a run's universe: its snapshot or its amendments.
	IsInUniverse(ctx context.Context, arg IsInUniverseParams) (pgtype.Bool, error)
	ListAmendments(ctx context.Context, arg ListAmendmentsParams) ([]TestRunAmendment, error)
	ListDiagnosticResults(ctx context.Context, testRunID int64) ([]ListDiagnosticResultsRow, error)
	// In a project's latest runs, how many runs each test case was flaky in: every result of one of its tests' last
	// attempt passed after a failed or errored earlier attempt, and the test case did not fail or error in that run (a
	// variant that failed for good is a failure, not flakiness). Manual re-tests are never flaky.
	ListFlakyCounts(ctx context.Context, arg ListFlakyCountsParams) ([]ListFlakyCountsRow, error)
	// When each given test case last had a valid result (the creation time of its latest run with one).
	ListLastExecuted(ctx context.Context, testCaseIds []int64) ([]ListLastExecutedRow, error)
	// For each given test case, its latest run with a conclusive logical status (passed, failed or error; skipped runs are
	// inconclusive) and that status. The logical status of a test case in a run is the highest attempt of each test
	// (every result of it: repeated names without an attempt signal are variants), aggregated failed > error > skipped >
	// passed, as in summaries.
	// Runs are walked newest first per test case and the walk stops at the first conclusive one (index
	// test_results_case_run_valid_idx), instead of aggregating every run of the test case's history.
	ListLatestConclusive(ctx context.Context, testCaseIds []int64) ([]ListLatestConclusiveRow, error)
	// The valid results of each given test case in the latest run that has one for it (status, test and attempt), to
	// read its latest status (requirement coverage).
	// The latest run is found first, once per test case (index test_results_case_run_valid_idx), then only its results
	// are read.
	ListLatestResults(ctx context.Context, testCaseIds []int64) ([]ListLatestResultsRow, error)
	ListParseErrors(ctx context.Context, arg ListParseErrorsParams) ([]ListParseErrorsRow, error)
	// The page is chosen first (index on test_case_id, id DESC) and each run's counts
	// are computed once, not for every row skipped by OFFSET or repeated per result.
	ListResultsForTestCase(ctx context.Context, arg ListResultsForTestCaseParams) ([]ListResultsForTestCaseRow, error)
	ListRunEvents(ctx context.Context, testRunID int64) ([]TestRunEvent, error)
	// retried: a later attempt of the same test exists in the run, so this one is not its logical result.
	ListRunResults(ctx context.Context, arg ListRunResultsParams) ([]ListRunResultsRow, error)
	ListRunShards(ctx context.Context, testRunID int64) ([]ListRunShardsRow, error)
	// Snapshot TC-IDs (kind 'expected'), amendments ('amended') and valid results ('result', with their status, the
	// test they belong to and their attempt) of the given runs, in one read.
	ListSummaryInputs(ctx context.Context, testRunIds []int64) ([]ListSummaryInputsRow, error)
	// The page is chosen first: the per-run counts are only computed for its rows,
	// not for every row skipped by OFFSET.
	ListTestRuns(ctx context.Context, arg ListTestRunsParams) ([]ListTestRunsRow, error)
	// Locks a run until the transaction ends (manual recording and completion).
	LockTestRun(ctx context.Context, id int64) (LockTestRunRow, error)
}

var _ Querier = (*Queries)(nil)
