// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package executiondb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountResultsForTestCase(ctx context.Context, testCaseID pgtype.Int8) (int64, error)
	CountRunResults(ctx context.Context, arg CountRunResultsParams) (int64, error)
	CountTestRuns(ctx context.Context) (int64, error)
	GetTestRun(ctx context.Context, id int64) (GetTestRunRow, error)
	GetTestRunIDByExternalID(ctx context.Context, externalRunID string) (int64, error)
	InsertExpectedCases(ctx context.Context, arg InsertExpectedCasesParams) error
	InsertTestResults(ctx context.Context, arg []InsertTestResultsParams) (int64, error)
	InsertTestRun(ctx context.Context, arg InsertTestRunParams) (int64, error)
	ListDiagnosticResults(ctx context.Context, testRunID int64) ([]ListDiagnosticResultsRow, error)
	ListExpectedCaseIDs(ctx context.Context, testRunID int64) ([]int64, error)
	ListResultsForTestCase(ctx context.Context, arg ListResultsForTestCaseParams) ([]ListResultsForTestCaseRow, error)
	ListRunResults(ctx context.Context, arg ListRunResultsParams) ([]TestResult, error)
	ListTestRuns(ctx context.Context, arg ListTestRunsParams) ([]ListTestRunsRow, error)
	ListValidResultStatuses(ctx context.Context, testRunID int64) ([]ListValidResultStatusesRow, error)
}

var _ Querier = (*Queries)(nil)
