// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package auditdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT count(*) FROM audit_events
WHERE ($1::text IS NULL OR project_key = $1)
  AND ($2::text IS NULL OR actor = $2)
  AND ($3::text IS NULL OR test_case_key = $3)
  AND ($4::text[] IS NULL OR project_key = ANY($4::text[]))
`

type CountAuditEventsParams struct {
	ProjectKey  pgtype.Text
	Actor       pgtype.Text
	TestCaseKey pgtype.Text
	ProjectKeys []string
}

func (q *Queries) CountAuditEvents(ctx context.Context, arg CountAuditEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents,
		arg.ProjectKey,
		arg.Actor,
		arg.TestCaseKey,
		arg.ProjectKeys,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (actor, action, path, project_key, status, summary, test_case_key, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9)
`

type InsertAuditEventParams struct {
	Actor       string
	Action      string
	Path        string
	ProjectKey  pgtype.Text
	Status      int32
	Summary     pgtype.Text
	TestCaseKey pgtype.Text
	Ip          pgtype.Text
	UserAgent   pgtype.Text
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.Actor,
		arg.Action,
		arg.Path,
		arg.ProjectKey,
		arg.Status,
		arg.Summary,
		arg.TestCaseKey,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, occurred_at, actor, action, path, project_key, status, summary, test_case_key, ip, user_agent FROM audit_events
WHERE ($1::text IS NULL OR project_key = $1)
  AND ($2::text IS NULL OR actor = $2)
  AND ($3::text IS NULL OR test_case_key = $3)
  AND ($4::text[] IS NULL OR project_key = ANY($4::text[]))
ORDER BY id DESC LIMIT $6 OFFSET $5
`

type ListAuditEventsParams struct {
	ProjectKey  pgtype.Text
	Actor       pgtype.Text
	TestCaseKey pgtype.Text
	ProjectKeys []string
	PageOffset  int32
	PageLimit   int32
}

// Newest first, narrowed by project, actor and/or test case; project_keys limits a maintainer to their projects.
func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.ProjectKey,
		arg.Actor,
		arg.TestCaseKey,
		arg.ProjectKeys,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Actor,
			&i.Action,
			&i.Path,
			&i.ProjectKey,
			&i.Status,
			&i.Summary,
			&i.TestCaseKey,
			&i.Ip,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
