// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auditdb

import (
	"context"
)

type Querier interface {
	CountAuditEvents(ctx context.Context, arg CountAuditEventsParams) (int64, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	// Newest first, narrowed by project, actor and/or test case.
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
}

var _ Querier = (*Queries)(nil)
