/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness check (the database is reachable) */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with a username and password
         * @description Returns a session token and sets it as the HttpOnly `provenly_session` cookie (SameSite=Strict).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out (clears the session cookie) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the signed-in user's password; every other session is signed out */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users by username (administrators) */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invitations, newest first (administrators) */
        get: operations["listInvitations"];
        put?: never;
        /** Create a single-use invitation link (administrators); the token is shown only in this response */
        post: operations["createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{invitationId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitationId: components["parameters"]["InvitationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a pending invitation (administrators) */
        post: operations["revokeInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account from an invitation link and sign in */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects (by key) */
        get: operations["listProjects"];
        put?: never;
        /** Create a project. The key is trimmed and upper-cased; it can never change. */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectKey}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example CHK */
                projectKey: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        /** Get a project by its key */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit a project's name or description (the key never changes) */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/api/v1/projects/{projectKey}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example CHK */
                projectKey: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        /** List a project's members by username (anyone who can see the project) */
        get: operations["listProjectMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectKey}/members/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example CHK */
                projectKey: components["parameters"]["ProjectKey"];
                /** @example ana */
                username: components["parameters"]["Username"];
            };
            cookie?: never;
        };
        get?: never;
        /** Add a user to the project or change their role (maintainers and administrators) */
        put: operations["setProjectMember"];
        post?: never;
        /** Remove a user from the project (maintainers and administrators) */
        delete: operations["removeProjectMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectKey}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example CHK */
                projectKey: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        /** List the project's API keys, newest first (maintainers and administrators) */
        get: operations["listApiKeys"];
        put?: never;
        /**
         * Create an API key for CI to report runs into this project (maintainers and administrators)
         * @description The key is returned once and never stored; only its digest is kept.
         */
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectKey}/api-keys/{apiKeyId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example CHK */
                projectKey: components["parameters"]["ProjectKey"];
                apiKeyId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke an API key at once (maintainers and administrators) */
        post: operations["revokeApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List test cases (newest id first) */
        get: operations["listTestCases"];
        put?: never;
        /** Create a test case. The TC-ID is assigned by the server. */
        post: operations["createTestCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/{testCaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        /** Get a test case by its numeric id */
        get: operations["getTestCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit test case content. Never changes the TC-ID nor creates a version. */
        patch: operations["updateTestCase"];
        trace?: never;
    };
    "/api/v1/test-cases/{testCaseId}/deprecate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deprecate a test case (idempotent). History is preserved; it leaves the expected universe of future runs. */
        post: operations["deprecateTestCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/{testCaseId}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivate a deprecated test case (idempotent). Same TC-ID; existing run snapshots are unchanged, future runs include it again if automated. */
        post: operations["reactivateTestCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/{testCaseId}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        /** List the steps of a test case, ordered by position */
        get: operations["listTestSteps"];
        put?: never;
        /** Add a step. Appended at the end unless `position` is given. */
        post: operations["createTestStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/{testCaseId}/steps/order": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Reorder steps. `stepIds` must be a permutation of all current step ids. */
        put: operations["reorderTestSteps"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/{testCaseId}/steps/{stepId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
                stepId: components["parameters"]["StepId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a step. Remaining steps are renumbered contiguously. */
        delete: operations["deleteTestStep"];
        options?: never;
        head?: never;
        /** Edit a step's action and/or expected result */
        patch: operations["updateTestStep"];
        trace?: never;
    };
    "/api/v1/test-cases/{testCaseId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        /** Result history of a TC-ID across runs (newest first), with observed execution metadata */
        get: operations["listTestCaseResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List test runs (newest first) */
        get: operations["listTestRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-runs/{testRunId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                testRunId: components["parameters"]["TestRunId"];
            };
            cookie?: never;
        };
        /** Get a test run */
        get: operations["getTestRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-runs/{testRunId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                testRunId: components["parameters"]["TestRunId"];
            };
            cookie?: never;
        };
        /** Individual results of a run, optionally filtered by status and/or TC-ID correlation */
        get: operations["listTestRunResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-runs/{testRunId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                testRunId: components["parameters"]["TestRunId"];
            };
            cookie?: never;
        };
        /** Snapshot-based summary with counts and the three percentages */
        get: operations["getTestRunSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-runs/{testRunId}/parse-errors": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                testRunId: components["parameters"]["TestRunId"];
            };
            cookie?: never;
        };
        /** Testcases of the ingested report that could not be fully normalized, in document order */
        get: operations["listTestRunParseErrors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/junit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest one complete JUnit XML report (batch) for a CI run attempt
         * @description CI authenticates with a project API key; people with a session need the
         *     `member` role in the project. A key reports into its own project only: it is
         *     the default `project`, and any other project answers 404.
         *     The run belongs to `project` (default: the API key's project, else `TC`): its expected universe is that
         *     project's, the testcase-name fallback only reads `<project>-<n>`, and a
         *     `tc-id` property with another project's key is a `wrong_project` diagnostic.
         *     `externalRunId` = `{provider}:{runId}:{runAttempt}`, unique per project. Re-sending the same
         *     attempt is idempotent (200, no duplicate run, no reprocessing; if the report
         *     content differs from the original, a `warnings` entry says it was not
         *     applied); a new
         *     attempt creates a new run (201). Individual invalid testcases never abort
         *     the batch: they are persisted with a correlation diagnostic, or reported in
         *     `parseErrors` (stored with the run; `persisted` tells whether the result
         *     was kept, e.g. with an unknown duration, or discarded, e.g. without name).
         */
        post: operations["ingestJUnitReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        Problem: {
            /**
             * @description URI reference identifying the problem type
             * @example about:blank
             */
            type: string;
            title: string;
            /** Format: int32 */
            status: number;
            /**
             * @description Stable machine-readable error code. Requests that match no operation get `not_found` (404), or `method_not_allowed` (405, with an `Allow` header) when the path exists for other methods.
             * @enum {string}
             */
            code: "bad_request" | "validation_error" | "invalid_junit" | "not_found" | "conflict" | "unauthorized" | "forbidden" | "method_not_allowed" | "payload_too_large" | "unsupported_media_type" | "service_unavailable" | "internal_error";
            detail?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            field: string;
            message: string;
        };
        PageMeta: {
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            totalItems: number;
            /** Format: int32 */
            totalPages: number;
        };
        /** @enum {string} */
        TestCaseStatus: "active" | "deprecated";
        TestCase: {
            /**
             * Format: int64
             * @example 153
             */
            id: number;
            /** @example CHK-12 */
            key: string;
            /** Format: int64 */
            projectId: number;
            /** @example CHK */
            projectKey: string;
            /**
             * Format: int64
             * @example 12
             */
            number: number;
            title: string;
            description: string;
            expectedResult: string;
            status: components["schemas"]["TestCaseStatus"];
            automated: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deprecatedAt?: string | null;
        };
        User: {
            /** Format: int64 */
            id: number;
            /** @example ana */
            username: string;
            /** @example Ana Pérez */
            displayName: string;
            email: string | null;
            isAdmin: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        UserPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["User"][];
        };
        Session: {
            /** @description Signed session token (JWT); send it as `Authorization: Bearer <token>` */
            token: string;
            /** Format: date-time */
            expiresAt: string;
            user: components["schemas"]["User"];
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            /** @description 10 characters to 72 bytes */
            newPassword: string;
        };
        /** @enum {string} */
        InvitationStatus: "pending" | "accepted" | "revoked" | "expired";
        Invitation: {
            /** Format: int64 */
            id: number;
            email: string | null;
            note: string;
            status: components["schemas"]["InvitationStatus"];
            /** Format: int64 */
            createdBy: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            acceptedAt: string | null;
            /** Format: int64 */
            acceptedUserId: number | null;
            /** Format: date-time */
            revokedAt: string | null;
            /**
             * Format: int64
             * @description The project the account joins on accept, if any
             */
            projectId: number | null;
            /** @enum {string|null} */
            projectRole: "maintainer" | "member" | "viewer" | null;
        };
        InvitationPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["Invitation"][];
        };
        CreateInvitationRequest: {
            /** @description Optional; becomes the account's email unless the person gives another */
            email?: string | null;
            note?: string;
            /** @description Key of a project the account joins on accept (with `role`) */
            project?: string;
            role?: components["schemas"]["ProjectRole"];
        };
        /** @enum {string} */
        ProjectRole: "maintainer" | "member" | "viewer";
        Member: {
            user: components["schemas"]["User"];
            role: components["schemas"]["ProjectRole"];
            /** Format: date-time */
            since: string;
        };
        MemberPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["Member"][];
        };
        SetMemberRequest: {
            role: components["schemas"]["ProjectRole"];
        };
        ApiKey: {
            /** Format: int64 */
            id: number;
            name: string;
            /** @description First characters of the key, to tell keys apart (the key itself is never shown again). */
            prefix: string;
            /** @enum {string} */
            status: "active" | "revoked";
            /** Format: int64 */
            createdBy: number;
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last report made with the key (recorded at most once a minute).
             */
            lastUsedAt: string | null;
            /** Format: date-time */
            revokedAt: string | null;
        };
        ApiKeyPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["ApiKey"][];
        };
        CreateApiKeyRequest: {
            /**
             * @description What the key is for (e.g. the CI pipeline); 1 to 100 characters.
             * @example GitHub Actions
             */
            name: string;
        };
        CreatedApiKey: {
            apiKey: components["schemas"]["ApiKey"];
            /** @description The key: send it as `Authorization: Bearer <token>`. Shown only once. */
            token: string;
        };
        CreatedInvitation: {
            invitation: components["schemas"]["Invitation"];
            /** @description Shown only here; the link is `<web origin>/accept-invite?token=<token>` */
            token: string;
        };
        AcceptInvitationRequest: {
            token: string;
            /** @description Stored lower-cased; 3 to 32 characters */
            username: string;
            displayName: string;
            email?: string | null;
            password: string;
        };
        Project: {
            /** Format: int64 */
            id: number;
            /** @example CHK */
            key: string;
            /** @example Checkout */
            name: string;
            description: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * @description What the signed-in user may do in this project
             * @enum {string}
             */
            myRole: "admin" | "maintainer" | "member" | "viewer";
        };
        ProjectPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["Project"][];
        };
        CreateProjectRequest: {
            /**
             * @description 2 to 10 letters or digits, starting with a letter; stored upper-cased.
             * @example CHK
             */
            key: string;
            name: string;
            description?: string;
        };
        UpdateProjectRequest: {
            name?: string;
            description?: string;
        };
        TestCasePage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["TestCase"][];
        };
        CreateTestCaseRequest: {
            /** @description Key of the project the test case belongs to (default `TC`); it never changes. */
            project?: string;
            title: string;
            description?: string;
            expectedResult?: string;
            /** @default false */
            automated?: boolean;
        };
        UpdateTestCaseRequest: {
            title?: string;
            description?: string;
            expectedResult?: string;
            automated?: boolean;
        };
        TestStep: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            testCaseId: number;
            /**
             * Format: int32
             * @description 1-based, contiguous order within the test case
             */
            position: number;
            action: string;
            expectedResult: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TestStepPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["TestStep"][];
        };
        TestStepList: {
            items: components["schemas"]["TestStep"][];
        };
        CreateTestStepRequest: {
            action: string;
            expectedResult?: string;
            /**
             * Format: int32
             * @description Insert at this 1-based position (clamped to the end)
             */
            position?: number;
        };
        UpdateTestStepRequest: {
            action?: string;
            expectedResult?: string;
        };
        ReorderTestStepsRequest: {
            stepIds: number[];
        };
        /**
         * @description How the CI execution ended, as reported by CI: `completed`, `interrupted` (the pipeline
         *     broke) or `cancelled` (it was stopped). It says nothing about test outcomes: see
         *     `TestRun.outcome.verdict`.
         * @default completed
         * @enum {string}
         */
        ExecutionStatus: "completed" | "interrupted" | "cancelled";
        /**
         * @description Derived from the run's summary (snapshot TC-IDs with their aggregated status):
         *     `no_tests` when the expected universe is empty; otherwise `failed` when any TC-ID
         *     failed or errored; otherwise `incomplete` when any is untested or skipped;
         *     otherwise `passed`.
         * @enum {string}
         */
        RunVerdict: "passed" | "failed" | "incomplete" | "no_tests";
        /** @description Test outcome of a run, from the same computation as its summary. */
        RunOutcome: {
            verdict: components["schemas"]["RunVerdict"];
            /**
             * Format: int32
             * @description Expected TC-IDs with at least one result
             */
            executed: number;
            /** Format: int32 */
            passed: number;
            /** Format: int32 */
            failed: number;
            /** Format: int32 */
            error: number;
            /** Format: int32 */
            skipped: number;
            /** Format: int32 */
            untested: number;
            /**
             * Format: double
             * @description Percentage of executed TC-IDs that passed (0 when none was executed)
             */
            passRate: number;
        };
        TestRun: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            projectId: number;
            /** @example github:9876543210:1 */
            externalRunId: string;
            provider: string;
            providerRunId: string;
            /** Format: int32 */
            runAttempt: number;
            pipeline: string;
            branch: string;
            commit: string;
            executionStatus: components["schemas"]["ExecutionStatus"];
            outcome: components["schemas"]["RunOutcome"];
            /**
             * Format: int32
             * @description Size of the immutable expected-universe snapshot
             */
            expectedCount: number;
            /** Format: int32 */
            resultCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
        };
        TestRunPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["TestRun"][];
        };
        /** @enum {string} */
        ResultStatus: "passed" | "failed" | "error" | "skipped";
        /**
         * @description Outcome of TC-ID extraction/validation for a result
         * @enum {string}
         */
        Correlation: "valid" | "missing" | "malformed" | "unknown" | "deprecated" | "wrong_project";
        TestResult: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            testRunId: number;
            /**
             * Format: int64
             * @description Set when correlation is `valid` or `deprecated` (a result received after the test case was deprecated still belongs to its history)
             */
            testCaseId: number | null;
            /**
             * @description Display key (`<projectKey>-<number>`) of the linked test case; null when not linked
             * @example CHK-12
             */
            testCaseKey: string | null;
            /** @description Raw TC-ID reference as declared by the test (for diagnostics) */
            requestedTestCaseId: string | null;
            correlation: components["schemas"]["Correlation"];
            testName: string;
            className: string;
            suiteName: string;
            status: components["schemas"]["ResultStatus"];
            /**
             * Format: int64
             * @description Milliseconds, rounded from the JUnit `time` attribute (seconds). 0 means
             *     reported as 0 or under 0.5 ms; null means not reported or invalid.
             */
            durationMs: number | null;
            errorMessage: string;
            errorDetails: string;
            /** Format: date-time */
            createdAt: string;
        };
        TestResultPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["TestResult"][];
        };
        /** @description A historical result of a TC-ID plus the metadata observed at execution time */
        TestCaseResult: {
            result: components["schemas"]["TestResult"];
            run: components["schemas"]["TestRun"];
        };
        TestCaseResultPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["TestCaseResult"][];
        };
        /** @enum {string} */
        SummaryStatus: "untested" | "passed" | "failed" | "error" | "skipped";
        StatusCounts: {
            /** Format: int32 */
            untested: number;
            /** Format: int32 */
            passed: number;
            /** Format: int32 */
            failed: number;
            /** Format: int32 */
            error: number;
            /** Format: int32 */
            skipped: number;
        };
        StatusPercentages: {
            untested: number;
            passed: number;
            failed: number;
            error: number;
            skipped: number;
        };
        ExecutedPercentages: {
            passed: number;
            failed: number;
            error: number;
            skipped: number;
        };
        DiagnosticCounts: {
            /**
             * Format: int32
             * @description References with another project's key (not correlated)
             */
            wrongProject: number;
            /** Format: int32 */
            missing: number;
            /** Format: int32 */
            malformed: number;
            /** Format: int32 */
            unknown: number;
            /** Format: int32 */
            deprecated: number;
            /** Format: int32 */
            total: number;
        };
        TestCaseOutcome: {
            /** Format: int64 */
            testCaseId: number;
            /** @example CHK-12 */
            testCaseKey: string;
            status: components["schemas"]["SummaryStatus"];
            /** Format: int32 */
            resultCount: number;
        };
        /**
         * @description Computed against the run's immutable expected-universe snapshot.
         *     Percentages are 0..100 with 6 decimals (0 when the denominator is 0);
         *     clients round them for display and compute totals from these precise values.
         *     Results with an invalid TC-ID are excluded and reported in `diagnostics`.
         *     Valid results for test cases outside the snapshot (e.g. automated=false)
         *     are excluded and counted in `outsideUniverse`.
         */
        TestRunSummary: {
            /** Format: int64 */
            testRunId: number;
            /** Format: int32 */
            expectedTotal: number;
            /** Format: int32 */
            executedTotal: number;
            counts: components["schemas"]["StatusCounts"];
            percentOfExpected: components["schemas"]["StatusPercentages"];
            percentOfExecuted: components["schemas"]["ExecutedPercentages"];
            executionPercent: number;
            diagnostics: components["schemas"]["DiagnosticCounts"];
            /**
             * Format: int32
             * @description Valid results whose test case was not in the snapshot (e.g. automated=false at run creation)
             */
            outsideUniverse: number;
            /** @description Distinct TC-IDs behind `outsideUniverse`, so the UI can warn and offer to mark them automated */
            outsideUniverseTestCaseIds: number[];
            /** @description Aggregated status per TC-ID of the snapshot (failed > error > skipped > passed; untested when no result) */
            testCases: components["schemas"]["TestCaseOutcome"][];
        };
        IngestionDiagnostic: {
            testName: string;
            /** @enum {string} */
            correlation: "missing" | "malformed" | "unknown" | "deprecated" | "wrong_project";
            requestedTestCaseId: string | null;
            message: string;
        };
        ParseError: {
            /**
             * Format: int32
             * @description 0-based position of the testcase in document order
             */
            index: number;
            testName: string;
            message: string;
            /** @description true when the result was still stored (e.g. invalid time), false when it was discarded */
            persisted: boolean;
            /**
             * @description error = data was lost or is unknown (no name, invalid time);
             *     warning = stored but worth reviewing (a passed/failed test with a 0 ms duration)
             * @enum {string}
             */
            severity: "error" | "warning";
        };
        ParseErrorPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["ParseError"][];
        };
        IngestionResponse: {
            /** @description false when the request was an idempotent replay */
            created: boolean;
            testRun: components["schemas"]["TestRun"];
            /**
             * Format: int32
             * @description testcase elements found in the document
             */
            received: number;
            /**
             * Format: int32
             * @description results stored for the run
             */
            persisted: number;
            diagnostics: components["schemas"]["IngestionDiagnostic"][];
            parseErrors: components["schemas"]["ParseError"][];
            /**
             * @description Non-blocking notices. On an idempotent replay whose report differs
             *     (SHA-256) from the one that created the run, it says the new report
             *     was not applied (send a new runAttempt to record it); likewise when
             *     the replay reports another status, pipeline, branch or commit. On a
             *     new run, it says when the report's suite timestamp is later than the
             *     ingestion or cannot be read (startedAt is then left unknown).
             */
            warnings: string[];
        };
    };
    responses: {
        /** @description Invalid request (parameters, body or document) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No valid session (missing, invalid or expired), or wrong username or password at sign-in */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Signed in but not allowed (e.g. not an administrator) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request conflicts with the current state (e.g. a project key already in use) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request body exceeds the allowed size */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unsupported Content-Type */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A dependency (the database) is unreachable */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unexpected server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @example ana */
        Username: string;
        InvitationId: number;
        /** @example CHK */
        ProjectKey: string;
        /**
         * @description Only items of the project with this key (an unknown key is a 404).
         * @example CHK
         */
        ProjectFilter: string;
        Page: number;
        PageSize: number;
        /** @description Numeric TC-ID (without the `TC-` prefix) */
        TestCaseId: number;
        StepId: number;
        TestRunId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service can serve requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed; a fresh session is returned and set as cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listInvitations: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of invitations (never their tokens) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedInvitation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    revokeInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitationId: components["parameters"]["InvitationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitationRequest"];
            };
        };
        responses: {
            /** @description Account created and signed in (session cookie set) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example CHK */
                projectKey: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example CHK */
                projectKey: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Updated project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    listProjectMembers: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                /** @example CHK */
                projectKey: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    setProjectMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example CHK */
                projectKey: components["parameters"]["ProjectKey"];
                /** @example ana */
                username: components["parameters"]["Username"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMemberRequest"];
            };
        };
        responses: {
            /** @description The membership */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    removeProjectMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example CHK */
                projectKey: components["parameters"]["ProjectKey"];
                /** @example ana */
                username: components["parameters"]["Username"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listApiKeys: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                /** @example CHK */
                projectKey: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of API keys (never the keys themselves) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example CHK */
                projectKey: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApiKeyRequest"];
            };
        };
        responses: {
            /** @description The key and its token (shown only now) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedApiKey"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    revokeApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example CHK */
                projectKey: components["parameters"]["ProjectKey"];
                apiKeyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The revoked key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    listTestCases: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                status?: components["schemas"]["TestCaseStatus"];
                /**
                 * @description Only items of the project with this key (an unknown key is a 404).
                 * @example CHK
                 */
                project?: components["parameters"]["ProjectFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of test cases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCasePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createTestCase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTestCaseRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    getTestCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test case */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateTestCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTestCaseRequest"];
            };
        };
        responses: {
            /** @description Updated test case */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    deprecateTestCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deprecated test case */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    reactivateTestCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active test case */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listTestSteps: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of steps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestStepPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createTestStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTestStepRequest"];
            };
        };
        responses: {
            /** @description Created step */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestStep"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    reorderTestSteps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderTestStepsRequest"];
            };
        };
        responses: {
            /** @description Steps in their new order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestStepList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteTestStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
                stepId: components["parameters"]["StepId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateTestStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
                stepId: components["parameters"]["StepId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTestStepRequest"];
            };
        };
        responses: {
            /** @description Updated step */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestStep"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    listTestCaseResults: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                /** @description Numeric TC-ID (without the `TC-` prefix) */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of historical results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseResultPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listTestRuns: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Only items of the project with this key (an unknown key is a 404).
                 * @example CHK
                 */
                project?: components["parameters"]["ProjectFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of test runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRunPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getTestRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                testRunId: components["parameters"]["TestRunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRun"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listTestRunResults: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                status?: components["schemas"]["ResultStatus"];
                correlation?: components["schemas"]["Correlation"];
            };
            header?: never;
            path: {
                testRunId: components["parameters"]["TestRunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResultPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getTestRunSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                testRunId: components["parameters"]["TestRunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRunSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listTestRunParseErrors: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                testRunId: components["parameters"]["TestRunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of parse errors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseErrorPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    ingestJUnitReport: {
        parameters: {
            query: {
                /**
                 * @description Key of the project the run belongs to (default the API key's project, else `TC`).
                 * @example CHK
                 */
                project?: string;
                /** @example github */
                provider: string;
                /** @example 9876543210 */
                runId: string;
                /** @example 1 */
                runAttempt: number;
                pipeline?: string;
                branch?: string;
                commit?: string;
                /**
                 * @description How the CI execution ended (the run's `executionStatus`). `interrupted` or
                 *     `cancelled` mark a run whose pipeline broke or was stopped, so its report may
                 *     be incomplete and its untested test cases may simply not have run.
                 */
                status?: components["schemas"]["ExecutionStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The JUnit XML document, uncompressed (a `Content-Encoding` other than
         *     `identity` is a 415). `application/xml`, `text/xml` and any `+xml` media
         *     type are accepted. A `charset` parameter overrides the document's XML
         *     declaration (RFC 7303); UTF-8, US-ASCII, ISO-8859-1, windows-1252 and
         *     UTF-16 are supported, any other charset is a 415.
         */
        requestBody: {
            content: {
                "application/xml": string;
                "text/xml": string;
            };
        };
        responses: {
            /** @description Idempotent replay; the existing run is returned unchanged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResponse"];
                };
            };
            /** @description New test run created and results persisted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
}
