--
-- PostgreSQL database dump
--

\restrict zfSN5CjbMafa2uDQK2CxBeI1R1DumXz4IwQ7fxVkBnfevAghKtJObab0Noquidm

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: test_cases_protect_identity(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.test_cases_protect_identity() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'test cases cannot be deleted (TC-%s); deprecate instead', OLD.id;
    END IF;
    IF NEW.id <> OLD.id THEN
        RAISE EXCEPTION 'test case id is immutable (TC-%s)', OLD.id;
    END IF;
    RETURN NEW;
END;
$$;


--
-- Name: test_run_expected_cases_immutable(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.test_run_expected_cases_immutable() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    RAISE EXCEPTION 'the expected-universe snapshot of a test run is immutable';
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: test_cases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_cases (
    id bigint NOT NULL,
    title text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    expected_result text DEFAULT ''::text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    automated boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deprecated_at timestamp with time zone,
    CONSTRAINT test_cases_status_check CHECK ((status = ANY (ARRAY['active'::text, 'deprecated'::text]))),
    CONSTRAINT test_cases_title_check CHECK (((length(title) >= 1) AND (length(title) <= 200)))
);


--
-- Name: test_cases_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.test_cases ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.test_cases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: test_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_results (
    id bigint NOT NULL,
    test_run_id bigint NOT NULL,
    test_case_id bigint,
    requested_test_case_id text,
    correlation text NOT NULL,
    test_name text NOT NULL,
    class_name text DEFAULT ''::text NOT NULL,
    suite_name text DEFAULT ''::text NOT NULL,
    status text NOT NULL,
    duration_ms bigint,
    error_message text DEFAULT ''::text NOT NULL,
    error_details text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT test_results_correlation_check CHECK ((correlation = ANY (ARRAY['valid'::text, 'missing'::text, 'malformed'::text, 'unknown'::text, 'deprecated'::text]))),
    CONSTRAINT test_results_duration_ms_check CHECK ((duration_ms >= 0)),
    CONSTRAINT test_results_linked_has_test_case CHECK (((correlation = ANY (ARRAY['valid'::text, 'deprecated'::text])) = (test_case_id IS NOT NULL))),
    CONSTRAINT test_results_status_check CHECK ((status = ANY (ARRAY['passed'::text, 'failed'::text, 'error'::text, 'skipped'::text])))
);


--
-- Name: test_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.test_results ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.test_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: test_run_expected_cases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_run_expected_cases (
    test_run_id bigint NOT NULL,
    test_case_id bigint NOT NULL
);


--
-- Name: test_run_parse_errors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_run_parse_errors (
    test_run_id bigint NOT NULL,
    case_index integer NOT NULL,
    test_name text NOT NULL,
    message text NOT NULL,
    persisted boolean NOT NULL,
    severity text DEFAULT 'error'::text NOT NULL,
    CONSTRAINT test_run_parse_errors_case_index_check CHECK ((case_index >= 0)),
    CONSTRAINT test_run_parse_errors_severity_check CHECK ((severity = ANY (ARRAY['error'::text, 'warning'::text])))
);


--
-- Name: test_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_runs (
    id bigint NOT NULL,
    external_run_id text NOT NULL,
    provider text NOT NULL,
    provider_run_id text NOT NULL,
    run_attempt integer NOT NULL,
    pipeline text DEFAULT ''::text NOT NULL,
    branch text DEFAULT ''::text NOT NULL,
    commit_sha text DEFAULT ''::text NOT NULL,
    status text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    report_sha256 text DEFAULT ''::text NOT NULL,
    CONSTRAINT test_runs_external_run_id_format CHECK ((external_run_id = ((((provider || ':'::text) || provider_run_id) || ':'::text) || run_attempt))),
    CONSTRAINT test_runs_run_attempt_check CHECK ((run_attempt >= 1)),
    CONSTRAINT test_runs_status_check CHECK ((status = ANY (ARRAY['created'::text, 'running'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])))
);


--
-- Name: test_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.test_runs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.test_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: test_steps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_steps (
    id bigint NOT NULL,
    test_case_id bigint NOT NULL,
    "position" integer NOT NULL,
    action text NOT NULL,
    expected_result text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT test_steps_action_check CHECK (((length(action) >= 1) AND (length(action) <= 2000))),
    CONSTRAINT test_steps_position_check CHECK (("position" >= 1))
);


--
-- Name: test_steps_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.test_steps ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.test_steps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: goose_db_version; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.goose_db_version (id, version_id, is_applied, tstamp) FROM stdin;
1	0	t	2026-09-30 12:04:00.361338
2	1	t	2026-09-30 12:04:00.371189
3	2	t	2026-09-30 12:04:00.388764
4	3	t	2026-09-30 12:04:00.407746
5	4	t	2026-09-30 12:04:00.410784
6	5	t	2026-09-30 12:04:00.416831
7	6	t	2026-09-30 12:04:00.418748
\.


--
-- Data for Name: test_cases; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.test_cases (id, title, description, expected_result, status, automated, created_at, updated_at, deprecated_at) FROM stdin;
1	User can log in with email and password		The dashboard is shown with the user name	active	t	2026-09-30 12:04:18.263225+00	2026-09-30 12:04:18.263225+00	\N
2	User can log out		The login page is shown	active	t	2026-09-30 12:04:18.308747+00	2026-09-30 12:04:18.308747+00	\N
3	Checkout with credit card		Order is confirmed	active	t	2026-09-30 12:04:18.319514+00	2026-09-30 12:04:18.319514+00	\N
4	Search products by name		Matching products are listed	active	t	2026-09-30 12:04:18.348203+00	2026-09-30 12:04:18.348203+00	\N
6	Password reset email is sent		An email with a reset link arrives	active	f	2026-09-30 12:04:18.367096+00	2026-09-30 12:04:18.367096+00	\N
7	Accessibility audit of the checkout		No critical WCAG issues	active	f	2026-09-30 12:04:18.375713+00	2026-09-30 12:04:18.375713+00	\N
5	Export orders to CSV (legacy)		A CSV file is downloaded	deprecated	t	2026-09-30 12:04:18.357339+00	2026-09-30 12:04:18.433718+00	2026-09-30 12:04:18.433718+00
\.


--
-- Data for Name: test_results; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.test_results (id, test_run_id, test_case_id, requested_test_case_id, correlation, test_name, class_name, suite_name, status, duration_ms, error_message, error_details, created_at) FROM stdin;
1	1	1	1	valid	login [chromium]	web	web	passed	1284			2026-09-30 12:04:18.392475+00
2	1	1	TC-1	valid	login [firefox]	web	web	failed	1284	Sign in button not found	Error: Sign in button not found	2026-09-30 12:04:18.392475+00
3	1	2	2	valid	logout	web	web	passed	0			2026-09-30 12:04:18.392475+00
4	1	3	3	valid	checkout with visa	web	web	skipped	1284	payment sandbox down		2026-09-30 12:04:18.392475+00
5	1	5	5	valid	export csv	web	web	error	1284	timeout after 30s	TimeoutError	2026-09-30 12:04:18.392475+00
6	1	6	6	valid	password reset	web	web	passed	1284			2026-09-30 12:04:18.392475+00
7	1	\N	\N	missing	header renders	web	web	passed	200			2026-09-30 12:04:18.392475+00
8	1	\N	987654321	unknown	wishlist	web	web	passed	1284			2026-09-30 12:04:18.392475+00
9	1	\N	TC-12x	malformed	cart badge	web	web	passed	1284			2026-09-30 12:04:18.392475+00
10	1	4	4	valid	search by name	web	web	passed	\N			2026-09-30 12:04:18.392475+00
11	2	1	1	valid	login [chromium]	web	web	passed	1284			2026-09-30 12:04:18.411445+00
12	3	2	2	valid	logout	web	web	passed	1284			2026-09-30 12:04:18.423526+00
13	4	5	5	deprecated	export csv	web	web	passed	1284			2026-09-30 12:04:18.444423+00
14	5	1	1	valid	login	web	web	passed	1284			2026-09-30 12:04:18.459495+00
15	5	2	2	valid	logout	web	web	failed	1284	session cookie still present	Error: session cookie still present	2026-09-30 12:04:18.459495+00
16	5	3	3	valid	checkout	web	web	skipped	1284			2026-09-30 12:04:18.459495+00
\.


--
-- Data for Name: test_run_expected_cases; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.test_run_expected_cases (test_run_id, test_case_id) FROM stdin;
1	1
1	2
1	3
1	4
1	5
2	1
2	2
2	3
2	4
2	5
3	1
3	2
3	3
3	4
3	5
4	1
4	2
4	3
4	4
5	1
5	2
5	3
5	4
\.


--
-- Data for Name: test_run_parse_errors; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.test_run_parse_errors (test_run_id, case_index, test_name, message, persisted, severity) FROM stdin;
1	2	logout	passed test reported a 0 ms duration (0 or under 0.5 ms); review the reporter	t	warning
1	9	search by name	invalid time attribute "abc"; result kept without duration	t	error
1	10		testcase has no name; result discarded	f	error
\.


--
-- Data for Name: test_runs; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.test_runs (id, external_run_id, provider, provider_run_id, run_attempt, pipeline, branch, commit_sha, status, created_at, started_at, completed_at, report_sha256) FROM stdin;
1	github:1001:1	github	1001	1	e2e-nightly	main	9f3c2a1e7b	completed	2026-09-30 12:04:18.392475+00	2026-09-28 09:00:00+00	2026-09-30 12:04:18.392533+00	dc1ef5ef79bf60ded677005ba2cc160f72ff0225002bc9137199079e4b3ab7aa
2	github:1002:1	github	1002	1	e2e-nightly	feature/checkout	9f3c2a1e7b	failed	2026-09-30 12:04:18.411445+00	2026-09-28 11:00:00+00	2026-09-30 12:04:18.411524+00	c882c0f3ea7ea482d97039705d5d417278e8fa5628f38c1f5077b591edc277af
3	github:1003:1	github	1003	1	e2e-nightly	feature/search	9f3c2a1e7b	cancelled	2026-09-30 12:04:18.423526+00	2026-09-28 12:00:00+00	2026-09-30 12:04:18.423575+00	868dd884de80f1e4a7138e6c4c93f8ab3da0239093bed1d590bf18ff8b6aa8c0
4	github:1004:1	github	1004	1	e2e-nightly	main	9f3c2a1e7b	completed	2026-09-30 12:04:18.444423+00	2026-09-28 13:00:00+00	2026-09-30 12:04:18.444479+00	b7b4c2e0be3eb9ff71f09e4d551789f89a130de306ad830f976184f4b0d63fad
5	github:1005:1	github	1005	1	e2e-nightly	main	9f3c2a1e7b	completed	2026-09-30 12:04:18.459495+00	2026-09-28 14:00:00+00	2026-09-30 12:04:18.459587+00	7bb10617ab7e1002cc15b7dfb60006e26b44468beb7c7a2139595ec77bae7be6
\.


--
-- Data for Name: test_steps; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.test_steps (id, test_case_id, "position", action, expected_result, created_at, updated_at) FROM stdin;
1	1	1	Open /login	Login form is shown	2026-09-30 12:04:18.275938+00	2026-09-30 12:04:18.275938+00
2	1	2	Enter valid email and password		2026-09-30 12:04:18.28903+00	2026-09-30 12:04:18.28903+00
3	1	3	Click "Sign in"	Dashboard is shown	2026-09-30 12:04:18.298807+00	2026-09-30 12:04:18.298807+00
4	3	1	Add a product to the cart		2026-09-30 12:04:18.32904+00	2026-09-30 12:04:18.32904+00
5	3	2	Pay with a test Visa card	Payment is approved	2026-09-30 12:04:18.338275+00	2026-09-30 12:04:18.338275+00
\.


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.goose_db_version_id_seq', 7, true);


--
-- Name: test_cases_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.test_cases_id_seq', 7, true);


--
-- Name: test_results_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.test_results_id_seq', 16, true);


--
-- Name: test_runs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.test_runs_id_seq', 5, true);


--
-- Name: test_steps_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.test_steps_id_seq', 5, true);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: test_cases test_cases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_cases
    ADD CONSTRAINT test_cases_pkey PRIMARY KEY (id);


--
-- Name: test_results test_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_results
    ADD CONSTRAINT test_results_pkey PRIMARY KEY (id);


--
-- Name: test_run_expected_cases test_run_expected_cases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_run_expected_cases
    ADD CONSTRAINT test_run_expected_cases_pkey PRIMARY KEY (test_run_id, test_case_id);


--
-- Name: test_run_parse_errors test_run_parse_errors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_run_parse_errors
    ADD CONSTRAINT test_run_parse_errors_pkey PRIMARY KEY (test_run_id, case_index);


--
-- Name: test_runs test_runs_external_run_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_runs
    ADD CONSTRAINT test_runs_external_run_id_key UNIQUE (external_run_id);


--
-- Name: test_runs test_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_runs
    ADD CONSTRAINT test_runs_pkey PRIMARY KEY (id);


--
-- Name: test_steps test_steps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_steps
    ADD CONSTRAINT test_steps_pkey PRIMARY KEY (id);


--
-- Name: test_steps test_steps_position_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_steps
    ADD CONSTRAINT test_steps_position_unique UNIQUE (test_case_id, "position") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: test_cases_expected_universe_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX test_cases_expected_universe_idx ON public.test_cases USING btree (id) WHERE ((status = 'active'::text) AND automated);


--
-- Name: test_results_run_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX test_results_run_idx ON public.test_results USING btree (test_run_id, id);


--
-- Name: test_results_test_case_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX test_results_test_case_idx ON public.test_results USING btree (test_case_id, id DESC) WHERE (test_case_id IS NOT NULL);


--
-- Name: test_cases test_cases_protect_identity; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER test_cases_protect_identity BEFORE DELETE OR UPDATE ON public.test_cases FOR EACH ROW EXECUTE FUNCTION public.test_cases_protect_identity();


--
-- Name: test_run_expected_cases test_run_expected_cases_immutable; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER test_run_expected_cases_immutable BEFORE DELETE OR UPDATE ON public.test_run_expected_cases FOR EACH ROW EXECUTE FUNCTION public.test_run_expected_cases_immutable();


--
-- Name: test_results test_results_test_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_results
    ADD CONSTRAINT test_results_test_run_id_fkey FOREIGN KEY (test_run_id) REFERENCES public.test_runs(id);


--
-- Name: test_run_expected_cases test_run_expected_cases_test_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_run_expected_cases
    ADD CONSTRAINT test_run_expected_cases_test_run_id_fkey FOREIGN KEY (test_run_id) REFERENCES public.test_runs(id);


--
-- Name: test_run_parse_errors test_run_parse_errors_test_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_run_parse_errors
    ADD CONSTRAINT test_run_parse_errors_test_run_id_fkey FOREIGN KEY (test_run_id) REFERENCES public.test_runs(id);


--
-- Name: test_steps test_steps_test_case_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_steps
    ADD CONSTRAINT test_steps_test_case_id_fkey FOREIGN KEY (test_case_id) REFERENCES public.test_cases(id);


--
-- PostgreSQL database dump complete
--

\unrestrict zfSN5CjbMafa2uDQK2CxBeI1R1DumXz4IwQ7fxVkBnfevAghKtJObab0Noquidm

