// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package integrationsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueDeliveries = `-- name: ClaimDueDeliveries :many
UPDATE webhook_deliveries d SET next_attempt_at = now() + interval '5 minutes'
WHERE d.id IN (
    SELECT x.id FROM webhook_deliveries x
    WHERE x.status = 'pending' AND x.next_attempt_at <= now()
    ORDER BY x.id LIMIT $1 FOR UPDATE SKIP LOCKED
)
RETURNING d.id, d.webhook_id, d.event, d.payload, d.status, d.attempts, d.next_attempt_at, d.last_status_code, d.last_error, d.created_at, d.completed_at
`

// Leases up to max_items due deliveries for 5 minutes (longer than a worker pass can take: 20 deliveries of at most
// 10 s each): concurrent workers skip each other's rows, and a worker that dies leaves its rows due again once the
// lease ends.
func (q *Queries) ClaimDueDeliveries(ctx context.Context, maxItems int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, claimDueDeliveries, maxItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.Event,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastStatusCode,
			&i.LastError,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDeliveries = `-- name: CountDeliveries :one
SELECT count(*) FROM webhook_deliveries WHERE webhook_id = $1
`

func (q *Queries) CountDeliveries(ctx context.Context, webhookID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDeliveries, webhookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (project_id, url, events, secret, created_by)
VALUES ($1, $2, $3::text[], $4, $5)
RETURNING id, project_id, url, events, secret, active, created_by, created_at, updated_at
`

type CreateWebhookParams struct {
	ProjectID int64
	Url       string
	Events    []string
	Secret    string
	CreatedBy string
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.ProjectID,
		arg.Url,
		arg.Events,
		arg.Secret,
		arg.CreatedBy,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Events,
		&i.Secret,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGitHubConnection = `-- name: DeleteGitHubConnection :execrows
DELETE FROM github_connections WHERE project_id = $1
`

func (q *Queries) DeleteGitHubConnection(ctx context.Context, projectID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGitHubConnection, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishAttempt = `-- name: FinishAttempt :execrows
UPDATE webhook_deliveries SET
    status = $1, attempts = $2, last_status_code = $3, last_error = $4,
    next_attempt_at = $5, completed_at = CASE WHEN $1::text = 'pending' THEN NULL ELSE now() END
WHERE id = $6 AND status = 'pending' AND attempts = $7::int
`

type FinishAttemptParams struct {
	Status          string
	Attempts        int32
	LastStatusCode  pgtype.Int4
	LastError       string
	NextAttemptAt   pgtype.Timestamptz
	ID              int64
	ClaimedAttempts int32
}

// Records one delivery attempt: still pending (retry at next_attempt_at), succeeded or failed for good. Only the
// attempt that was claimed is recorded: a late worker whose lease expired (the row was claimed and finished again)
// changes nothing.
func (q *Queries) FinishAttempt(ctx context.Context, arg FinishAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishAttempt,
		arg.Status,
		arg.Attempts,
		arg.LastStatusCode,
		arg.LastError,
		arg.NextAttemptAt,
		arg.ID,
		arg.ClaimedAttempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGitHubConnection = `-- name: GetGitHubConnection :one
SELECT project_id, repository, token, labels, last_synced_at, last_error, created_at, updated_at FROM github_connections WHERE project_id = $1
`

func (q *Queries) GetGitHubConnection(ctx context.Context, projectID int64) (GithubConnection, error) {
	row := q.db.QueryRow(ctx, getGitHubConnection, projectID)
	var i GithubConnection
	err := row.Scan(
		&i.ProjectID,
		&i.Repository,
		&i.Token,
		&i.Labels,
		&i.LastSyncedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, project_id, url, events, secret, active, created_by, created_at, updated_at FROM webhooks WHERE project_id = $1 AND id = $2
`

type GetWebhookParams struct {
	ProjectID int64
	ID        int64
}

func (q *Queries) GetWebhook(ctx context.Context, arg GetWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, arg.ProjectID, arg.ID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Events,
		&i.Secret,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, project_id, url, events, secret, active, created_by, created_at, updated_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhookByID(ctx context.Context, id int64) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhookByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Events,
		&i.Secret,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDelivery = `-- name: InsertDelivery :one
INSERT INTO webhook_deliveries (webhook_id, event, payload) VALUES ($1, $2, $3) RETURNING id
`

type InsertDeliveryParams struct {
	WebhookID int64
	Event     string
	Payload   []byte
}

func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertDelivery, arg.WebhookID, arg.Event, arg.Payload)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lastDeliveries = `-- name: LastDeliveries :many
SELECT DISTINCT ON (webhook_id) id, webhook_id, event, payload, status, attempts, next_attempt_at, last_status_code, last_error, created_at, completed_at FROM webhook_deliveries WHERE webhook_id = ANY($1::bigint[]) ORDER BY webhook_id, id DESC
`

// The latest delivery of each webhook.
func (q *Queries) LastDeliveries(ctx context.Context, webhookIds []int64) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, lastDeliveries, webhookIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.Event,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastStatusCode,
			&i.LastError,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, webhook_id, event, payload, status, attempts, next_attempt_at, last_status_code, last_error, created_at, completed_at FROM webhook_deliveries WHERE webhook_id = $1 ORDER BY id DESC LIMIT $3 OFFSET $2
`

type ListDeliveriesParams struct {
	WebhookID  int64
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries, arg.WebhookID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.Event,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastStatusCode,
			&i.LastError,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribedWebhooks = `-- name: ListSubscribedWebhooks :many
SELECT id FROM webhooks WHERE project_id = $1 AND active AND $2::text = ANY(events) ORDER BY id
`

type ListSubscribedWebhooksParams struct {
	ProjectID int64
	Event     string
}

// The active webhooks of a project subscribed to an event.
func (q *Queries) ListSubscribedWebhooks(ctx context.Context, arg ListSubscribedWebhooksParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listSubscribedWebhooks, arg.ProjectID, arg.Event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, project_id, url, events, secret, active, created_by, created_at, updated_at FROM webhooks WHERE project_id = $1 ORDER BY id
`

func (q *Queries) ListWebhooks(ctx context.Context, projectID int64) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.Events,
			&i.Secret,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeWebhookDeliveries = `-- name: PurgeWebhookDeliveries :execrows
WITH purge_lock AS (SELECT pg_try_advisory_xact_lock($1::bigint) AS held),
doomed AS (
    SELECT d.id FROM webhook_deliveries d, purge_lock
    WHERE purge_lock.held AND d.status <> 'pending' AND d.completed_at < $2
    ORDER BY d.id LIMIT $3
)
DELETE FROM webhook_deliveries WHERE id IN (SELECT id FROM doomed)
`

type PurgeWebhookDeliveriesParams struct {
	LockKey    int64
	Before     pgtype.Timestamptz
	BatchLimit int32
}

// Deletes up to batch_limit finished deliveries completed before `before` (the retention, decision 2026-10-06).
// The advisory lock (held for this statement) keeps two servers from purging at once: the one that does not get it
// deletes nothing. Pending deliveries are never purged.
func (q *Queries) PurgeWebhookDeliveries(ctx context.Context, arg PurgeWebhookDeliveriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeWebhookDeliveries, arg.LockKey, arg.Before, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordGitHubSync = `-- name: RecordGitHubSync :exec
UPDATE github_connections SET last_synced_at = coalesce($1, last_synced_at), last_error = $2, updated_at = now()
WHERE project_id = $3
`

type RecordGitHubSyncParams struct {
	SyncedAt  pgtype.Timestamptz
	LastError string
	ProjectID int64
}

func (q *Queries) RecordGitHubSync(ctx context.Context, arg RecordGitHubSyncParams) error {
	_, err := q.db.Exec(ctx, recordGitHubSync, arg.SyncedAt, arg.LastError, arg.ProjectID)
	return err
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks SET
    url        = coalesce($1, url),
    events     = coalesce($2::text[], events),
    active     = coalesce($3, active),
    updated_at = now()
WHERE project_id = $4 AND id = $5
RETURNING id
`

type UpdateWebhookParams struct {
	Url       pgtype.Text
	Events    []string
	Active    pgtype.Bool
	ProjectID int64
	ID        int64
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.Url,
		arg.Events,
		arg.Active,
		arg.ProjectID,
		arg.ID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertGitHubConnection = `-- name: UpsertGitHubConnection :exec
INSERT INTO github_connections (project_id, repository, token, labels)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id) DO UPDATE SET repository = EXCLUDED.repository, token = EXCLUDED.token, labels = EXCLUDED.labels,
    last_error = '', updated_at = now()
`

type UpsertGitHubConnectionParams struct {
	ProjectID  int64
	Repository string
	Token      string
	Labels     string
}

func (q *Queries) UpsertGitHubConnection(ctx context.Context, arg UpsertGitHubConnectionParams) error {
	_, err := q.db.Exec(ctx, upsertGitHubConnection,
		arg.ProjectID,
		arg.Repository,
		arg.Token,
		arg.Labels,
	)
	return err
}
