// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package integrationsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GithubConnection struct {
	ProjectID    int64
	Repository   string
	Token        string
	Labels       string
	LastSyncedAt pgtype.Timestamptz
	LastError    string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Webhook struct {
	ID        int64
	ProjectID int64
	Url       string
	Events    []string
	Secret    string
	Active    bool
	CreatedBy string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type WebhookDelivery struct {
	ID             int64
	WebhookID      int64
	Event          string
	Payload        []byte
	Status         string
	Attempts       int32
	NextAttemptAt  pgtype.Timestamptz
	LastStatusCode pgtype.Int4
	LastError      string
	CreatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
}
