// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package integrationsdb

import (
	"context"
)

type Querier interface {
	// Leases up to max_items due deliveries for 5 minutes (longer than a worker pass can take: 20 deliveries of at most
	// 10 s each): concurrent workers skip each other's rows, and a worker that dies leaves its rows due again once the
	// lease ends.
	ClaimDueDeliveries(ctx context.Context, maxItems int32) ([]WebhookDelivery, error)
	CountDeliveries(ctx context.Context, webhookID int64) (int64, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	DeleteGitHubConnection(ctx context.Context, projectID int64) (int64, error)
	// Records one delivery attempt: still pending (retry at next_attempt_at), succeeded or failed for good. Only the
	// attempt that was claimed is recorded: a late worker whose lease expired (the row was claimed and finished again)
	// changes nothing.
	FinishAttempt(ctx context.Context, arg FinishAttemptParams) (int64, error)
	GetGitHubConnection(ctx context.Context, projectID int64) (GithubConnection, error)
	GetWebhook(ctx context.Context, arg GetWebhookParams) (Webhook, error)
	GetWebhookByID(ctx context.Context, id int64) (Webhook, error)
	InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (int64, error)
	// The latest delivery of each webhook.
	LastDeliveries(ctx context.Context, webhookIds []int64) ([]WebhookDelivery, error)
	ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]WebhookDelivery, error)
	// The active webhooks of a project subscribed to an event.
	ListSubscribedWebhooks(ctx context.Context, arg ListSubscribedWebhooksParams) ([]int64, error)
	ListWebhooks(ctx context.Context, projectID int64) ([]Webhook, error)
	// Deletes up to batch_limit finished deliveries completed before `before` (the retention, decision 2026-10-06).
	// The advisory lock (held for this statement) keeps two servers from purging at once: the one that does not get it
	// deletes nothing. Pending deliveries are never purged.
	PurgeWebhookDeliveries(ctx context.Context, arg PurgeWebhookDeliveriesParams) (int64, error)
	RecordGitHubSync(ctx context.Context, arg RecordGitHubSyncParams) error
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (int64, error)
	UpsertGitHubConnection(ctx context.Context, arg UpsertGitHubConnectionParams) error
}

var _ Querier = (*Queries)(nil)
