// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPersonalAccessTokenProjects = `-- name: AddPersonalAccessTokenProjects :exec
INSERT INTO personal_access_token_projects (token_id, project_id)
SELECT $1, unnest($2::bigint[])
`

type AddPersonalAccessTokenProjectsParams struct {
	TokenID    int64
	ProjectIds []int64
}

func (q *Queries) AddPersonalAccessTokenProjects(ctx context.Context, arg AddPersonalAccessTokenProjectsParams) error {
	_, err := q.db.Exec(ctx, addPersonalAccessTokenProjects, arg.TokenID, arg.ProjectIds)
	return err
}

const countAPIKeys = `-- name: CountAPIKeys :one
SELECT count(*) FROM api_keys WHERE project_id = $1
`

func (q *Queries) CountAPIKeys(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAPIKeys, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*) FROM users WHERE is_admin AND deactivated_at IS NULL
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInvitations = `-- name: CountInvitations :one
SELECT count(*) FROM invitations
`

func (q *Queries) CountInvitations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInvitations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPersonalAccessTokens = `-- name: CountPersonalAccessTokens :one
SELECT count(*) FROM personal_access_tokens WHERE user_id = $1
`

func (q *Queries) CountPersonalAccessTokens(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPersonalAccessTokens, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectMembers = `-- name: CountProjectMembers :one
SELECT count(*) FROM project_members WHERE project_id = $1
`

func (q *Queries) CountProjectMembers(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectMembers, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (project_id, name, prefix, token_sha256, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, prefix, token_sha256, created_by, created_at, last_used_at, revoked_at
`

type CreateAPIKeyParams struct {
	ProjectID   int64
	Name        string
	Prefix      string
	TokenSha256 []byte
	CreatedBy   int64
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ProjectID,
		arg.Name,
		arg.Prefix,
		arg.TokenSha256,
		arg.CreatedBy,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.TokenSha256,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (token_sha256, email, note, created_by, expires_at, project_id, project_role)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, token_sha256, email, note, created_by, created_at, expires_at, accepted_at, accepted_user_id, revoked_at, project_id, project_role
`

type CreateInvitationParams struct {
	TokenSha256 []byte
	Email       pgtype.Text
	Note        string
	CreatedBy   int64
	ExpiresAt   pgtype.Timestamptz
	ProjectID   pgtype.Int8
	ProjectRole pgtype.Text
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.TokenSha256,
		arg.Email,
		arg.Note,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.ProjectID,
		arg.ProjectRole,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TokenSha256,
		&i.Email,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.RevokedAt,
		&i.ProjectID,
		&i.ProjectRole,
	)
	return i, err
}

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_resets (user_id, token_sha256, created_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_sha256, created_by, created_at, expires_at, used_at
`

type CreatePasswordResetParams struct {
	UserID      int64
	TokenSha256 []byte
	CreatedBy   pgtype.Int8
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, createPasswordReset,
		arg.UserID,
		arg.TokenSha256,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenSha256,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createPersonalAccessToken = `-- name: CreatePersonalAccessToken :one
INSERT INTO personal_access_tokens (user_id, name, prefix, token_sha256, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, prefix, token_sha256, created_at, expires_at, last_used_at, revoked_at
`

type CreatePersonalAccessTokenParams struct {
	UserID      int64
	Name        string
	Prefix      string
	TokenSha256 []byte
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreatePersonalAccessToken(ctx context.Context, arg CreatePersonalAccessTokenParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, createPersonalAccessToken,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.TokenSha256,
		arg.ExpiresAt,
	)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.TokenSha256,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, display_name, email, password_hash, is_admin)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (username) DO NOTHING
RETURNING id, username, display_name, email, password_hash, is_admin, created_at, updated_at, deactivated_at
`

type CreateUserParams struct {
	Username     string
	DisplayName  string
	Email        pgtype.Text
	PasswordHash string
	IsAdmin      bool
}

// No row when the username is taken.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :execrows
DELETE FROM project_members WHERE project_id = $1 AND user_id = $2
`

type DeleteMemberParams struct {
	ProjectID int64
	UserID    int64
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMember, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, project_id, name, prefix, token_sha256, created_by, created_at, last_used_at, revoked_at FROM api_keys WHERE id = $1 AND project_id = $2
`

type GetAPIKeyParams struct {
	ID        int64
	ProjectID int64
}

func (q *Queries) GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, arg.ID, arg.ProjectID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.TokenSha256,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByToken = `-- name: GetAPIKeyByToken :one
SELECT id, project_id, name, prefix, token_sha256, created_by, created_at, last_used_at, revoked_at FROM api_keys WHERE token_sha256 = $1
`

func (q *Queries) GetAPIKeyByToken(ctx context.Context, tokenSha256 []byte) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByToken, tokenSha256)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.TokenSha256,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getInvitation = `-- name: GetInvitation :one
SELECT id, token_sha256, email, note, created_by, created_at, expires_at, accepted_at, accepted_user_id, revoked_at, project_id, project_role FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitation(ctx context.Context, id int64) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TokenSha256,
		&i.Email,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.RevokedAt,
		&i.ProjectID,
		&i.ProjectRole,
	)
	return i, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM project_members WHERE project_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	ProjectID int64
	UserID    int64
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getPersonalAccessToken = `-- name: GetPersonalAccessToken :one
SELECT id, user_id, name, prefix, token_sha256, created_at, expires_at, last_used_at, revoked_at FROM personal_access_tokens WHERE id = $1 AND user_id = $2
`

type GetPersonalAccessTokenParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetPersonalAccessToken(ctx context.Context, arg GetPersonalAccessTokenParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, getPersonalAccessToken, arg.ID, arg.UserID)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.TokenSha256,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPersonalAccessTokenByToken = `-- name: GetPersonalAccessTokenByToken :one
SELECT id, user_id, name, prefix, token_sha256, created_at, expires_at, last_used_at, revoked_at FROM personal_access_tokens WHERE token_sha256 = $1
`

func (q *Queries) GetPersonalAccessTokenByToken(ctx context.Context, tokenSha256 []byte) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, getPersonalAccessTokenByToken, tokenSha256)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.TokenSha256,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, display_name, email, password_hash, is_admin, created_at, updated_at, deactivated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, email, password_hash, is_admin, created_at, updated_at, deactivated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, project_id, name, prefix, token_sha256, created_by, created_at, last_used_at, revoked_at FROM api_keys WHERE project_id = $1 ORDER BY id DESC LIMIT $3 OFFSET $2
`

type ListAPIKeysParams struct {
	ProjectID  int64
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, arg.ProjectID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Prefix,
			&i.TokenSha256,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, token_sha256, email, note, created_by, created_at, expires_at, accepted_at, accepted_user_id, revoked_at, project_id, project_role FROM invitations ORDER BY id DESC LIMIT $2 OFFSET $1
`

type ListInvitationsParams struct {
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitations, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.TokenSha256,
			&i.Email,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedUserID,
			&i.RevokedAt,
			&i.ProjectID,
			&i.ProjectRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalAccessTokenProjects = `-- name: ListPersonalAccessTokenProjects :many
SELECT token_id, project_id FROM personal_access_token_projects
WHERE token_id = ANY($1::bigint[]) ORDER BY token_id, project_id
`

// The projects of some tokens, in id order.
func (q *Queries) ListPersonalAccessTokenProjects(ctx context.Context, tokenIds []int64) ([]PersonalAccessTokenProject, error) {
	rows, err := q.db.Query(ctx, listPersonalAccessTokenProjects, tokenIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalAccessTokenProject
	for rows.Next() {
		var i PersonalAccessTokenProject
		if err := rows.Scan(&i.TokenID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalAccessTokens = `-- name: ListPersonalAccessTokens :many
SELECT id, user_id, name, prefix, token_sha256, created_at, expires_at, last_used_at, revoked_at FROM personal_access_tokens WHERE user_id = $1 ORDER BY id DESC LIMIT $3 OFFSET $2
`

type ListPersonalAccessTokensParams struct {
	UserID     int64
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListPersonalAccessTokens(ctx context.Context, arg ListPersonalAccessTokensParams) ([]PersonalAccessToken, error) {
	rows, err := q.db.Query(ctx, listPersonalAccessTokens, arg.UserID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalAccessToken
	for rows.Next() {
		var i PersonalAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.TokenSha256,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT users.id, users.username, users.display_name, users.email, users.password_hash, users.is_admin, users.created_at, users.updated_at, users.deactivated_at, m.role AS member_role, m.created_at AS member_since
FROM project_members m JOIN users ON users.id = m.user_id
WHERE m.project_id = $1
ORDER BY users.username
LIMIT $3 OFFSET $2
`

type ListProjectMembersParams struct {
	ProjectID  int64
	PageOffset int32
	PageLimit  int32
}

type ListProjectMembersRow struct {
	User        User
	MemberRole  string
	MemberSince pgtype.Timestamptz
}

func (q *Queries) ListProjectMembers(ctx context.Context, arg ListProjectMembersParams) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, arg.ProjectID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersRow
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.DisplayName,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.IsAdmin,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeactivatedAt,
			&i.MemberRole,
			&i.MemberSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMemberships = `-- name: ListUserMemberships :many
SELECT project_id, role FROM project_members WHERE user_id = $1
`

type ListUserMembershipsRow struct {
	ProjectID int64
	Role      string
}

func (q *Queries) ListUserMemberships(ctx context.Context, userID int64) ([]ListUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listUserMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserMembershipsRow
	for rows.Next() {
		var i ListUserMembershipsRow
		if err := rows.Scan(&i.ProjectID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, email, password_hash, is_admin, created_at, updated_at, deactivated_at FROM users ORDER BY username LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeactivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInvitationByToken = `-- name: LockInvitationByToken :one
SELECT id, token_sha256, email, note, created_by, created_at, expires_at, accepted_at, accepted_user_id, revoked_at, project_id, project_role FROM invitations WHERE token_sha256 = $1 FOR UPDATE
`

// Locks the invitation so two acceptances of one link cannot both create a user.
func (q *Queries) LockInvitationByToken(ctx context.Context, tokenSha256 []byte) (Invitation, error) {
	row := q.db.QueryRow(ctx, lockInvitationByToken, tokenSha256)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TokenSha256,
		&i.Email,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.RevokedAt,
		&i.ProjectID,
		&i.ProjectRole,
	)
	return i, err
}

const lockPasswordResetByToken = `-- name: LockPasswordResetByToken :one
SELECT id, user_id, token_sha256, created_by, created_at, expires_at, used_at FROM password_resets WHERE token_sha256 = $1 FOR UPDATE
`

// Locks the link so two uses of it cannot both set a password.
func (q *Queries) LockPasswordResetByToken(ctx context.Context, tokenSha256 []byte) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, lockPasswordResetByToken, tokenSha256)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenSha256,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :exec
UPDATE invitations SET accepted_at = now(), accepted_user_id = $1 WHERE id = $2
`

type MarkInvitationAcceptedParams struct {
	UserID pgtype.Int8
	ID     int64
}

func (q *Queries) MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) error {
	_, err := q.db.Exec(ctx, markInvitationAccepted, arg.UserID, arg.ID)
	return err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_resets SET used_at = now() WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markPasswordResetUsed, id)
	return err
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys SET revoked_at = now()
WHERE id = $1 AND project_id = $2 AND revoked_at IS NULL
RETURNING id, project_id, name, prefix, token_sha256, created_by, created_at, last_used_at, revoked_at
`

type RevokeAPIKeyParams struct {
	ID        int64
	ProjectID int64
}

// No row when the key does not exist in the project or is already revoked.
func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.ProjectID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.TokenSha256,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeInvitation = `-- name: RevokeInvitation :one
UPDATE invitations SET revoked_at = now()
WHERE id = $1 AND accepted_at IS NULL AND revoked_at IS NULL
RETURNING id, token_sha256, email, note, created_by, created_at, expires_at, accepted_at, accepted_user_id, revoked_at, project_id, project_role
`

// No row when the invitation does not exist or is already accepted or revoked.
func (q *Queries) RevokeInvitation(ctx context.Context, id int64) (Invitation, error) {
	row := q.db.QueryRow(ctx, revokeInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TokenSha256,
		&i.Email,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.RevokedAt,
		&i.ProjectID,
		&i.ProjectRole,
	)
	return i, err
}

const revokePersonalAccessToken = `-- name: RevokePersonalAccessToken :one
UPDATE personal_access_tokens SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
RETURNING id, user_id, name, prefix, token_sha256, created_at, expires_at, last_used_at, revoked_at
`

type RevokePersonalAccessTokenParams struct {
	ID     int64
	UserID int64
}

// No row when the token is not the user's or is already revoked.
func (q *Queries) RevokePersonalAccessToken(ctx context.Context, arg RevokePersonalAccessTokenParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, revokePersonalAccessToken, arg.ID, arg.UserID)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.TokenSha256,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeUserPersonalAccessTokens = `-- name: RevokeUserPersonalAccessTokens :exec
UPDATE personal_access_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

// Deactivating a user revokes every token they still have.
func (q *Queries) RevokeUserPersonalAccessTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeUserPersonalAccessTokens, userID)
	return err
}

const setPasswordHash = `-- name: SetPasswordHash :one
UPDATE users SET password_hash = $1, updated_at = now() WHERE id = $2 RETURNING id, username, display_name, email, password_hash, is_admin, created_at, updated_at, deactivated_at
`

type SetPasswordHashParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) (User, error) {
	row := q.db.QueryRow(ctx, setPasswordHash, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const setUserDeactivated = `-- name: SetUserDeactivated :one
UPDATE users SET deactivated_at = $1, updated_at = now() WHERE id = $2 RETURNING id, username, display_name, email, password_hash, is_admin, created_at, updated_at, deactivated_at
`

type SetUserDeactivatedParams struct {
	DeactivatedAt pgtype.Timestamptz
	ID            int64
}

// deactivated_at NULL reactivates the user.
func (q *Queries) SetUserDeactivated(ctx context.Context, arg SetUserDeactivatedParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserDeactivated, arg.DeactivatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

// Records a use at most once a minute: a busy CI does not write on every report.
func (q *Queries) TouchAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}

const touchPersonalAccessToken = `-- name: TouchPersonalAccessToken :exec
UPDATE personal_access_tokens SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

// Records a use at most once a minute: a busy script does not write on every request.
func (q *Queries) TouchPersonalAccessToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchPersonalAccessToken, id)
	return err
}

const upsertMember = `-- name: UpsertMember :one
INSERT INTO project_members (project_id, user_id, role) VALUES ($1, $2, $3)
ON CONFLICT (project_id, user_id) DO UPDATE SET role = EXCLUDED.role, updated_at = now()
RETURNING project_id, user_id, role, created_at, updated_at
`

type UpsertMemberParams struct {
	ProjectID int64
	UserID    int64
	Role      string
}

func (q *Queries) UpsertMember(ctx context.Context, arg UpsertMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, upsertMember, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const voidPasswordResets = `-- name: VoidPasswordResets :exec
UPDATE password_resets SET used_at = now() WHERE user_id = $1 AND used_at IS NULL
`

// A new link, or a used one, voids the user's other pending links.
func (q *Queries) VoidPasswordResets(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, voidPasswordResets, userID)
	return err
}
