// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInvitations = `-- name: CountInvitations :one
SELECT count(*) FROM invitations
`

func (q *Queries) CountInvitations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInvitations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (token_sha256, email, note, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token_sha256, email, note, created_by, created_at, expires_at, accepted_at, accepted_user_id, revoked_at
`

type CreateInvitationParams struct {
	TokenSha256 []byte
	Email       pgtype.Text
	Note        string
	CreatedBy   int64
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.TokenSha256,
		arg.Email,
		arg.Note,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TokenSha256,
		&i.Email,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, display_name, email, password_hash, is_admin)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (username) DO NOTHING
RETURNING id, username, display_name, email, password_hash, is_admin, created_at, updated_at
`

type CreateUserParams struct {
	Username     string
	DisplayName  string
	Email        pgtype.Text
	PasswordHash string
	IsAdmin      bool
}

// No row when the username is taken.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitation = `-- name: GetInvitation :one
SELECT id, token_sha256, email, note, created_by, created_at, expires_at, accepted_at, accepted_user_id, revoked_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitation(ctx context.Context, id int64) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TokenSha256,
		&i.Email,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.RevokedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, display_name, email, password_hash, is_admin, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, email, password_hash, is_admin, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, token_sha256, email, note, created_by, created_at, expires_at, accepted_at, accepted_user_id, revoked_at FROM invitations ORDER BY id DESC LIMIT $2 OFFSET $1
`

type ListInvitationsParams struct {
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitations, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.TokenSha256,
			&i.Email,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedUserID,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, email, password_hash, is_admin, created_at, updated_at FROM users ORDER BY username LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInvitationByToken = `-- name: LockInvitationByToken :one
SELECT id, token_sha256, email, note, created_by, created_at, expires_at, accepted_at, accepted_user_id, revoked_at FROM invitations WHERE token_sha256 = $1 FOR UPDATE
`

// Locks the invitation so two acceptances of one link cannot both create a user.
func (q *Queries) LockInvitationByToken(ctx context.Context, tokenSha256 []byte) (Invitation, error) {
	row := q.db.QueryRow(ctx, lockInvitationByToken, tokenSha256)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TokenSha256,
		&i.Email,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.RevokedAt,
	)
	return i, err
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :exec
UPDATE invitations SET accepted_at = now(), accepted_user_id = $1 WHERE id = $2
`

type MarkInvitationAcceptedParams struct {
	UserID pgtype.Int8
	ID     int64
}

func (q *Queries) MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) error {
	_, err := q.db.Exec(ctx, markInvitationAccepted, arg.UserID, arg.ID)
	return err
}

const revokeInvitation = `-- name: RevokeInvitation :one
UPDATE invitations SET revoked_at = now()
WHERE id = $1 AND accepted_at IS NULL AND revoked_at IS NULL
RETURNING id, token_sha256, email, note, created_by, created_at, expires_at, accepted_at, accepted_user_id, revoked_at
`

// No row when the invitation does not exist or is already accepted or revoked.
func (q *Queries) RevokeInvitation(ctx context.Context, id int64) (Invitation, error) {
	row := q.db.QueryRow(ctx, revokeInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TokenSha256,
		&i.Email,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.RevokedAt,
	)
	return i, err
}

const setPasswordHash = `-- name: SetPasswordHash :one
UPDATE users SET password_hash = $1, updated_at = now() WHERE id = $2 RETURNING id, username, display_name, email, password_hash, is_admin, created_at, updated_at
`

type SetPasswordHashParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) (User, error) {
	row := q.db.QueryRow(ctx, setPasswordHash, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
