// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Invitation struct {
	ID             int64
	TokenSha256    []byte
	Email          pgtype.Text
	Note           string
	CreatedBy      int64
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	AcceptedAt     pgtype.Timestamptz
	AcceptedUserID pgtype.Int8
	RevokedAt      pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	DisplayName  string
	Email        pgtype.Text
	PasswordHash string
	IsAdmin      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
