// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          int64
	ProjectID   int64
	Name        string
	Prefix      string
	TokenSha256 []byte
	CreatedBy   int64
	CreatedAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type Invitation struct {
	ID             int64
	TokenSha256    []byte
	Email          pgtype.Text
	Note           string
	CreatedBy      int64
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	AcceptedAt     pgtype.Timestamptz
	AcceptedUserID pgtype.Int8
	RevokedAt      pgtype.Timestamptz
	ProjectID      pgtype.Int8
	ProjectRole    pgtype.Text
}

type Project struct {
	ID          int64
	Key         string
	Name        string
	Description string
	NextNumber  int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProjectMember struct {
	ProjectID int64
	UserID    int64
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TestCase struct {
	ID             int64
	Title          string
	Description    string
	ExpectedResult string
	Status         string
	Automated      bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeprecatedAt   pgtype.Timestamptz
	ProjectID      int64
	Number         int64
}

type TestStep struct {
	ID             int64
	TestCaseID     int64
	Position       int32
	Action         string
	ExpectedResult string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	DisplayName  string
	Email        pgtype.Text
	PasswordHash string
	IsAdmin      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
