// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"context"
)

type Querier interface {
	CountAPIKeys(ctx context.Context, projectID int64) (int64, error)
	CountActiveAdmins(ctx context.Context) (int64, error)
	CountInvitations(ctx context.Context) (int64, error)
	CountProjectMembers(ctx context.Context, projectID int64) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error)
	// No row when the username is taken.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMember(ctx context.Context, arg DeleteMemberParams) (int64, error)
	GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error)
	GetAPIKeyByToken(ctx context.Context, tokenSha256 []byte) (ApiKey, error)
	GetInvitation(ctx context.Context, id int64) (Invitation, error)
	GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKey, error)
	ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]Invitation, error)
	ListProjectMembers(ctx context.Context, arg ListProjectMembersParams) ([]ListProjectMembersRow, error)
	ListUserMemberships(ctx context.Context, userID int64) ([]ListUserMembershipsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Locks the invitation so two acceptances of one link cannot both create a user.
	LockInvitationByToken(ctx context.Context, tokenSha256 []byte) (Invitation, error)
	// Locks the link so two uses of it cannot both set a password.
	LockPasswordResetByToken(ctx context.Context, tokenSha256 []byte) (PasswordReset, error)
	MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) error
	MarkPasswordResetUsed(ctx context.Context, id int64) error
	// No row when the key does not exist in the project or is already revoked.
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error)
	// No row when the invitation does not exist or is already accepted or revoked.
	RevokeInvitation(ctx context.Context, id int64) (Invitation, error)
	SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) (User, error)
	// deactivated_at NULL reactivates the user.
	SetUserDeactivated(ctx context.Context, arg SetUserDeactivatedParams) (User, error)
	// Records a use at most once a minute: a busy CI does not write on every report.
	TouchAPIKey(ctx context.Context, id int64) error
	UpsertMember(ctx context.Context, arg UpsertMemberParams) (ProjectMember, error)
	// A new link, or a used one, voids the user's other pending links.
	VoidPasswordResets(ctx context.Context, userID int64) error
}

var _ Querier = (*Queries)(nil)
