// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"context"
)

type Querier interface {
	CountInvitations(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	// No row when the username is taken.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetInvitation(ctx context.Context, id int64) (Invitation, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]Invitation, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Locks the invitation so two acceptances of one link cannot both create a user.
	LockInvitationByToken(ctx context.Context, tokenSha256 []byte) (Invitation, error)
	MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) error
	// No row when the invitation does not exist or is already accepted or revoked.
	RevokeInvitation(ctx context.Context, id int64) (Invitation, error)
	SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) (User, error)
}

var _ Querier = (*Queries)(nil)
